// HSK 1 Vocabulary (150 words)
export const hsk1Vocab = [
  { char: "我", pinyin: "wǒ", de: "ich", en: "I", es: "yo", ar: "أنا", hi: "मैं", cat: "Pronomen", icon: "👤" },
  { char: "你", pinyin: "nǐ", de: "du", en: "you", es: "tú", ar: "أنت", hi: "तुम", cat: "Pronomen", icon: "👈" },
  { char: "他", pinyin: "tā", de: "er", en: "he", es: "él", ar: "هو", hi: "वह (पुरुष)", cat: "Pronomen", icon: "👨" },
  { char: "她", pinyin: "tā", de: "sie", en: "she", es: "ella", ar: "هي", hi: "वह (स्त्री)", cat: "Pronomen", icon: "👩" },
  { char: "我们", pinyin: "wǒ men", de: "wir", en: "we", es: "nosotros", ar: "نحن", hi: "हम", cat: "Pronomen", icon: "👥" },
  { char: "这", pinyin: "zhè", de: "dies", en: "this", es: "este", ar: "هذا", hi: "यह", cat: "Pronomen", icon: "📍" },
  { char: "那", pinyin: "nà", de: "jenes", en: "that", es: "eso", ar: "ذلك", hi: "वह", cat: "Pronomen", icon: "👉" },
  { char: "谁", pinyin: "shéi", de: "wer", en: "who", es: "quién", ar: "من", hi: "कौन", cat: "Pronomen", icon: "🕵️" },
  { char: "什么", pinyin: "shén me", de: "was", en: "what", es: "qué", ar: "ماذا", hi: "क्या", cat: "Pronomen", icon: "🤔" },
  { char: "怎么", pinyin: "zěn me", de: "wie", en: "how", es: "cómo", ar: "كيف", hi: "कैसे", cat: "Pronomen", icon: "⚙️" },
  { char: "一", pinyin: "yī", de: "eins", en: "one", es: "uno", ar: "واحد", hi: "एक", cat: "Zahlen", icon: "1️⃣" },
  { char: "二", pinyin: "èr", de: "zwei", en: "two", es: "dos", ar: "اثنان", hi: "दो", cat: "Zahlen", icon: "2️⃣" },
  { char: "三", pinyin: "sān", de: "drei", en: "three", es: "tres", ar: "ثلاثة", hi: "तीन", cat: "Zahlen", icon: "3️⃣" },
  { char: "四", pinyin: "sì", de: "vier", en: "four", es: "cuatro", ar: "أربعة", hi: "चार", cat: "Zahlen", icon: "4️⃣" },
  { char: "五", pinyin: "wǔ", de: "fünf", en: "five", es: "cinco", ar: "خمسة", hi: "पाँच", cat: "Zahlen", icon: "5️⃣" },
  { char: "六", pinyin: "liù", de: "sechs", en: "six", es: "seis", ar: "ستة", hi: "छह", cat: "Zahlen", icon: "6️⃣" },
  { char: "七", pinyin: "qī", de: "sieben", en: "seven", es: "siete", ar: "سبعة", hi: "सात", cat: "Zahlen", icon: "7️⃣" },
  { char: "八", pinyin: "bā", de: "acht", en: "eight", es: "ocho", ar: "ثمانية", hi: "आठ", cat: "Zahlen", icon: "8️⃣" },
  { char: "九", pinyin: "jiǔ", de: "neun", en: "nine", es: "nueve", ar: "تسعة", hi: "नौ", cat: "Zahlen", icon: "9️⃣" },
  { char: "十", pinyin: "shí", de: "zehn", en: "ten", es: "diez", ar: "عشرة", hi: "दस", cat: "Zahlen", icon: "🔟" },

  { char: "今天", pinyin: "jīn tiān", de: "heute", en: "today", es: "hoy", ar: "اليوم", hi: "आज", cat: "Zeit", icon: "📅" },
  { char: "明天", pinyin: "míng tiān", de: "morgen", en: "tomorrow", es: "mañana", ar: "غداً", hi: "कल (आने वाला)", cat: "Zeit", icon: "⏩" },
  { char: "昨天", pinyin: "zuó tiān", de: "gestern", en: "yesterday", es: "ayer", ar: "أمس", hi: "कल (बीता हुआ)", cat: "Zeit", icon: "⏪" },
  { char: "年", pinyin: "nián", de: "Jahr", en: "year", es: "año", ar: "سنة", hi: "साल", cat: "Zeit", icon: "🎇" },
  { char: "月", pinyin: "yuè", de: "Monat", en: "month", es: "mes", ar: "شهر", hi: "महीना", cat: "Zeit", icon: "🌙" },
  { char: "日", pinyin: "rì", de: "Tag", en: "day", es: "día", ar: "يوم", hi: "दिन", cat: "Zeit", icon: "🌞" },
  { char: "星期", pinyin: "xīng qī", de: "Woche", en: "week", es: "semana", ar: "أسبوع", hi: "सप्ताह", cat: "Zeit", icon: "📆" },
  { char: "现在", pinyin: "xiàn zài", de: "jetzt", en: "now", es: "ahora", ar: "الآن", hi: "अभी", cat: "Zeit", icon: "⏱️" },
  { char: "家", pinyin: "jiā", de: "Zuhause", en: "home", es: "casa", ar: "منزل", hi: "घर", cat: "Orte", icon: "🏠" },
  { char: "学校", pinyin: "xué xiào", de: "Schule", en: "school", es: "escuela", ar: "مدرسة", hi: "स्कूल", cat: "Orte", icon: "🏫" },
  { char: "饭店", pinyin: "fàn diàn", de: "Restaurant", en: "restaurant", es: "restaurante", ar: "مطعم", hi: "रेस्तरां", cat: "Orte", icon: "🍜" },
  { char: "商店", pinyin: "shāng diàn", de: "Laden", en: "shop", es: "tienda", ar: "متجر", hi: "दुकान", cat: "Orte", icon: "🛒" },
  { char: "医院", pinyin: "yī yuàn", de: "Krankenhaus", en: "hospital", es: "hospital", ar: "مستشفى", hi: "अस्पताल", cat: "Orte", icon: "🏥" },
  { char: "中国", pinyin: "zhōng guó", de: "China", en: "China", es: "China", ar: "الصين", hi: "चीन", cat: "Orte", icon: "🇨🇳" },
  { char: "北京", pinyin: "běi jīng", de: "Peking", en: "Beijing", es: "Pekín", ar: "بكين", hi: "बीजिंग", cat: "Orte", icon: "🏯" },
  { char: "爸爸", pinyin: "bà ba", de: "Papa", en: "dad", es: "papá", ar: "أبي", hi: "पापा", cat: "Personen", icon: "🧔" },
  { char: "妈妈", pinyin: "mā ma", de: "Mama", en: "mom", es: "mamá", ar: "أمي", hi: "माँ", cat: "Personen", icon: "👩" },
  { char: "老师", pinyin: "lǎo shī", de: "Lehrer", en: "teacher", es: "profesor", ar: "معلم", hi: "शिक्षक", cat: "Personen", icon: "👨‍🏫" },
  { char: "学生", pinyin: "xué sheng", de: "Schüler", en: "student", es: "estudiante", ar: "طالب", hi: "छात्र", cat: "Personen", icon: "🎒" },
  { char: "朋友", pinyin: "péng you", de: "Freund", en: "friend", es: "amigo", ar: "صديق", hi: "दोस्त", cat: "Personen", icon: "👫" },
  { char: "医生", pinyin: "yī shēng", de: "Arzt", en: "doctor", es: "médico", ar: "طبيب", hi: "डॉक्टर", cat: "Personen", icon: "🩺" },
  { char: "人", pinyin: "rén", de: "Mensch", en: "person", es: "persona", ar: "شخص", hi: "व्यक्ति", cat: "Personen", icon: "👤" },
  { char: "水", pinyin: "shuǐ", de: "Wasser", en: "water", es: "agua", ar: "ماء", hi: "पानी", cat: "Essen", icon: "💧" },
  { char: "茶", pinyin: "chá", de: "Tee", en: "tea", es: "té", ar: "شاي", hi: "चाय", cat: "Essen", icon: "🍵" },
  { char: "米饭", pinyin: "mǐ fàn", de: "Reis", en: "rice", es: "arroz", ar: "أرز", hi: "चावल", cat: "Essen", icon: "🍚" },
  { char: "苹果", pinyin: "píng guǒ", de: "Apfel", en: "apple", es: "manzana", ar: "تفاحة", hi: "सेब", cat: "Essen", icon: "🍎" },
  { char: "钱", pinyin: "qián", de: "Geld", en: "money", es: "dinero", ar: "مال", hi: "पैसा", cat: "Dinge", icon: "💰" },
  { char: "飞机", pinyin: "fēi jī", de: "Flugzeug", en: "airplane", es: "avión", ar: "طائرة", hi: "हवाई जहाज", cat: "Dinge", icon: "✈️" },
  { char: "电视", pinyin: "diàn shì", de: "TV", en: "TV", es: "tele", ar: "تلفزيون", hi: "टीवी", cat: "Dinge", icon: "📺" },
  { char: "电脑", pinyin: "diàn nǎo", de: "Computer", en: "computer", es: "ordenador", ar: "حاسوب", hi: "कंप्यूटर", cat: "Dinge", icon: "💻" },
  { char: "书", pinyin: "shū", de: "Buch", en: "book", es: "libro", ar: "كتاب", hi: "किताब", cat: "Dinge", icon: "📕" },
  { char: "猫", pinyin: "māo", de: "Katze", en: "cat", es: "gato", ar: "قطة", hi: "बिल्ली", cat: "Natur", icon: "🐱" },
  { char: "狗", pinyin: "gǒu", de: "Hund", en: "dog", es: "perro", ar: "كلب", hi: "कुत्ता", cat: "Natur", icon: "🐶" },
  { char: "天气", pinyin: "tiān qì", de: "Wetter", en: "weather", es: "clima", ar: "طقس", hi: "मौसम", cat: "Natur", icon: "☁️" },
  { char: "名字", pinyin: "míng zi", de: "Name", en: "name", es: "nombre", ar: "اسم", hi: "नाम", cat: "Dinge", icon: "📛" },
  { char: "谢谢", pinyin: "xiè xie", de: "danke", en: "thanks", es: "gracias", ar: "شكراً", hi: "धन्यवाद", cat: "Verben", icon: "🙏" },
  { char: "再见", pinyin: "zài jiàn", de: "tschüss", en: "bye", es: "adiós", ar: "وداعاً", hi: "अलविदा", cat: "Verben", icon: "👋" },
  { char: "请", pinyin: "qǐng", de: "bitte", en: "please", es: "por favor", ar: "من فضلك", hi: "कृपया", cat: "Verben", icon: "👐" },
  { char: "是", pinyin: "shì", de: "sein", en: "be", es: "ser", ar: "يكون", hi: "होना", cat: "Verben", icon: "✅" },
  { char: "有", pinyin: "yǒu", de: "haben", en: "have", es: "tener", ar: "يملك", hi: "रखना", cat: "Verben", icon: "🤲" },
  { char: "看", pinyin: "kàn", de: "sehen", en: "look", es: "ver", ar: "ينظر", hi: "देखना", cat: "Verben", icon: "👁️" },
  { char: "听", pinyin: "tīng", de: "hören", en: "listen", es: "escuchar", ar: "يستمع", hi: "सुनना", cat: "Verben", icon: "👂" },
  { char: "说", pinyin: "shuō", de: "sagen", en: "speak", es: "hablar", ar: "يتكلم", hi: "बोलना", cat: "Verben", icon: "🗣️" },
  { char: "读", pinyin: "dú", de: "lesen", en: "read", es: "leer", ar: "يقرأ", hi: "पढ़ना", cat: "Verben", icon: "📖" },
  { char: "写", pinyin: "xiě", de: "schreiben", en: "write", es: "escribir", ar: "يكتب", hi: "लिखना", cat: "Verben", icon: "✍️" },
  { char: "叫", pinyin: "jiào", de: "heißen", en: "be called", es: "llamarse", ar: "يُدعى", hi: "कहलाना", cat: "Verben", icon: "📛" },
  { char: "来", pinyin: "lái", de: "kommen", en: "come", es: "venir", ar: "يأتي", hi: "आना", cat: "Verben", icon: "🚶" },
  { char: "去", pinyin: "qù", de: "gehen", en: "go", es: "ir", ar: "يذهب", hi: "जाना", cat: "Verben", icon: "🏃" },
  { char: "吃", pinyin: "chī", de: "essen", en: "eat", es: "comer", ar: "يأكل", hi: "खाना", cat: "Verben", icon: "👄" },
  { char: "喝", pinyin: "hē", de: "trinken", en: "drink", es: "beber", ar: "يشرب", hi: "पीना", cat: "Verben", icon: "🥤" },
  { char: "睡觉", pinyin: "shuì jiào", de: "schlafen", en: "sleep", es: "dormir", ar: "ينام", hi: "सोना", cat: "Verben", icon: "😴" },
  { char: "做", pinyin: "zuò", de: "machen", en: "do", es: "hacer", ar: "يفعل", hi: "करना", cat: "Verben", icon: "🔨" },
  { char: "买", pinyin: "mǎi", de: "kaufen", en: "buy", es: "comprar", ar: "يشتري", hi: "खरीदना", cat: "Verben", icon: "🛍️" },
  { char: "住", pinyin: "zhù", de: "wohnen", en: "live", es: "vivir", ar: "يسكن", hi: "रहना", cat: "Verben", icon: "🏘️" },
  { char: "学习", pinyin: "xué xí", de: "lernen", en: "study", es: "estudiar", ar: "يدرس", hi: "पढ़ाई करना", cat: "Verben", icon: "📚" },
  { char: "工作", pinyin: "gōng zuò", de: "arbeiten", en: "work", es: "trabajar", ar: "يعمل", hi: "काम करना", cat: "Verben", icon: "💼" },
  { char: "爱", pinyin: "ài", de: "lieben", en: "love", es: "amar", ar: "يحب", hi: "प्यार करना", cat: "Gefühle", icon: "❤️" },
  { char: "喜欢", pinyin: "xǐ huan", de: "mögen", en: "like", es: "gustar", ar: "يعجب", hi: "पसंद करना", cat: "Gefühle", icon: "🥰" },
  { char: "想", pinyin: "xiǎng", de: "denken", en: "think", es: "pensar", ar: "يفكر", hi: "सोचना", cat: "Gefühle", icon: "🧠" },
  { char: "会", pinyin: "huì", de: "können", en: "can", es: "saber", ar: "يستطيع", hi: "सकना", cat: "Verben", icon: "🎓" },
  { char: "能", pinyin: "néng", de: "können", en: "can", es: "poder", ar: "يقدر", hi: "कर सकना", cat: "Verben", icon: "💪" },
  { char: "好", pinyin: "hǎo", de: "gut", en: "good", es: "bueno", ar: "جيد", hi: "अच्छा", cat: "Adjektive", icon: "👍" },
  { char: "大", pinyin: "dà", de: "groß", en: "big", es: "grande", ar: "كبير", hi: "बड़ा", cat: "Adjektive", icon: "🐘" },
  { char: "小", pinyin: "xiǎo", de: "klein", en: "small", es: "pequeño", ar: "صغير", hi: "छोटा", cat: "Adjektive", icon: "🐭" },
  { char: "多", pinyin: "duō", de: "viel", en: "many", es: "mucho", ar: "كثير", hi: "बहुत", cat: "Adjektive", icon: "➕" },
  { char: "少", pinyin: "shǎo", de: "wenig", en: "few", es: "poco", ar: "قليل", hi: "कम", cat: "Adjektive", icon: "➖" },
  { char: "冷", pinyin: "lěng", de: "kalt", en: "cold", es: "frío", ar: "بارد", hi: "ठंडा", cat: "Wetter", icon: "❄️" },
  { char: "热", pinyin: "rè", de: "heiß", en: "hot", es: "caliente", ar: "حار", hi: "गर्म", cat: "Wetter", icon: "🔥" },
  { char: "高兴", pinyin: "gāo xìng", de: "froh", en: "happy", es: "feliz", ar: "سعيد", hi: "खुश", cat: "Gefühle", icon: "😊" },
  { char: "漂亮", pinyin: "piào liang", de: "hübsch", en: "pretty", es: "hermoso", ar: "جميل", hi: "सुंदर", cat: "Adjektive", icon: "✨" },
  { char: "不", pinyin: "bù", de: "nicht", en: "not", es: "no", ar: "لا", hi: "नहीं", cat: "Grammatik", icon: "❌" },
  { char: "很", pinyin: "hěn", de: "sehr", en: "very", es: "muy", ar: "جداً", hi: "बहुत", cat: "Grammatik", icon: "🚀" },
  { char: "都", pinyin: "dōu", de: "alle", en: "all", es: "todos", ar: "الكل", hi: "सभी", cat: "Grammatik", icon: "🌎" },
  { char: "和", pinyin: "hé", de: "und", en: "and", es: "y", ar: "و", hi: "और", cat: "Grammatik", icon: "➕" },
  { char: "在", pinyin: "zài", de: "in/bei", en: "at/in", es: "en", ar: "في", hi: "में", cat: "Grammatik", icon: "📍" },
  { char: "的", pinyin: "de", de: "Besitz-P.", en: "possessive", es: "posesivo", ar: "ملكية", hi: "का/की/के", cat: "Grammatik", icon: "🔗" },

  { char: "没有", pinyin: "méi yǒu", de: "nicht haben", en: "don't have", es: "no tener", ar: "لا يملك", hi: "नहीं है", cat: "Grammatik", icon: "🚫" },
  { char: "哪", pinyin: "nǎ", de: "welche", en: "which", es: "cuál", ar: "أي", hi: "कौन सा", cat: "Pronomen", icon: "❓" },
  { char: "哪儿", pinyin: "nǎr", de: "wo", en: "where", es: "dónde", ar: "أين", hi: "कहाँ", cat: "Pronomen", icon: "📍" },

  { char: "呢", pinyin: "ne", de: "und du?", en: "what about", es: "¿y tú?", ar: "ماذا عنك", hi: "और तुम", cat: "Grammatik", icon: "❓" },
  { char: "吗", pinyin: "ma", de: "Frage-P.", en: "question", es: "partícula", ar: "سؤال", hi: "क्या", cat: "Grammatik", icon: "❓" },
  { char: "太", pinyin: "tài", de: "zu (sehr)", en: "too", es: "demasiado", ar: "جداً", hi: "बहुत ज़्यादा", cat: "Grammatik", icon: "⚡" },
  { char: "几", pinyin: "jǐ", de: "wie viele", en: "how many", es: "cuántos", ar: "كم", hi: "कितने", cat: "Zahlen", icon: "🔢" },
  { char: "多少", pinyin: "duōshao", de: "wie viel", en: "how much", es: "cuánto", ar: "كم", hi: "कितना", cat: "Zahlen", icon: "🔢" },
  { char: "块", pinyin: "kuài", de: "Yuan", en: "yuan", es: "yuan", ar: "يوان", hi: "युआन", cat: "Geld", icon: "💴" },
  { char: "岁", pinyin: "suì", de: "Jahre alt", en: "years old", es: "años", ar: "سنة عمر", hi: "साल (उम्र)", cat: "Zeit", icon: "🎂" },
  { char: "点", pinyin: "diǎn", de: "Uhr", en: "o'clock", es: "en punto", ar: "الساعة", hi: "बजे", cat: "Zeit", icon: "⏰" },
  { char: "分钟", pinyin: "fēn zhōng", de: "Minute", en: "minute", es: "minuto", ar: "دقيقة", hi: "मिनट", cat: "Zeit", icon: "⏱️" },
  { char: "上午", pinyin: "shàng wǔ", de: "Vormittag", en: "morning", es: "mañana", ar: "صباحاً", hi: "सुबह", cat: "Zeit", icon: "🌅" },
  { char: "中午", pinyin: "zhōng wǔ", de: "Mittag", en: "noon", es: "mediodía", ar: "ظهراً", hi: "दोपहर", cat: "Zeit", icon: "☀️" },
  { char: "下午", pinyin: "xià wǔ", de: "Nachmittag", en: "afternoon", es: "tarde", ar: "بعد الظهر", hi: "दोपहर बाद", cat: "Zeit", icon: "🌤️" },
  { char: "前面", pinyin: "qián miàn", de: "vorne", en: "front", es: "delante", ar: "أمام", hi: "सामने", cat: "Richtungen", icon: "⬆️" },
  { char: "后面", pinyin: "hòu miàn", de: "hinten", en: "behind", es: "detrás", ar: "خلف", hi: "पीछे", cat: "Richtungen", icon: "⬇️" },
  { char: "上", pinyin: "shàng", de: "oben", en: "up", es: "arriba", ar: "فوق", hi: "ऊपर", cat: "Richtungen", icon: "⬆️" },
  { char: "下", pinyin: "xià", de: "unten", en: "down", es: "abajo", ar: "تحت", hi: "नीचे", cat: "Richtungen", icon: "⬇️" },
  { char: "里", pinyin: "lǐ", de: "innen", en: "inside", es: "dentro", ar: "داخل", hi: "अंदर", cat: "Richtungen", icon: "📦" },
  { char: "菜", pinyin: "cài", de: "Gericht", en: "dish", es: "plato", ar: "طبق", hi: "व्यंजन", cat: "Essen", icon: "🍽️" },
  { char: "杯子", pinyin: "bēi zi", de: "Tasse", en: "cup", es: "taza", ar: "كوب", hi: "कप", cat: "Dinge", icon: "☕" },
  { char: "桌子", pinyin: "zhuō zi", de: "Tisch", en: "table", es: "mesa", ar: "طاولة", hi: "मेज़", cat: "Dinge", icon: "🪑" },
  { char: "椅子", pinyin: "yǐ zi", de: "Stuhl", en: "chair", es: "silla", ar: "كرسي", hi: "कुर्सी", cat: "Dinge", icon: "🪑" },
  { char: "衣服", pinyin: "yī fu", de: "Kleidung", en: "clothes", es: "ropa", ar: "ملابس", hi: "कपड़े", cat: "Dinge", icon: "👔" },
  { char: "水果", pinyin: "shuǐ guǒ", de: "Obst", en: "fruit", es: "fruta", ar: "فاكهة", hi: "फल", cat: "Essen", icon: "🍎" },
  { char: "同学", pinyin: "tóng xué", de: "Mitschüler", en: "classmate", es: "compañero", ar: "زميل", hi: "सहपाठी", cat: "Personen", icon: "👨‍🎓" },
  { char: "女儿", pinyin: "nǚ ér", de: "Tochter", en: "daughter", es: "hija", ar: "ابنة", hi: "बेटी", cat: "Personen", icon: "👧" },
  { char: "儿子", pinyin: "ér zi", de: "Sohn", en: "son", es: "hijo", ar: "ابن", hi: "बेटा", cat: "Personen", icon: "👦" },
  { char: "先生", pinyin: "xiān sheng", de: "Herr", en: "Mr.", es: "señor", ar: "سيد", hi: "श्रीमान", cat: "Personen", icon: "🎩" },
  { char: "小姐", pinyin: "xiǎo jiě", de: "Fräulein", en: "Miss", es: "señorita", ar: "آنسة", hi: "सुश्री", cat: "Personen", icon: "👩" },
  { char: "打电话", pinyin: "dǎ diàn huà", de: "telefonieren", en: "call", es: "llamar", ar: "يتصل", hi: "फ़ोन करना", cat: "Verben", icon: "📞" },
  { char: "看见", pinyin: "kàn jiàn", de: "sehen", en: "see", es: "ver", ar: "يرى", hi: "देखना", cat: "Verben", icon: "👁️" },
  { char: "开", pinyin: "kāi", de: "öffnen", en: "open", es: "abrir", ar: "يفتح", hi: "खोलना", cat: "Verben", icon: "🚪" },
  { char: "坐", pinyin: "zuò", de: "sitzen", en: "sit", es: "sentarse", ar: "يجلس", hi: "बैठना", cat: "Verben", icon: "🪑" },
  { char: "回", pinyin: "huí", de: "zurückkehren", en: "return", es: "volver", ar: "يعود", hi: "लौटना", cat: "Verben", icon: "🔙" },
  { char: "下雨", pinyin: "xià yǔ", de: "regnen", en: "rain", es: "llover", ar: "تمطر", hi: "बारिश होना", cat: "Wetter", icon: "🌧️" },
  { char: "认识", pinyin: "rèn shi", de: "kennen", en: "know", es: "conocer", ar: "يعرف", hi: "जानना", cat: "Verben", icon: "🤝" },
  { char: "对不起", pinyin: "duì bu qǐ", de: "Entschuldigung", en: "sorry", es: "lo siento", ar: "آسف", hi: "माफ़ कीजिए", cat: "Verben", icon: "🙇" },

  { char: "字", pinyin: "zì", de: "Zeichen", en: "character", es: "carácter", ar: "حرف", hi: "अक्षर", cat: "Sprache", icon: "📝" },
  { char: "汉语", pinyin: "hàn yǔ", de: "Chinesisch", en: "Chinese", es: "chino", ar: "الصينية", hi: "चीनी भाषा", cat: "Sprache", icon: "🇨🇳" },
  { char: "出租车", pinyin: "chū zū chē", de: "Taxi", en: "taxi", es: "taxi", ar: "تاكسي", hi: "टैक्सी", cat: "Verkehr", icon: "🚕" },
  { char: "怎么样", pinyin: "zěn me yàng", de: "wie ist", en: "how about", es: "qué tal", ar: "كيف الحال", hi: "कैसा है", cat: "Pronomen", icon: "🤔" },
  { char: "喂", pinyin: "wèi", de: "Hallo", en: "hello", es: "hola", ar: "مرحباً", hi: "हैलो", cat: "Verben", icon: "📞" },
  { char: "些", pinyin: "xiē", de: "einige", en: "some", es: "algunos", ar: "بعض", hi: "कुछ", cat: "Grammatik", icon: "📊" },
  { char: "本", pinyin: "běn", de: "Zählwort", en: "measure word", es: "clasificador", ar: "عداد", hi: "गिनती शब्द", cat: "Grammatik", icon: "📚" },
  { char: "个", pinyin: "gè", de: "Zählwort", en: "measure word", es: "clasificador", ar: "عداد", hi: "गिनती शब्द", cat: "Grammatik", icon: "👤" },
  { char: "号", pinyin: "hào", de: "Nummer", en: "number/date", es: "número", ar: "رقم", hi: "नंबर", cat: "Zahlen", icon: "🔢" },
  { char: "了", pinyin: "le", de: "Partikel", en: "particle", es: "partícula", ar: "جسيم", hi: "कण", cat: "Grammatik", icon: "✅" },
  { char: "没关系", pinyin: "méi guān xi", de: "macht nichts", en: "it's okay", es: "no pasa nada", ar: "لا بأس", hi: "कोई बात नहीं", cat: "Ausdrücke", icon: "👌" },
  { char: "时候", pinyin: "shí hou", de: "Zeit", en: "time/moment", es: "momento", ar: "وقت", hi: "समय", cat: "Zeit", icon: "⏰" },
  { char: "一点儿", pinyin: "yī diǎn er", de: "ein bisschen", en: "a little", es: "un poco", ar: "قليلاً", hi: "थोड़ा सा", cat: "Grammatik", icon: "🤏" },
  { char: "电影", pinyin: "diàn yǐng", de: "Film", en: "movie", es: "película", ar: "فيلم", hi: "फ़िल्म", cat: "Kultur", icon: "🎬" },
  { char: "东西", pinyin: "dōng xi", de: "Ding", en: "thing", es: "cosa", ar: "شيء", hi: "चीज़", cat: "Dinge", icon: "📦" }
];
