// HSK 2 Vocabulary (150 words)
export const hsk2Vocab = [
  { char: "帮助", pinyin: "bāngzhù", de: "helfen", en: "help", es: "ayudar", ar: "يساعد", hi: "मदद करना", cat: "Aktionen", icon: "🤝" },
  { char: "报纸", pinyin: "bàozhǐ", de: "Zeitung", en: "newspaper", es: "periódico", ar: "جريدة", hi: "अखबार", cat: "Dinge", icon: "📰" },
  { char: "比", pinyin: "bǐ", de: "vergleichen", en: "than", es: "que", ar: "من", hi: "से", cat: "Grammatik", icon: "⚖️" },
  { char: "别", pinyin: "bié", de: "nicht", en: "don't", es: "no", ar: "لا تفعل", hi: "मत", cat: "Grammatik", icon: "⛔" },
  { char: "长", pinyin: "cháng", de: "lang", en: "long", es: "largo", ar: "طويل", hi: "लंबा", cat: "Adjektive", icon: "📏" },
  { char: "唱歌", pinyin: "chànggē", de: "singen", en: "sing", es: "cantar", ar: "يغني", hi: "गाना", cat: "Hobby", icon: "🎤" },
  { char: "穿", pinyin: "chuān", de: "tragen", en: "wear", es: "vestir", ar: "يرتدي", hi: "पहनना", cat: "Verben", icon: "🧥" },
  { char: "错", pinyin: "cuò", de: "falsch", en: "wrong", es: "falso", ar: "خطأ", hi: "गलत", cat: "Adjektive", icon: "❌" },
  { char: "打篮球", pinyin: "dǎ lánqiú", de: "Basketball", en: "basketball", es: "baloncesto", ar: "كرة السلة", hi: "बास्केटबॉल", cat: "Sport", icon: "🏀" },

  { char: "到", pinyin: "dào", de: "ankommen", en: "arrive", es: "llegar", ar: "يصل", hi: "पहुँचना", cat: "Verben", icon: "🏁" },
  { char: "等", pinyin: "děng", de: "warten", en: "wait", es: "esperar", ar: "ينتظر", hi: "इंतज़ार करना", cat: "Verben", icon: "⏳" },
  { char: "弟弟", pinyin: "dìdi", de: "Bruder", en: "brother", es: "hermano menor", ar: "أخ أصغر", hi: "छोटा भाई", cat: "Personen", icon: "👶" },
  { char: "第一", pinyin: "dì-yī", de: "erster", en: "first", es: "primero", ar: "الأول", hi: "पहला", cat: "Zahlen", icon: "🥇" },
  { char: "懂", pinyin: "dǒng", de: "verstehen", en: "understand", es: "entender", ar: "يفهم", hi: "समझना", cat: "Geist", icon: "💡" },
  { char: "对", pinyin: "duì", de: "richtig", en: "correct", es: "correcto", ar: "صحيح", hi: "सही", cat: "Adjektive", icon: "✅" },
  { char: "房间", pinyin: "fángjiān", de: "Zimmer", en: "room", es: "habitación", ar: "غرفة", hi: "कमरा", cat: "Orte", icon: "🛌" },
  { char: "非常", pinyin: "fēicháng", de: "sehr", en: "very", es: "muy", ar: "جداً", hi: "बहुत", cat: "Adverb", icon: "✨" },
  { char: "高", pinyin: "gāo", de: "hoch", en: "high", es: "alto", ar: "عالي", hi: "ऊँचा", cat: "Adjektive", icon: "🏔️" },
  { char: "告诉", pinyin: "gàosu", de: "sagen", en: "tell", es: "decir", ar: "يخبر", hi: "बताना", cat: "Aktionen", icon: "🗣️" },
  { char: "哥哥", pinyin: "gēge", de: "Bruder", en: "brother", es: "hermano mayor", ar: "أخ أكبر", hi: "बड़ा भाई", cat: "Personen", icon: "👦" },
  { char: "给", pinyin: "gěi", de: "geben", en: "give", es: "dar", ar: "يعطي", hi: "देना", cat: "Verben", icon: "🎁" },
  { char: "公共汽车", pinyin: "gōnggòngqìchē", de: "Bus", en: "bus", es: "autobús", ar: "حافلة", hi: "बस", cat: "Verkehr", icon: "🚌" },
  { char: "公司", pinyin: "gōngsī", de: "Firma", en: "company", es: "compañía", ar: "شركة", hi: "कंपनी", cat: "Orte", icon: "🏢" },
  { char: "贵", pinyin: "guì", de: "teuer", en: "expensive", es: "caro", ar: "غالي", hi: "महँगा", cat: "Adjektive", icon: "💎" },

  { char: "还", pinyin: "hái", de: "noch", en: "still", es: "todavía", ar: "لا يزال", hi: "अभी भी", cat: "Adverb", icon: "🔁" },
  { char: "孩子", pinyin: "háizi", de: "Kind", en: "child", es: "niño", ar: "طفل", hi: "बच्चा", cat: "Personen", icon: "👶" },
  { char: "好吃", pinyin: "hǎochī", de: "lecker", en: "delicious", es: "delicioso", ar: "لذيذ", hi: "स्वादिष्ट", cat: "Adjektive", icon: "😋" },
  { char: "黑", pinyin: "hēi", de: "schwarz", en: "black", es: "negro", ar: "أسود", hi: "काला", cat: "Farben", icon: "⚫" },
  { char: "红", pinyin: "hóng", de: "rot", en: "red", es: "rojo", ar: "أحمر", hi: "लाल", cat: "Farben", icon: "🔴" },
  { char: "白", pinyin: "bái", de: "weiß", en: "white", es: "blanco", ar: "أبيض", hi: "सफ़ेद", cat: "Farben", icon: "⚪" },

  { char: "机场", pinyin: "jīchǎng", de: "Flughafen", en: "airport", es: "aeropuerto", ar: "مطار", hi: "हवाई अड्डा", cat: "Orte", icon: "✈️" },
  { char: "鸡蛋", pinyin: "jīdàn", de: "Ei", en: "egg", es: "huevo", ar: "بيضة", hi: "अंडा", cat: "Essen", icon: "🥚" },
  { char: "教室", pinyin: "jiàoshì", de: "Klassenzimmer", en: "classroom", es: "aula", ar: "قاعة", hi: "कक्षा", cat: "Orte", icon: "🏫" },
  { char: "姐姐", pinyin: "jiějie", de: "Schwester", en: "sister", es: "hermana mayor", ar: "أخت أكبر", hi: "बड़ी बहन", cat: "Personen", icon: "👧" },
  { char: "介绍", pinyin: "jièshào", de: "vorstellen", en: "introduce", es: "presentar", ar: "يقدم", hi: "परिचय देना", cat: "Aktionen", icon: "🗣️" },
  { char: "进", pinyin: "jìn", de: "eintreten", en: "enter", es: "entrar", ar: "يدخل", hi: "अंदर आना", cat: "Verben", icon: "📥" },
  { char: "近", pinyin: "jìn", de: "nah", en: "near", es: "cerca", ar: "قريب", hi: "पास", cat: "Adjektive", icon: "📍" },
  { char: "就", pinyin: "jiù", de: "eben", en: "just", es: "entonces", ar: "فقط", hi: "बस", cat: "Adverb", icon: "⚡" },
  { char: "觉得", pinyin: "juéde", de: "fühlen", en: "feel", es: "sentir", ar: "يشعر", hi: "महसूस करना", cat: "Geist", icon: "💭" },
  { char: "咖啡", pinyin: "kāfēi", de: "Kaffee", en: "coffee", es: "café", ar: "قهوة", hi: "कॉफ़ी", cat: "Essen", icon: "☕" },
  { char: "开始", pinyin: "kāishǐ", de: "starten", en: "start", es: "empezar", ar: "يبدأ", hi: "शुरू करना", cat: "Aktionen", icon: "🚀" },
  { char: "考试", pinyin: "kǎoshì", de: "Prüfung", en: "exam", es: "examen", ar: "امتحان", hi: "परीक्षा", cat: "Schule", icon: "📝" },
  { char: "可能", pinyin: "kěnéng", de: "vielleicht", en: "possible", es: "posible", ar: "ممكن", hi: "शायद", cat: "Adverb", icon: "❓" },
  { char: "可以", pinyin: "kěyǐ", de: "können", en: "can", es: "poder", ar: "يستطيع", hi: "सकना", cat: "Verben", icon: "💪" },
  { char: "课", pinyin: "kè", de: "Unterricht", en: "class", es: "clase", ar: "درس", hi: "कक्षा", cat: "Schule", icon: "📖" },
  { char: "快", pinyin: "kuài", de: "schnell", en: "fast", es: "rápido", ar: "سريع", hi: "तेज़", cat: "Adjektive", icon: "⚡" },
  { char: "快乐", pinyin: "kuàilè", de: "glücklich", en: "happy", es: "feliz", ar: "سعيد", hi: "खुश", cat: "Emotion", icon: "😊" },
  { char: "累", pinyin: "lèi", de: "müde", en: "tired", es: "cansado", ar: "متعب", hi: "थका हुआ", cat: "Gefühle", icon: "😫" },
  { char: "离", pinyin: "lí", de: "fern von", en: "away from", es: "lejos de", ar: "بعيد عن", hi: "दूर", cat: "Richtungen", icon: "🛤️" },
  { char: "两", pinyin: "liǎng", de: "zwei", en: "two", es: "dos", ar: "اثنان", hi: "दो", cat: "Zahlen", icon: "2️⃣" },
  { char: "路", pinyin: "lù", de: "Weg", en: "road", es: "camino", ar: "طريق", hi: "रास्ता", cat: "Orte", icon: "🛣️" },
  { char: "旅游", pinyin: "lǚyóu", de: "reisen", en: "travel", es: "viajar", ar: "يسافر", hi: "यात्रा करना", cat: "Hobby", icon: "🧳" },
  { char: "卖", pinyin: "mài", de: "verkaufen", en: "sell", es: "vender", ar: "يبيع", hi: "बेचना", cat: "Verben", icon: "💵" },
  { char: "慢", pinyin: "màn", de: "langsam", en: "slow", es: "lento", ar: "بطيء", hi: "धीमा", cat: "Adjektive", icon: "🐢" },
  { char: "忙", pinyin: "máng", de: "beschäftigt", en: "busy", es: "ocupado", ar: "مشغول", hi: "व्यस्त", cat: "Adjektive", icon: "🏃‍♂️" },
  { char: "每", pinyin: "měi", de: "jeder", en: "every", es: "cada", ar: "كل", hi: "हर", cat: "Adverb", icon: "🔄" },
  { char: "妹妹", pinyin: "mèimei", de: "Schwester", en: "sister", es: "hermana menor", ar: "أخت أصغر", hi: "छोटी बहन", cat: "Personen", icon: "🧒" },
  { char: "门", pinyin: "mén", de: "Tür", en: "door", es: "puerta", ar: "باب", hi: "दरवाज़ा", cat: "Dinge", icon: "🚪" },
  { char: "面条", pinyin: "miàntiáo", de: "Nudeln", en: "noodles", es: "fideos", ar: "نودلز", hi: "नूडल्स", cat: "Essen", icon: "🍜" },
  { char: "牛奶", pinyin: "niúnǎi", de: "Milch", en: "milk", es: "leche", ar: "حليب", hi: "दूध", cat: "Essen", icon: "🥛" },
  { char: "旁边", pinyin: "pángbiān", de: "neben", en: "beside", es: "al lado", ar: "بجانب", hi: "बगल में", cat: "Richtungen", icon: "📍" },
  { char: "跑步", pinyin: "pǎobù", de: "laufen", en: "running", es: "correr", ar: "يركض", hi: "दौड़ना", cat: "Sport", icon: "🏃" },
  { char: "便宜", pinyin: "piányi", de: "billig", en: "cheap", es: "barato", ar: "رخيص", hi: "सस्ता", cat: "Adjektive", icon: "🏷️" },
  { char: "票", pinyin: "piào", de: "Ticket", en: "ticket", es: "billete", ar: "تذكرة", hi: "टिकट", cat: "Dinge", icon: "🎟️" },
  { char: "起床", pinyin: "qǐchuáng", de: "aufstehen", en: "get up", es: "levantarse", ar: "يستيقظ", hi: "उठना", cat: "Aktionen", icon: "🌅" },
  { char: "千", pinyin: "qiān", de: "tausend", en: "thousand", es: "mil", ar: "ألف", hi: "हज़ार", cat: "Zahlen", icon: "🔢" },
  { char: "晴", pinyin: "qíng", de: "sonnig", en: "sunny", es: "soleado", ar: "مشمس", hi: "धूप", cat: "Wetter", icon: "☀️" },
  { char: "让", pinyin: "ràng", de: "lassen", en: "let", es: "dejar", ar: "يسمح", hi: "देना", cat: "Verben", icon: "👤" },
  { char: "上班", pinyin: "shàngbān", de: "arbeiten", en: "work", es: "ir al trabajo", ar: "يعمل", hi: "काम पर जाना", cat: "Aktionen", icon: "💼" },
  { char: "身体", pinyin: "shēntǐ", de: "Körper", en: "body", es: "cuerpo", ar: "جسم", hi: "शरीर", cat: "Mensch", icon: "💪" },
  { char: "生病", pinyin: "shēngbìng", de: "krank", en: "sick", es: "enfermo", ar: "مريض", hi: "बीमार", cat: "Gesundheit", icon: "🤒" },
  { char: "生日", pinyin: "shēngrì", de: "Geburtstag", en: "birthday", es: "cumpleaños", ar: "عيد ميلاد", hi: "जन्मदिन", cat: "Zeit", icon: "🎂" },
  { char: "时间", pinyin: "shíjiān", de: "Zeit", en: "time", es: "tiempo", ar: "وقت", hi: "समय", cat: "Zeit", icon: "⏰" },
  { char: "手表", pinyin: "shǒubiǎo", de: "Uhr", en: "watch", es: "reloj", ar: "ساعة يد", hi: "घड़ी", cat: "Dinge", icon: "⌚" },
  { char: "手机", pinyin: "shǒujī", de: "Handy", en: "phone", es: "móvil", ar: "هاتف", hi: "मोबाइल", cat: "Dinge", icon: "📱" },
  { char: "踢足球", pinyin: "tī zúqiú", de: "Fußball", en: "football", es: "fútbol", ar: "كرة القدم", hi: "फुटबॉल", cat: "Sport", icon: "⚽" },
  { char: "跳舞", pinyin: "tiàowǔ", de: "tanzen", en: "dance", es: "bailar", ar: "يرقص", hi: "नाचना", cat: "Hobby", icon: "💃" },
  { char: "玩", pinyin: "wán", de: "spielen", en: "play", es: "jugar", ar: "يلعب", hi: "खेलना", cat: "Hobby", icon: "🎮" },
  { char: "晚上", pinyin: "wǎnshang", de: "Abend", en: "evening", es: "noche", ar: "مساء", hi: "शाम", cat: "Zeit", icon: "🌙" },
  { char: "为什么", pinyin: "wèishénme", de: "warum", en: "why", es: "por qué", ar: "لماذا", hi: "क्यों", cat: "Pronomen", icon: "❔" },
  { char: "问", pinyin: "wèn", de: "fragen", en: "ask", es: "preguntar", ar: "يسأل", hi: "पूछना", cat: "Verben", icon: "❓" },
  { char: "问题", pinyin: "wèntí", de: "Problem", en: "problem", es: "problema", ar: "مشكلة", hi: "समस्या", cat: "Geist", icon: "💡" },
  { char: "希望", pinyin: "xīwàng", de: "hoffen", en: "hope", es: "esperar", ar: "يأمل", hi: "आशा करना", cat: "Geist", icon: "🌟" },
  { char: "洗", pinyin: "xǐ", de: "waschen", en: "wash", es: "lavar", ar: "يغسل", hi: "धोना", cat: "Verben", icon: "🧼" },
  { char: "笑", pinyin: "xiào", de: "lachen", en: "laugh", es: "reír", ar: "يضحك", hi: "हँसना", cat: "Emotion", icon: "😄" },
  { char: "休息", pinyin: "xiūxi", de: "ausruhen", en: "rest", es: "descansar", ar: "يستريح", hi: "आराम करना", cat: "Verben", icon: "🛌" },
  { char: "雪", pinyin: "xuě", de: "Schnee", en: "snow", es: "nieve", ar: "ثلج", hi: "बर्फ़", cat: "Wetter", icon: "❄️" },
  { char: "颜色", pinyin: "yánsè", de: "Farbe", en: "color", es: "color", ar: "لون", hi: "रंग", cat: "Dinge", icon: "🎨" },
  { char: "眼睛", pinyin: "yǎnjing", de: "Auge", en: "eye", es: "ojo", ar: "عين", hi: "आँख", cat: "Mensch", icon: "👁️" },
  { char: "药", pinyin: "yào", de: "Medizin", en: "medicine", es: "medicina", ar: "دواء", hi: "दवा", cat: "Gesundheit", icon: "💊" },
  { char: "要", pinyin: "yào", de: "wollen", en: "want", es: "querer", ar: "يريد", hi: "चाहना", cat: "Verben", icon: "🎯" },
  { char: "也", pinyin: "yě", de: "auch", en: "also", es: "también", ar: "أيضاً", hi: "भी", cat: "Adverb", icon: "➕" },
  { char: "一起", pinyin: "yīqǐ", de: "zusammen", en: "together", es: "junto", ar: "معاً", hi: "साथ में", cat: "Verben", icon: "👫" },
  { char: "已经", pinyin: "yǐjīng", de: "bereits", en: "already", es: "ya", ar: "بالفعل", hi: "पहले से", cat: "Adverb", icon: "⏳" },
  { char: "意思", pinyin: "yìsi", de: "Bedeutung", en: "meaning", es: "significado", ar: "معنى", hi: "मतलब", cat: "Geist", icon: "📖" },
  { char: "因为", pinyin: "yīnwèi", de: "weil", en: "because", es: "porque", ar: "لأن", hi: "क्योंकि", cat: "Grammatik", icon: "ℹ️" },
  { char: "游泳", pinyin: "yóuyǒng", de: "schwimmen", en: "swimming", es: "nadar", ar: "يسبح", hi: "तैरना", cat: "Sport", icon: "🏊" },
  { char: "右边", pinyin: "yòubian", de: "rechts", en: "right side", es: "derecha", ar: "يمين", hi: "दाईं ओर", cat: "Richtungen", icon: "👉" },
  { char: "鱼", pinyin: "yú", de: "Fisch", en: "fish", es: "pescado", ar: "سمك", hi: "मछली", cat: "Essen", icon: "🐟" },
  { char: "远", pinyin: "yuǎn", de: "weit", en: "far", es: "lejos", ar: "بعيد", hi: "दूर", cat: "Adjektive", icon: "🔭" },
  { char: "运动", pinyin: "yùndòng", de: "Sport", en: "sport", es: "deporte", ar: "رياضة", hi: "खेल", cat: "Sport", icon: "🏃" },
  { char: "再", pinyin: "zài", de: "wieder", en: "again", es: "otra vez", ar: "مرة أخرى", hi: "फिर", cat: "Adverb", icon: "🔁" },
  { char: "早上", pinyin: "zǎoshang", de: "Morgen", en: "morning", es: "mañana", ar: "صباح", hi: "सुबह", cat: "Zeit", icon: "🌅" },
  { char: "丈夫", pinyin: "zhàngfu", de: "Ehemann", en: "husband", es: "esposo", ar: "زوج", hi: "पति", cat: "Personen", icon: "🤵" },
  { char: "找", pinyin: "zhǎo", de: "suchen", en: "find", es: "buscar", ar: "يجد", hi: "ढूँढना", cat: "Verben", icon: "🔍" },
  { char: "真", pinyin: "zhēn", de: "wirklich", en: "really", es: "verdadero", ar: "حقاً", hi: "सच में", cat: "Adverb", icon: "💎" },
  { char: "正在", pinyin: "zhèngzài", de: "gerade", en: "currently", es: "ahora mismo", ar: "الآن", hi: "अभी", cat: "Adverb", icon: "🕐" },
  { char: "知道", pinyin: "zhīdao", de: "wissen", en: "know", es: "saber", ar: "يعرف", hi: "जानना", cat: "Geist", icon: "🧠" },
  { char: "准备", pinyin: "zhǔnbèi", de: "vorbereiten", en: "prepare", es: "preparar", ar: "يستعد", hi: "तैयारी करना", cat: "Aktionen", icon: "📝" },
  { char: "自行车", pinyin: "zìxíngchē", de: "Fahrrad", en: "bicycle", es: "bicicleta", ar: "دراجة", hi: "साइकिल", cat: "Verkehr", icon: "🚲" },
  { char: "走", pinyin: "zǒu", de: "gehen", en: "walk", es: "caminar", ar: "يمشي", hi: "चलना", cat: "Verben", icon: "🚶" },
  { char: "最", pinyin: "zuì", de: "meiste", en: "most", es: "más", ar: "الأكثر", hi: "सबसे", cat: "Adverb", icon: "🔝" },
  { char: "左边", pinyin: "zuǒbian", de: "links", en: "left side", es: "izquierda", ar: "يسار", hi: "बाईं ओर", cat: "Richtungen", icon: "👈" },
  { char: "女", pinyin: "nǚ", de: "weiblich", en: "female", es: "femenino", ar: "أنثى", hi: "महिला", cat: "Personen", icon: "♀️" },
  { char: "男", pinyin: "nán", de: "männlich", en: "male", es: "masculino", ar: "ذكر", hi: "पुरुष", cat: "Personen", icon: "♂️" },
  { char: "从", pinyin: "cóng", de: "von", en: "from", es: "desde", ar: "من", hi: "से", cat: "Grammatik", icon: "➡️" },

  { char: "外", pinyin: "wài", de: "außen", en: "outside", es: "fuera", ar: "خارج", hi: "बाहर", cat: "Richtungen", icon: "🚪" },
  { char: "完", pinyin: "wán", de: "beenden", en: "finish", es: "terminar", ar: "ينهي", hi: "समाप्त करना", cat: "Verben", icon: "✅" },

  { char: "送", pinyin: "sòng", de: "schenken", en: "send", es: "enviar", ar: "يرسل", hi: "भेजना", cat: "Verben", icon: "🎁" },


  { char: "所以", pinyin: "suǒyǐ", de: "deshalb", en: "so", es: "por eso", ar: "لذلك", hi: "इसलिए", cat: "Grammatik", icon: "➡️" },


  { char: "吧", pinyin: "ba", de: "Partikel", en: "particle", es: "partícula", ar: "جسيم", hi: "कण", cat: "Grammatik", icon: "💬" },
  { char: "过", pinyin: "guò", de: "Erfahrungs-P.", en: "experience", es: "experiencia", ar: "خبرة", hi: "अनुभव", cat: "Grammatik", icon: "✔️" },
  { char: "得", pinyin: "de", de: "erhalten", en: "get", es: "obtener", ar: "يحصل", hi: "पाना", cat: "Grammatik", icon: "🎁" },
  { char: "着", pinyin: "zhe", de: "Dauer-P.", en: "continuous", es: "continuo", ar: "مستمر", hi: "रहा", cat: "Grammatik", icon: "⏳" },
  { char: "事情", pinyin: "shìqing", de: "Sache", en: "thing", es: "cosa", ar: "شيء", hi: "बात", cat: "Dinge", icon: "📋" },
  { char: "妻子", pinyin: "qīzi", de: "Ehefrau", en: "wife", es: "esposa", ar: "زوجة", hi: "पत्नी", cat: "Personen", icon: "👩" },
  { char: "服务员", pinyin: "fúwùyuán", de: "Kellner", en: "waiter", es: "camarero", ar: "نادل", hi: "वेटर", cat: "Personen", icon: "🍽️" },
  { char: "宾馆", pinyin: "bīnguǎn", de: "Hotel", en: "hotel", es: "hotel", ar: "فندق", hi: "होटल", cat: "Orte", icon: "🏨" },
  { char: "张", pinyin: "zhāng", de: "Blatt", en: "sheet", es: "hoja", ar: "ورقة", hi: "पत्ता", cat: "Maße", icon: "📄" },
  { char: "件", pinyin: "jiàn", de: "Stück", en: "piece", es: "pieza", ar: "قطعة", hi: "टुकड़ा", cat: "Maße", icon: "👔" },

  { char: "新", pinyin: "xīn", de: "neu", en: "new", es: "nuevo", ar: "جديد", hi: "नया", cat: "Adjektive", icon: "✨" },
  { char: "出", pinyin: "chū", de: "ausgehen", en: "go out", es: "salir", ar: "يخرج", hi: "बाहर जाना", cat: "Verben", icon: "🚪" },
  { char: "大家", pinyin: "dàjiā", de: "alle", en: "everyone", es: "todos", ar: "الجميع", hi: "सब लोग", cat: "Pronomen", icon: "👥" },
  { char: "火车站", pinyin: "huǒchēzhàn", de: "Bahnhof", en: "train station", es: "estación", ar: "محطة قطار", hi: "रेलवे स्टेशन", cat: "Orte", icon: "🚉" },
  { char: "您", pinyin: "nín", de: "Sie", en: "you (polite)", es: "usted", ar: "حضرتك", hi: "आप", cat: "Pronomen", icon: "🙏" },
  { char: "铅笔", pinyin: "qiānbǐ", de: "Bleistift", en: "pencil", es: "lápiz", ar: "قلم رصاص", hi: "पेंसिल", cat: "Dinge", icon: "✏️" },
  { char: "去年", pinyin: "qùnián", de: "letztes Jahr", en: "last year", es: "año pasado", ar: "السنة الماضية", hi: "पिछले साल", cat: "Zeit", icon: "📅" },
  { char: "说话", pinyin: "shuōhuà", de: "sprechen", en: "speak", es: "hablar", ar: "يتكلم", hi: "बोलना", cat: "Verben", icon: "🗣️" },
  { char: "它", pinyin: "tā", de: "es", en: "it", es: "ello", ar: "هو/هي", hi: "यह", cat: "Pronomen", icon: "👉" },
  { char: "题", pinyin: "tí", de: "Frage", en: "question", es: "pregunta", ar: "سؤال", hi: "सवाल", cat: "Schule", icon: "❓" },
  { char: "往", pinyin: "wǎng", de: "Richtung", en: "towards", es: "hacia", ar: "نحو", hi: "की ओर", cat: "Richtungen", icon: "➡️" },
  { char: "西瓜", pinyin: "xīguā", de: "Wassermelone", en: "watermelon", es: "sandía", ar: "بطيخ", hi: "तरबूज़", cat: "Essen", icon: "🍉" },
  { char: "小时", pinyin: "xiǎoshí", de: "Stunde", en: "hour", es: "hora", ar: "ساعة", hi: "घंटा", cat: "Zeit", icon: "⏰" },
  { char: "姓", pinyin: "xìng", de: "Nachname", en: "surname", es: "apellido", ar: "اسم العائلة", hi: "उपनाम", cat: "Personen", icon: "📛" },
  { char: "羊肉", pinyin: "yángròu", de: "Lammfleisch", en: "lamb", es: "cordero", ar: "لحم خروف", hi: "भेड़ का मांस", cat: "Essen", icon: "🐑" },
  { char: "阴", pinyin: "yīn", de: "bewölkt", en: "cloudy", es: "nublado", ar: "غائم", hi: "बादल", cat: "Wetter", icon: "☁️" },
  { char: "一下", pinyin: "yīxià", de: "kurz", en: "a moment", es: "un momento", ar: "لحظة", hi: "एक पल", cat: "Zeit", icon: "⏱️" },
  { char: "零", pinyin: "líng", de: "null", en: "zero", es: "cero", ar: "صفر", hi: "शून्य", cat: "Zahlen", icon: "0️⃣" },
  { char: "百", pinyin: "bǎi", de: "hundert", en: "hundred", es: "cien", ar: "مئة", hi: "सौ", cat: "Zahlen", icon: "💯" },
  { char: "日", pinyin: "rì", de: "Tag", en: "day", es: "día", ar: "يوم", hi: "दिन", cat: "Zeit", icon: "📆" }
];
