// HSK 3 Vocabulary (300 words)
export const hsk3Vocab = [
  { char: "阿姨", pinyin: "āyí", de: "Tante", en: "aunt", es: "tía", ar: "عمة", hi: "चाची", cat: "Personen", icon: "👩" },
  { char: "安静", pinyin: "ānjìng", de: "ruhig", en: "quiet", es: "tranquilo", ar: "هادئ", hi: "शांत", cat: "Adjektive", icon: "🤫" },
  { char: "把", pinyin: "bǎ", de: "fassen", en: "grasp", es: "agarrar", ar: "يمسك", hi: "पकड़ना", cat: "Grammatik", icon: "✊" },
  { char: "搬", pinyin: "bān", de: "umziehen", en: "move", es: "mudarse", ar: "ينتقل", hi: "स्थानांतरित करना", cat: "Aktionen", icon: "📦" },
  { char: "办法", pinyin: "bànfǎ", de: "Methode", en: "method", es: "método", ar: "طريقة", hi: "तरीका", cat: "Geist", icon: "💡" },
  { char: "办公室", pinyin: "bàngōngshì", de: "Büro", en: "office", es: "oficina", ar: "مكتب", hi: "कार्यालय", cat: "Orte", icon: "🏢" },
  { char: "包", pinyin: "bāo", de: "Tasche", en: "bag", es: "bolsa", ar: "حقيبة", hi: "बैग", cat: "Dinge", icon: "👜" },
  { char: "比较", pinyin: "bǐjiào", de: "vergleichen", en: "compare", es: "comparar", ar: "يقارن", hi: "तुलना करना", cat: "Adverb", icon: "⚖️" },
  { char: "比赛", pinyin: "bǐsài", de: "Wettbewerb", en: "match", es: "partido", ar: "مباراة", hi: "प्रतियोगिता", cat: "Sport", icon: "⚽" },
  { char: "必须", pinyin: "bìxū", de: "müssen", en: "must", es: "deber", ar: "يجب", hi: "ज़रूरी", cat: "Adverb", icon: "⚠️" },
  { char: "变化", pinyin: "biànhuà", de: "Änderung", en: "change", es: "cambio", ar: "تغيير", hi: "बदलाव", cat: "Geist", icon: "🔄" },
  { char: "宾馆", pinyin: "bīnguǎn", de: "Hotel", en: "hotel", es: "hotel", ar: "فندق", hi: "होटल", cat: "Orte", icon: "🏨" },
  { char: "冰箱", pinyin: "bīngxiāng", de: "Kühlschrank", en: "fridge", es: "nevera", ar: "ثلاجة", hi: "फ्रिज", cat: "Dinge", icon: "🧊" },
  { char: "菜单", pinyin: "càidān", de: "Menü", en: "menu", es: "menú", ar: "قائمة طعام", hi: "मेन्यू", cat: "Dinge", icon: "📜" },
  { char: "参加", pinyin: "cānjiā", de: "teilnehmen", en: "participate", es: "participar", ar: "يشارك", hi: "भाग लेना", cat: "Aktionen", icon: "🙋" },
  { char: "超市", pinyin: "chāoshì", de: "Supermarkt", en: "supermarket", es: "supermercado", ar: "سوبرماركت", hi: "सुपरमार्केट", cat: "Orte", icon: "🛒" },
  { char: "成绩", pinyin: "chéngjì", de: "Note", en: "score", es: "nota", ar: "درجة", hi: "अंक", cat: "Schule", icon: "💯" },
  { char: "城市", pinyin: "chéngshì", de: "Stadt", en: "city", es: "ciudad", ar: "مدينة", hi: "शहर", cat: "Orte", icon: "🏙️" },
  { char: "迟到", pinyin: "chídào", de: "zu spät", en: "late", es: "tarde", ar: "متأخر", hi: "देर से आना", cat: "Aktionen", icon: "⏰" },
  { char: "厨房", pinyin: "chúfáng", de: "Küche", en: "kitchen", es: "cocina", ar: "مطبخ", hi: "रसोई", cat: "Orte", icon: "🍳" },
  { char: "春", pinyin: "chūn", de: "Frühling", en: "spring", es: "primavera", ar: "ربيع", hi: "वसंत", cat: "Zeit", icon: "🌱" },
  { char: "聪明", pinyin: "cōngmíng", de: "klug", en: "smart", es: "listo", ar: "ذكي", hi: "होशियार", cat: "Adjektive", icon: "🧠" },
  { char: "打扫", pinyin: "dǎsǎo", de: "putzen", en: "clean", es: "limpiar", ar: "ينظف", hi: "सफाई करना", cat: "Aktionen", icon: "🧹" },
  { char: "打算", pinyin: "dǎsuàn", de: "planen", en: "plan", es: "planear", ar: "يخطط", hi: "योजना बनाना", cat: "Geist", icon: "📅" },
  { char: "担心", pinyin: "dānxīn", de: "sorgen", en: "worry", es: "preocuparse", ar: "يقلق", hi: "चिंतित होना", cat: "Emotion", icon: "😟" },
  { char: "蛋糕", pinyin: "dàngāo", de: "Kuchen", en: "cake", es: "pastel", ar: "كعكة", hi: "केक", cat: "Essen", icon: "🍰" },
  { char: "当然", pinyin: "dāngrán", de: "natürlich", en: "of course", es: "claro", ar: "بالطبع", hi: "बेशक", cat: "Adverb", icon: "👌" },
  { char: "地方", pinyin: "dìfang", de: "Ort", en: "place", es: "lugar", ar: "مكان", hi: "जगह", cat: "Orte", icon: "📍" },
  { char: "地铁", pinyin: "dìtiě", de: "U-Bahn", en: "subway", es: "metro", ar: "مترو", hi: "मेट्रो", cat: "Verkehr", icon: "🚇" },
  { char: "电梯", pinyin: "diàntī", de: "Aufzug", en: "elevator", es: "ascensor", ar: "مصعد", hi: "लिफ्ट", cat: "Verkehr", icon: "🛗" },
  { char: "电子邮件", pinyin: "diànzǐ yóujiàn", de: "E-Mail", en: "email", es: "correo", ar: "بريد إلكتروني", hi: "ईमेल", cat: "Dinge", icon: "📧" },
  { char: "冬", pinyin: "dōng", de: "Winter", en: "winter", es: "invierno", ar: "شتاء", hi: "सर्दी", cat: "Zeit", icon: "❄️" },
  { char: "动物", pinyin: "dòngwù", de: "Tier", en: "animal", es: "animal", ar: "حيوان", hi: "जानवर", cat: "Natur", icon: "🐾" },
  { char: "锻炼", pinyin: "duànliàn", de: "trainieren", en: "exercise", es: "ejercicio", ar: "يتمرن", hi: "व्यायाम करना", cat: "Sport", icon: "🏋️" },
  { char: "发现", pinyin: "fāxiàn", de: "entdecken", en: "discover", es: "descubrir", ar: "يكتشف", hi: "पता लगाना", cat: "Verben", icon: "🔍" },
  { char: "方便", pinyin: "fāngbiàn", de: "praktisch", en: "convenient", es: "confortable", ar: "مريح", hi: "सुविधाजनक", cat: "Adjektive", icon: "🛵" },
  { char: "干净", pinyin: "gānjìng", de: "sauber", en: "clean", es: "limpio", ar: "نظيف", hi: "साफ", cat: "Adjektive", icon: "✨" },
  { char: "感冒", pinyin: "gǎnmào", de: "Erkältung", en: "cold", es: "resfriado", ar: "زكام", hi: "सर्दी-जुकाम", cat: "Gesundheit", icon: "🤧" },
  { char: "公园", pinyin: "gōngyuán", de: "Park", en: "park", es: "parque", ar: "حديقة", hi: "पार्क", cat: "Orte", icon: "🌳" },
  { char: "故事", pinyin: "gùshi", de: "Märchen", en: "story", es: "historia", ar: "قصة", hi: "कहानी", cat: "Dinge", icon: "📚" },
  { char: "国家", pinyin: "guójiā", de: "Staat", en: "country", es: "país", ar: "دولة", hi: "देश", cat: "Orte", icon: "🗺️" },
  { char: "害怕", pinyin: "hàipà", de: "Angst", en: "afraid", es: "miedo", ar: "خائف", hi: "डरना", cat: "Emotion", icon: "😨" },
  { char: "护照", pinyin: "hùzhào", de: "Pass", en: "passport", es: "pasaporte", ar: "جواز سفر", hi: "पासपोर्ट", cat: "Dinge", icon: "🛂" },
  { char: "花", pinyin: "huā", de: "Blume", en: "flower", es: "flor", ar: "زهرة", hi: "फूल", cat: "Natur", icon: "🌸" },
  { char: "环境", pinyin: "huánjìng", de: "Umwelt", en: "environment", es: "ambiente", ar: "بيئة", hi: "पर्यावरण", cat: "Natur", icon: "🌍" },
  { char: "会议", pinyin: "huìyì", de: "Konferenz", en: "meeting", es: "reunión", ar: "اجتماع", hi: "बैठक", cat: "Orte", icon: "🤝" },
  { char: "机会", pinyin: "jīhuì", de: "Chance", en: "chance", es: "oportunidad", ar: "فرصة", hi: "मौका", cat: "Geist", icon: "🚪" },
  { char: "记得", pinyin: "jìde", de: "erinnern", en: "remember", es: "recordar", ar: "يتذكر", hi: "याद रखना", cat: "Geist", icon: "🧠" },
  { char: "季节", pinyin: "jìjié", de: "Saison", en: "season", es: "estación", ar: "موسم", hi: "मौसम", cat: "Zeit", icon: "🍂" },
  { char: "检查", pinyin: "jiǎnchá", de: "prüfen", en: "check", es: "revisar", ar: "يفحص", hi: "जाँच करना", cat: "Verben", icon: "✅" },
  { char: "简单", pinyin: "jiǎndān", de: "einfach", en: "simple", es: "simple", ar: "بسيط", hi: "आसान", cat: "Adjektive", icon: "👌" },
  { char: "健康", pinyin: "jiànkāng", de: "Gesundheit", en: "healthy", es: "saludable", ar: "صحي", hi: "स्वस्थ", cat: "Gesundheit", icon: "🥗" },
  { char: "教", pinyin: "jiāo", de: "lehren", en: "teach", es: "enseñar", ar: "يعلم", hi: "पढ़ाना", cat: "Schule", icon: "👨‍🏫" },
  { char: "节目", pinyin: "jiémù", de: "Sendung", en: "program", es: "programa", ar: "برنامج", hi: "कार्यक्रम", cat: "Dinge", icon: "📺" },
  { char: "节日", pinyin: "jiérì", de: "Fest", en: "holiday", es: "festivo", ar: "عيد", hi: "त्योहार", cat: "Zeit", icon: "��" },
  { char: "结婚", pinyin: "jiéhūn", de: "Ehe", en: "marry", es: "casarse", ar: "يتزوج", hi: "शादी करना", cat: "Aktionen", icon: "💍" },
  { char: "解决", pinyin: "jiějué", de: "lösen", en: "solve", es: "resolver", ar: "يحل", hi: "हल करना", cat: "Verben", icon: "🔓" },
  { char: "借", pinyin: "jiè", de: "leihen", en: "borrow", es: "prestar", ar: "يستعير", hi: "उधार लेना", cat: "Verben", icon: "📖" },
  { char: "经常", pinyin: "jīngcháng", de: "oft", en: "often", es: "a menudo", ar: "غالباً", hi: "अक्सर", cat: "Adverb", icon: "🔁" },
  { char: "经理", pinyin: "jīnglǐ", de: "Chef", en: "manager", es: "gerente", ar: "مدير", hi: "प्रबंधक", cat: "Personen", icon: "👔" },
  { char: "决定", pinyin: "juédìng", de: "Beschluss", en: "decide", es: "decidir", ar: "يقرر", hi: "निर्णय लेना", cat: "Geist", icon: "🤔" },
  { char: "可爱", pinyin: "kě'ài", de: "süß", en: "cute", es: "lindo", ar: "لطيف", hi: "प्यारा", cat: "Adjektive", icon: "😻" },
  { char: "空调", pinyin: "kōngtiáo", de: "Klima", en: "AC", es: "aire", ar: "مكيف", hi: "एसी", cat: "Dinge", icon: "❄️" },
  { char: "哭", pinyin: "kū", de: "weinen", en: "cry", es: "llorar", ar: "يبكي", hi: "रोना", cat: "Emotion", icon: "😢" },
  { char: "筷子", pinyin: "kuàizi", de: "Stäbchen", en: "chopsticks", es: "palillos", ar: "عيدان الأكل", hi: "चॉपस्टिक्स", cat: "Dinge", icon: "🥢" },
  { char: "蓝", pinyin: "lán", de: "blau", en: "blue", es: "azul", ar: "أزرق", hi: "नीला", cat: "Farben", icon: "🔵" },
  { char: "礼物", pinyin: "lǐwù", de: "Geschenk", en: "gift", es: "regalo", ar: "هدية", hi: "उपहार", cat: "Dinge", icon: "🎁" },
  { char: "历史", pinyin: "lìshǐ", de: "Historie", en: "history", es: "historia", ar: "تاريخ", hi: "इतिहास", cat: "Schule", icon: "📜" },
  { char: "练习", pinyin: "liànxí", de: "Übung", en: "practice", es: "practicar", ar: "يتدرب", hi: "अभ्यास करना", cat: "Schule", icon: "🏋️" },
  { char: "绿", pinyin: "lǜ", de: "grün", en: "green", es: "verde", ar: "أخضر", hi: "हरा", cat: "Farben", icon: "🟢" },
  { char: "马", pinyin: "mǎ", de: "Pferd", en: "horse", es: "caballo", ar: "حصان", hi: "घोड़ा", cat: "Natur", icon: "🐎" },
  { char: "满意", pinyin: "mǎnyì", de: "zufrieden", en: "satisfied", es: "satisfecho", ar: "راضٍ", hi: "संतुष्ट", cat: "Emotion", icon: "😊" },
  { char: "面包", pinyin: "miànbāo", de: "Brot", en: "bread", es: "pan", ar: "خبز", hi: "रोटी", cat: "Essen", icon: "🍞" },
  { char: "明白", pinyin: "míngbai", de: "klar", en: "understand", es: "entender", ar: "يفهم", hi: "समझना", cat: "Geist", icon: "🧠" },
  { char: "奶奶", pinyin: "nǎinai", de: "Oma", en: "grandma", es: "abuela", ar: "جدة", hi: "दादी", cat: "Personen", icon: "👵" },
  { char: "难", pinyin: "nán", de: "schwer", en: "difficult", es: "difícil", ar: "صعب", hi: "मुश्किल", cat: "Adjektive", icon: "🧩" },
  { char: "难过", pinyin: "nánguò", de: "traurig", en: "sad", es: "triste", ar: "حزين", hi: "दुखी", cat: "Emotion", icon: "😔" },
  { char: "年轻", pinyin: "niánqīng", de: "jung", en: "young", es: "joven", ar: "شاب", hi: "जवान", cat: "Adjektive", icon: "👶" },
  { char: "鸟", pinyin: "niǎo", de: "Vogel", en: "bird", es: "pájaro", ar: "طائر", hi: "चिड़िया", cat: "Natur", icon: "🐦" },
  { char: "努力", pinyin: "nǔlì", de: "fleißig", en: "hardworking", es: "esforzado", ar: "مجتهد", hi: "मेहनती", cat: "Adjektive", icon: "💪" },
  { char: "爬山", pinyin: "páshān", de: "Bergsteigen", en: "climb", es: "escalar", ar: "يتسلق الجبل", hi: "पहाड़ चढ़ना", cat: "Sport", icon: "🏔️" },
  { char: "盘子", pinyin: "pánzi", de: "Teller", en: "plate", es: "plato", ar: "طبق", hi: "प्लेट", cat: "Dinge", icon: "🍽️" },
  { char: "皮鞋", pinyin: "píxié", de: "Lederschuh", en: "leather shoes", es: "zapatos de cuero", ar: "حذاء جلدي", hi: "चमड़े के जूते", cat: "Dinge", icon: "👞" },
  { char: "普通", pinyin: "pǔtōng", de: "gewöhnlich", en: "common", es: "común", ar: "عادي", hi: "सामान्य", cat: "Adjektive", icon: "📦" },
  { char: "其他", pinyin: "qítā", de: "andere", en: "other", es: "otro", ar: "آخر", hi: "अन्य", cat: "Pronomen", icon: "👥" },
  { char: "其实", pinyin: "qíshí", de: "eigentlich", en: "actually", es: "en realidad", ar: "في الحقيقة", hi: "वास्तव में", cat: "Adverb", icon: "💡" },
  { char: "骑", pinyin: "qí", de: "reiten", en: "ride", es: "montar", ar: "يركب", hi: "सवारी करना", cat: "Verben", icon: "🚴" },
  { char: "奇怪", pinyin: "qíguài", de: "seltsam", en: "strange", es: "extraño", ar: "غريب", hi: "अजीब", cat: "Adjektive", icon: "🤔" },
  { char: "铅笔", pinyin: "qiānbǐ", de: "Bleistift", en: "pencil", es: "lápiz", ar: "قلم رصاص", hi: "पेंसिल", cat: "Dinge", icon: "✏️" },
  { char: "清楚", pinyin: "qīngchu", de: "klar", en: "clear", es: "claro", ar: "واضح", hi: "स्पष्ट", cat: "Adjektive", icon: "👁️" },
  { char: "秋", pinyin: "qiū", de: "Herbst", en: "autumn", es: "otoño", ar: "خريف", hi: "पतझड़", cat: "Zeit", icon: "🍂" },
  { char: "裙子", pinyin: "qúnzi", de: "Rock", en: "skirt", es: "falda", ar: "تنورة", hi: "स्कर्ट", cat: "Dinge", icon: "👗" },
  { char: "然后", pinyin: "ránhòu", de: "danach", en: "then", es: "luego", ar: "ثم", hi: "फिर", cat: "Adverb", icon: "➡️" },
  { char: "热情", pinyin: "rèqíng", de: "enthusiastisch", en: "warm", es: "entusiasta", ar: "حماسي", hi: "उत्साही", cat: "Adjektive", icon: "🔥" },
  { char: "认为", pinyin: "rènwéi", de: "denken", en: "think", es: "pensar", ar: "يعتقد", hi: "सोचना", cat: "Geist", icon: "💭" },
  { char: "容易", pinyin: "róngyì", de: "einfach", en: "easy", es: "fácil", ar: "سهل", hi: "आसान", cat: "Adjektive", icon: "👌" },
  { char: "如果", pinyin: "rúguǒ", de: "falls", en: "if", es: "si", ar: "إذا", hi: "अगर", cat: "Grammatik", icon: "❓" },
  { char: "伞", pinyin: "sǎn", de: "Regenschirm", en: "umbrella", es: "paraguas", ar: "مظلة", hi: "छाता", cat: "Dinge", icon: "☂️" },
  { char: "上网", pinyin: "shàngwǎng", de: "surfen", en: "go online", es: "navegar", ar: "يتصفح الإنترنت", hi: "इंटरनेट चलाना", cat: "Aktionen", icon: "🌐" },
  { char: "生气", pinyin: "shēngqì", de: "wütend", en: "angry", es: "enfadado", ar: "غاضب", hi: "गुस्सा", cat: "Emotion", icon: "😠" },
  { char: "声音", pinyin: "shēngyīn", de: "Stimme", en: "sound", es: "sonido", ar: "صوت", hi: "आवाज़", cat: "Dinge", icon: "🔊" },
  { char: "世界", pinyin: "shìjiè", de: "Welt", en: "world", es: "mundo", ar: "عالم", hi: "दुनिया", cat: "Orte", icon: "🌍" },
  { char: "树", pinyin: "shù", de: "Baum", en: "tree", es: "árbol", ar: "شجرة", hi: "पेड़", cat: "Natur", icon: "🌳" },
  { char: "数学", pinyin: "shùxué", de: "Mathe", en: "math", es: "matemáticas", ar: "رياضيات", hi: "गणित", cat: "Schule", icon: "🔢" },
  { char: "刷牙", pinyin: "shuāyá", de: "Zähneputzen", en: "brush teeth", es: "cepillarse", ar: "ينظف أسنانه", hi: "दाँत साफ करना", cat: "Aktionen", icon: "🪥" },
  { char: "双", pinyin: "shuāng", de: "Paar", en: "pair", es: "par", ar: "زوج", hi: "जोड़ा", cat: "Maße", icon: "👟" },
  { char: "水平", pinyin: "shuǐpíng", de: "Niveau", en: "level", es: "nivel", ar: "مستوى", hi: "स्तर", cat: "Geist", icon: "📊" },
  { char: "司机", pinyin: "sījī", de: "Fahrer", en: "driver", es: "conductor", ar: "سائق", hi: "ड्राइवर", cat: "Personen", icon: "🚗" },
  { char: "太阳", pinyin: "tàiyáng", de: "Sonne", en: "sun", es: "sol", ar: "شمس", hi: "सूरज", cat: "Natur", icon: "☀️" },
  { char: "糖", pinyin: "táng", de: "Zucker", en: "sugar", es: "azúcar", ar: "سكر", hi: "चीनी", cat: "Essen", icon: "🍬" },
  { char: "特别", pinyin: "tèbié", de: "besonders", en: "special", es: "especial", ar: "خاص", hi: "खास", cat: "Adjektive", icon: "⭐" },
  { char: "疼", pinyin: "téng", de: "schmerzen", en: "ache", es: "doler", ar: "يؤلم", hi: "दर्द करना", cat: "Gesundheit", icon: "🤕" },
  { char: "提", pinyin: "tí", de: "tragen", en: "carry", es: "llevar", ar: "يحمل", hi: "उठाना", cat: "Verben", icon: "🎒" },
  { char: "提高", pinyin: "tígāo", de: "erhöhen", en: "improve", es: "mejorar", ar: "يحسن", hi: "सुधारना", cat: "Verben", icon: "📈" },
  { char: "体育", pinyin: "tǐyù", de: "Sport", en: "sports", es: "deportes", ar: "رياضة", hi: "खेल", cat: "Schule", icon: "🏃" },
  { char: "条", pinyin: "tiáo", de: "Stück", en: "strip", es: "tira", ar: "شريط", hi: "पट्टी", cat: "Maße", icon: "➖" },
  { char: "同事", pinyin: "tóngshì", de: "Kollege", en: "colleague", es: "colega", ar: "زميل عمل", hi: "सहकर्मी", cat: "Personen", icon: "👔" },
  { char: "同意", pinyin: "tóngyì", de: "zustimmen", en: "agree", es: "estar de acuerdo", ar: "يوافق", hi: "सहमत होना", cat: "Verben", icon: "✅" },
  { char: "头发", pinyin: "tóufa", de: "Haare", en: "hair", es: "cabello", ar: "شعر", hi: "बाल", cat: "Mensch", icon: "💇" },
  { char: "突然", pinyin: "tūrán", de: "plötzlich", en: "suddenly", es: "de repente", ar: "فجأة", hi: "अचानक", cat: "Adverb", icon: "⚡" },
  { char: "图书馆", pinyin: "túshūguǎn", de: "Bibliothek", en: "library", es: "biblioteca", ar: "مكتبة", hi: "पुस्तकालय", cat: "Orte", icon: "📚" },
  { char: "腿", pinyin: "tuǐ", de: "Bein", en: "leg", es: "pierna", ar: "ساق", hi: "टाँग", cat: "Mensch", icon: "🦵" },
  { char: "完成", pinyin: "wánchéng", de: "beenden", en: "complete", es: "completar", ar: "يكمل", hi: "पूरा करना", cat: "Verben", icon: "✅" },
  { char: "碗", pinyin: "wǎn", de: "Schüssel", en: "bowl", es: "tazón", ar: "وعاء", hi: "कटोरा", cat: "Dinge", icon: "🥣" },
  { char: "万", pinyin: "wàn", de: "zehntausend", en: "ten thousand", es: "diez mil", ar: "عشرة آلاف", hi: "दस हज़ार", cat: "Zahlen", icon: "🔢" },
  { char: "忘记", pinyin: "wàngjì", de: "vergessen", en: "forget", es: "olvidar", ar: "ينسى", hi: "भूलना", cat: "Geist", icon: "🤔" },
  { char: "危险", pinyin: "wēixiǎn", de: "gefährlich", en: "dangerous", es: "peligroso", ar: "خطير", hi: "खतरनाक", cat: "Adjektive", icon: "⚠️" },
  { char: "位", pinyin: "wèi", de: "Person", en: "person", es: "persona", ar: "شخص", hi: "व्यक्ति", cat: "Maße", icon: "👤" },
  { char: "文化", pinyin: "wénhuà", de: "Kultur", en: "culture", es: "cultura", ar: "ثقافة", hi: "संस्कृति", cat: "Kultur", icon: "🎭" },
  { char: "西", pinyin: "xī", de: "Westen", en: "west", es: "oeste", ar: "غرب", hi: "पश्चिम", cat: "Richtungen", icon: "🌅" },
  { char: "习惯", pinyin: "xíguàn", de: "Gewohnheit", en: "habit", es: "costumbre", ar: "عادة", hi: "आदत", cat: "Geist", icon: "🔄" },
  { char: "洗手间", pinyin: "xǐshǒujiān", de: "WC", en: "restroom", es: "baño", ar: "حمام", hi: "शौचालय", cat: "Orte", icon: "🚻" },
  { char: "洗澡", pinyin: "xǐzǎo", de: "duschen", en: "shower", es: "ducharse", ar: "يستحم", hi: "नहाना", cat: "Aktionen", icon: "🚿" },
  { char: "夏", pinyin: "xià", de: "Sommer", en: "summer", es: "verano", ar: "صيف", hi: "गर्मी", cat: "Zeit", icon: "☀️" },
  { char: "先", pinyin: "xiān", de: "zuerst", en: "first", es: "primero", ar: "أولاً", hi: "पहले", cat: "Adverb", icon: "1️⃣" },
  { char: "相信", pinyin: "xiāngxìn", de: "glauben", en: "believe", es: "creer", ar: "يصدق", hi: "विश्वास करना", cat: "Geist", icon: "✅" },
  { char: "像", pinyin: "xiàng", de: "aussehen", en: "look like", es: "parecer", ar: "يشبه", hi: "जैसा", cat: "Verben", icon: "👀" },
  { char: "小心", pinyin: "xiǎoxīn", de: "vorsichtig", en: "careful", es: "cuidado", ar: "حذر", hi: "सावधान", cat: "Adjektive", icon: "⚠️" },
  { char: "校长", pinyin: "xiàozhǎng", de: "Rektor", en: "principal", es: "director", ar: "مدير المدرسة", hi: "प्राचार्य", cat: "Personen", icon: "🎓" },
  { char: "鞋", pinyin: "xié", de: "Schuh", en: "shoe", es: "zapato", ar: "حذاء", hi: "जूता", cat: "Dinge", icon: "👟" },
  { char: "新闻", pinyin: "xīnwén", de: "Nachrichten", en: "news", es: "noticias", ar: "أخبار", hi: "समाचार", cat: "Dinge", icon: "📰" },
  { char: "信", pinyin: "xìn", de: "Brief", en: "letter", es: "carta", ar: "رسالة", hi: "पत्र", cat: "Dinge", icon: "✉️" },
  { char: "信用卡", pinyin: "xìnyòngkǎ", de: "Kreditkarte", en: "credit card", es: "tarjeta de crédito", ar: "بطاقة ائتمان", hi: "क्रेडिट कार्ड", cat: "Geld", icon: "💳" },
  { char: "行", pinyin: "xíng", de: "OK", en: "OK", es: "vale", ar: "حسناً", hi: "ठीक है", cat: "Adverb", icon: "👌" },
  { char: "兴趣", pinyin: "xìngqù", de: "Interesse", en: "interest", es: "interés", ar: "اهتمام", hi: "रुचि", cat: "Geist", icon: "⭐" },
  { char: "姓", pinyin: "xìng", de: "Nachname", en: "surname", es: "apellido", ar: "لقب", hi: "उपनाम", cat: "Personen", icon: "📛" },
  { char: "熊猫", pinyin: "xióngmāo", de: "Panda", en: "panda", es: "panda", ar: "باندا", hi: "पांडा", cat: "Natur", icon: "🐼" },
  { char: "需要", pinyin: "xūyào", de: "brauchen", en: "need", es: "necesitar", ar: "يحتاج", hi: "ज़रूरत होना", cat: "Verben", icon: "🙏" },
  { char: "选择", pinyin: "xuǎnzé", de: "wählen", en: "choose", es: "elegir", ar: "يختار", hi: "चुनना", cat: "Verben", icon: "✅" },
  { char: "牙", pinyin: "yá", de: "Zahn", en: "tooth", es: "diente", ar: "سن", hi: "दाँत", cat: "Mensch", icon: "🦷" },
  { char: "羊肉", pinyin: "yángròu", de: "Lammfleisch", en: "lamb", es: "cordero", ar: "لحم خروف", hi: "मटन", cat: "Essen", icon: "🍖" },
  { char: "要求", pinyin: "yāoqiú", de: "verlangen", en: "require", es: "requerir", ar: "يطلب", hi: "माँगना", cat: "Verben", icon: "📋" },
  { char: "爷爷", pinyin: "yéye", de: "Opa", en: "grandpa", es: "abuelo", ar: "جد", hi: "दादा", cat: "Personen", icon: "👴" },
  { char: "叶子", pinyin: "yèzi", de: "Blatt", en: "leaf", es: "hoja", ar: "ورقة", hi: "पत्ता", cat: "Natur", icon: "🍃" },
  { char: "一般", pinyin: "yìbān", de: "normal", en: "normal", es: "normal", ar: "عادي", hi: "सामान्य", cat: "Adjektive", icon: "📊" },
  { char: "一边", pinyin: "yìbiān", de: "gleichzeitig", en: "while", es: "mientras", ar: "أثناء", hi: "साथ-साथ", cat: "Adverb", icon: "↔️" },
  { char: "一定", pinyin: "yídìng", de: "bestimmt", en: "certainly", es: "ciertamente", ar: "بالتأكيد", hi: "ज़रूर", cat: "Adverb", icon: "✅" },
  { char: "一共", pinyin: "yígòng", de: "insgesamt", en: "total", es: "en total", ar: "إجمالاً", hi: "कुल मिलाकर", cat: "Adverb", icon: "📊" },
  { char: "一会儿", pinyin: "yíhuìr", de: "kurz", en: "a moment", es: "un momento", ar: "لحظة", hi: "थोड़ी देर", cat: "Zeit", icon: "⏰" },
  { char: "一直", pinyin: "yìzhí", de: "immer", en: "always", es: "siempre", ar: "دائماً", hi: "हमेशा", cat: "Adverb", icon: "➡️" },
  { char: "以前", pinyin: "yǐqián", de: "früher", en: "before", es: "antes", ar: "من قبل", hi: "पहले", cat: "Zeit", icon: "⏪" },
  { char: "以为", pinyin: "yǐwéi", de: "meinen", en: "think", es: "creer", ar: "يظن", hi: "सोचना", cat: "Geist", icon: "💭" },
  { char: "银行", pinyin: "yínháng", de: "Bank", en: "bank", es: "banco", ar: "بنك", hi: "बैंक", cat: "Orte", icon: "🏦" },
  { char: "饮料", pinyin: "yǐnliào", de: "Getränk", en: "drink", es: "bebida", ar: "مشروب", hi: "पेय", cat: "Essen", icon: "🥤" },
  { char: "应该", pinyin: "yīnggāi", de: "sollen", en: "should", es: "deber", ar: "ينبغي", hi: "चाहिए", cat: "Verben", icon: "✅" },
  { char: "影响", pinyin: "yǐngxiǎng", de: "Einfluss", en: "influence", es: "influencia", ar: "تأثير", hi: "प्रभाव", cat: "Geist", icon: "🌊" },
  { char: "用", pinyin: "yòng", de: "benutzen", en: "use", es: "usar", ar: "يستخدم", hi: "उपयोग करना", cat: "Verben", icon: "🔧" },
  { char: "邮局", pinyin: "yóujú", de: "Post", en: "post office", es: "correos", ar: "مكتب البريد", hi: "डाकघर", cat: "Orte", icon: "📮" },
  { char: "又", pinyin: "yòu", de: "wieder", en: "again", es: "otra vez", ar: "مرة أخرى", hi: "फिर से", cat: "Adverb", icon: "🔁" },
  { char: "有名", pinyin: "yǒumíng", de: "berühmt", en: "famous", es: "famoso", ar: "مشهور", hi: "प्रसिद्ध", cat: "Adjektive", icon: "⭐" },
  { char: "遇到", pinyin: "yùdào", de: "treffen", en: "meet", es: "encontrar", ar: "يقابل", hi: "मिलना", cat: "Verben", icon: "🤝" },
  { char: "元", pinyin: "yuán", de: "Yuan", en: "yuan", es: "yuan", ar: "يوان", hi: "युआन", cat: "Geld", icon: "💴" },
  { char: "月亮", pinyin: "yuèliang", de: "Mond", en: "moon", es: "luna", ar: "قمر", hi: "चाँद", cat: "Natur", icon: "🌙" },
  { char: "越", pinyin: "yuè", de: "je mehr", en: "more", es: "más", ar: "أكثر", hi: "जितना अधिक", cat: "Grammatik", icon: "📈" },
  { char: "站", pinyin: "zhàn", de: "stehen", en: "stand", es: "estar de pie", ar: "يقف", hi: "खड़ा होना", cat: "Verben", icon: "🧍" },
  { char: "照顾", pinyin: "zhàogù", de: "kümmern", en: "care for", es: "cuidar", ar: "يعتني", hi: "देखभाल करना", cat: "Verben", icon: "🤗" },
  { char: "照片", pinyin: "zhàopiàn", de: "Foto", en: "photo", es: "foto", ar: "صورة", hi: "फोटो", cat: "Dinge", icon: "📷" },
  { char: "照相机", pinyin: "zhàoxiàngjī", de: "Kamera", en: "camera", es: "cámara", ar: "كاميرا", hi: "कैमरा", cat: "Dinge", icon: "📸" },
  { char: "只", pinyin: "zhǐ", de: "nur", en: "only", es: "solo", ar: "فقط", hi: "सिर्फ", cat: "Adverb", icon: "1️⃣" },
  { char: "只有", pinyin: "zhǐyǒu", de: "nur", en: "only", es: "solo", ar: "فقط", hi: "केवल", cat: "Adverb", icon: "☝️" },
  { char: "中间", pinyin: "zhōngjiān", de: "Mitte", en: "middle", es: "medio", ar: "وسط", hi: "बीच में", cat: "Richtungen", icon: "⏺️" },
  { char: "终于", pinyin: "zhōngyú", de: "endlich", en: "finally", es: "finalmente", ar: "أخيراً", hi: "आखिरकार", cat: "Adverb", icon: "🎉" },
  { char: "种", pinyin: "zhǒng", de: "Art", en: "kind", es: "tipo", ar: "نوع", hi: "प्रकार", cat: "Maße", icon: "📦" },
  { char: "重要", pinyin: "zhòngyào", de: "wichtig", en: "important", es: "importante", ar: "مهم", hi: "महत्वपूर्ण", cat: "Adjektive", icon: "⭐" },
  { char: "周末", pinyin: "zhōumò", de: "Wochenende", en: "weekend", es: "fin de semana", ar: "عطلة نهاية الأسبوع", hi: "सप्ताहांत", cat: "Zeit", icon: "🎉" },
  { char: "主要", pinyin: "zhǔyào", de: "hauptsächlich", en: "main", es: "principal", ar: "رئيسي", hi: "मुख्य", cat: "Adjektive", icon: "⭐" },
  { char: "注意", pinyin: "zhùyì", de: "beachten", en: "pay attention", es: "prestar atención", ar: "ينتبه", hi: "ध्यान देना", cat: "Verben", icon: "⚠️" },
  { char: "自己", pinyin: "zìjǐ", de: "selbst", en: "self", es: "uno mismo", ar: "نفسه", hi: "खुद", cat: "Pronomen", icon: "👤" },
  { char: "总是", pinyin: "zǒngshì", de: "immer", en: "always", es: "siempre", ar: "دائماً", hi: "हमेशा", cat: "Adverb", icon: "🔄" },
  { char: "嘴", pinyin: "zuǐ", de: "Mund", en: "mouth", es: "boca", ar: "فم", hi: "मुँह", cat: "Mensch", icon: "👄" },
  { char: "作业", pinyin: "zuòyè", de: "Hausaufgabe", en: "homework", es: "deberes", ar: "واجب منزلي", hi: "गृहकार्य", cat: "Schule", icon: "📝" },
  { char: "南", pinyin: "nán", de: "Süden", en: "south", es: "sur", ar: "جنوب", hi: "दक्षिण", cat: "Richtungen", icon: "🧭" },
  { char: "北", pinyin: "běi", de: "Norden", en: "north", es: "norte", ar: "شمال", hi: "उत्तर", cat: "Richtungen", icon: "🧭" },
  { char: "东", pinyin: "dōng", de: "Osten", en: "east", es: "este", ar: "شرق", hi: "पूर्व", cat: "Richtungen", icon: "🌅" },
  { char: "河", pinyin: "hé", de: "Fluss", en: "river", es: "río", ar: "نهر", hi: "नदी", cat: "Natur", icon: "🏞️" },
  { char: "口", pinyin: "kǒu", de: "Mund", en: "mouth", es: "boca", ar: "فم", hi: "मुँह", cat: "Mensch", icon: "👄" },
  { char: "脸", pinyin: "liǎn", de: "Gesicht", en: "face", es: "cara", ar: "وجه", hi: "चेहरा", cat: "Mensch", icon: "😊" },
  { char: "鼻子", pinyin: "bízi", de: "Nase", en: "nose", es: "nariz", ar: "أنف", hi: "नाक", cat: "Mensch", icon: "👃" },
  { char: "耳朵", pinyin: "ěrduo", de: "Ohr", en: "ear", es: "oreja", ar: "أذن", hi: "कान", cat: "Mensch", icon: "👂" },
  { char: "手", pinyin: "shǒu", de: "Hand", en: "hand", es: "mano", ar: "يد", hi: "हाथ", cat: "Mensch", icon: "✋" },
  { char: "脚", pinyin: "jiǎo", de: "Fuß", en: "foot", es: "pie", ar: "قدم", hi: "पैर", cat: "Mensch", icon: "🦶" },
  { char: "帽子", pinyin: "màozi", de: "Hut", en: "hat", es: "sombrero", ar: "قبعة", hi: "टोपी", cat: "Dinge", icon: "🎩" },
  { char: "裤子", pinyin: "kùzi", de: "Hose", en: "pants", es: "pantalones", ar: "سروال", hi: "पैंट", cat: "Dinge", icon: "👖" },
  { char: "衬衫", pinyin: "chènshān", de: "Hemd", en: "shirt", es: "camisa", ar: "قميص", hi: "शर्ट", cat: "Dinge", icon: "👔" },
  { char: "眼镜", pinyin: "yǎnjìng", de: "Brille", en: "glasses", es: "gafas", ar: "نظارات", hi: "चश्मा", cat: "Dinge", icon: "👓" },
  { char: "电影", pinyin: "diànyǐng", de: "Film", en: "movie", es: "película", ar: "فيلم", hi: "फ़िल्म", cat: "Kultur", icon: "🎬" },
  { char: "音乐", pinyin: "yīnyuè", de: "Musik", en: "music", es: "música", ar: "موسيقى", hi: "संगीत", cat: "Kultur", icon: "🎵" },
  { char: "黄", pinyin: "huáng", de: "gelb", en: "yellow", es: "amarillo", ar: "أصفر", hi: "पीला", cat: "Farben", icon: "🟡" },
  { char: "瓶子", pinyin: "píngzi", de: "Flasche", en: "bottle", es: "botella", ar: "زجاجة", hi: "बोतल", cat: "Dinge", icon: "🍾" },
  { char: "草", pinyin: "cǎo", de: "Gras", en: "grass", es: "hierba", ar: "عشب", hi: "घास", cat: "Natur", icon: "🌿" },
  { char: "米", pinyin: "mǐ", de: "Meter", en: "meter", es: "metro", ar: "متر", hi: "मीटर", cat: "Maße", icon: "📏" },
  { char: "公斤", pinyin: "gōngjīn", de: "Kilogramm", en: "kilogram", es: "kilogramo", ar: "كيلوغرام", hi: "किलोग्राम", cat: "Maße", icon: "⚖️" },
  { char: "见面", pinyin: "jiànmiàn", de: "treffen", en: "meet", es: "encontrarse", ar: "يلتقي", hi: "मिलना", cat: "Verben", icon: "🤝" },
  { char: "放", pinyin: "fàng", de: "legen", en: "put", es: "poner", ar: "يضع", hi: "रखना", cat: "Verben", icon: "📦" },
  { char: "半", pinyin: "bàn", de: "halb", en: "half", es: "medio", ar: "نصف", hi: "आधा", cat: "Zahlen", icon: "½" },
  { char: "刻", pinyin: "kè", de: "Viertelstunde", en: "quarter", es: "cuarto", ar: "ربع ساعة", hi: "पंद्रह मिनट", cat: "Zeit", icon: "⏰" },
  { char: "明年", pinyin: "míngnián", de: "nächstes Jahr", en: "next year", es: "próximo año", ar: "السنة القادمة", hi: "अगला साल", cat: "Zeit", icon: "📅" },
  { char: "上个月", pinyin: "shàng gè yuè", de: "letzten Monat", en: "last month", es: "mes pasado", ar: "الشهر الماضي", hi: "पिछला महीना", cat: "Zeit", icon: "📆" },
  { char: "回答", pinyin: "huídá", de: "antworten", en: "answer", es: "responder", ar: "يجيب", hi: "जवाब देना", cat: "Verben", icon: "💬" },
  { char: "黑板", pinyin: "hēibǎn", de: "Tafel", en: "blackboard", es: "pizarra", ar: "سبورة", hi: "ब्लैकबोर्ड", cat: "Schule", icon: "📋" },
  { char: "长城", pinyin: "chángchéng", de: "Große Mauer", en: "Great Wall", es: "Gran Muralla", ar: "سور الصين العظيم", hi: "चीन की दीवार", cat: "Orte", icon: "🏯" },
  { char: "马上", pinyin: "mǎshàng", de: "sofort", en: "immediately", es: "inmediatamente", ar: "فوراً", hi: "तुरंत", cat: "Adverb", icon: "⚡" },
  { char: "到处", pinyin: "dàochù", de: "überall", en: "everywhere", es: "en todas partes", ar: "في كل مكان", hi: "हर जगह", cat: "Adverb", icon: "🌍" },
  { char: "最后", pinyin: "zuìhòu", de: "zuletzt", en: "finally", es: "por último", ar: "أخيراً", hi: "अंत में", cat: "Adverb", icon: "🏁" },
  { char: "渴", pinyin: "kě", de: "durstig", en: "thirsty", es: "sediento", ar: "عطشان", hi: "प्यासा", cat: "Gefühle", icon: "💧" },
  { char: "饿", pinyin: "è", de: "hungrig", en: "hungry", es: "hambriento", ar: "جائع", hi: "भूखा", cat: "Gefühle", icon: "🍔" },
  { char: "办", pinyin: "bàn", de: "erledigen", en: "handle", es: "gestionar", ar: "ينجز", hi: "करना", cat: "Verben", icon: "📋" },
  { char: "着", pinyin: "zhe", de: "Dauer-P.", en: "continuous", es: "continuo", ar: "مستمر", hi: "रहा/रही", cat: "Grammatik", icon: "⏳" },
  { char: "啊", pinyin: "a", de: "Partikel", en: "particle", es: "partícula", ar: "آه", hi: "आह", cat: "Grammatik", icon: "💬" },
  { char: "啤酒", pinyin: "píjiǔ", de: "Bier", en: "beer", es: "cerveza", ar: "بيرة", hi: "बीयर", cat: "Essen", icon: "🍺" },
  { char: "葡萄", pinyin: "pútao", de: "Traube", en: "grape", es: "uva", ar: "عنب", hi: "अंगूर", cat: "Essen", icon: "🍇" },
  { char: "香蕉", pinyin: "xiāngjiāo", de: "Banane", en: "banana", es: "plátano", ar: "موز", hi: "केला", cat: "Essen", icon: "🍌" },
  { char: "苹果", pinyin: "píngguǒ", de: "Apfel", en: "apple", es: "manzana", ar: "تفاحة", hi: "सेब", cat: "Essen", icon: "🍎" },
  { char: "西瓜", pinyin: "xīguā", de: "Wassermelone", en: "watermelon", es: "sandía", ar: "بطيخ", hi: "तरबूज", cat: "Essen", icon: "🍉" },
  { char: "牛奶", pinyin: "niúnǎi", de: "Milch", en: "milk", es: "leche", ar: "حليب", hi: "दूध", cat: "Essen", icon: "🥛" },
  { char: "鸡蛋", pinyin: "jīdàn", de: "Ei", en: "egg", es: "huevo", ar: "بيضة", hi: "अंडा", cat: "Essen", icon: "🥚" },
  { char: "面条", pinyin: "miàntiáo", de: "Nudeln", en: "noodles", es: "fideos", ar: "نودلز", hi: "नूडल्स", cat: "Essen", icon: "🍜" },
  { char: "米饭", pinyin: "mǐfàn", de: "Reis", en: "rice", es: "arroz", ar: "أرز", hi: "चावल", cat: "Essen", icon: "🍚" },
  { char: "饺子", pinyin: "jiǎozi", de: "Teigtasche", en: "dumpling", es: "dumpling", ar: "فطيرة محشوة", hi: "मोमो", cat: "Essen", icon: "🥟" },
  { char: "便宜", pinyin: "piányi", de: "günstig", en: "cheap", es: "barato", ar: "رخيص", hi: "सस्ता", cat: "Adjektive", icon: "💰" },
  { char: "贵", pinyin: "guì", de: "teuer", en: "expensive", es: "caro", ar: "غالي", hi: "महँगा", cat: "Adjektive", icon: "💎" },
  { char: "矮", pinyin: "ǎi", de: "klein", en: "short", es: "bajo", ar: "قصير", hi: "नाटा", cat: "Adjektive", icon: "📏" },
  { char: "瘦", pinyin: "shòu", de: "dünn", en: "thin", es: "delgado", ar: "نحيف", hi: "पतला", cat: "Adjektive", icon: "🧍" },
  { char: "胖", pinyin: "pàng", de: "dick", en: "fat", es: "gordo", ar: "سمين", hi: "मोटा", cat: "Adjektive", icon: "🍔" },
  { char: "旧", pinyin: "jiù", de: "alt", en: "old", es: "viejo", ar: "قديم", hi: "पुराना", cat: "Adjektive", icon: "📦" },
  { char: "新鲜", pinyin: "xīnxiān", de: "frisch", en: "fresh", es: "fresco", ar: "طازج", hi: "ताज़ा", cat: "Adjektive", icon: "🌿" },
  { char: "甜", pinyin: "tián", de: "süß", en: "sweet", es: "dulce", ar: "حلو", hi: "मीठा", cat: "Adjektive", icon: "🍬" },
  { char: "咸", pinyin: "xián", de: "salzig", en: "salty", es: "salado", ar: "مالح", hi: "नमकीन", cat: "Adjektive", icon: "🧂" },
  { char: "辣", pinyin: "là", de: "scharf", en: "spicy", es: "picante", ar: "حار", hi: "तीखा", cat: "Adjektive", icon: "🌶️" },
  { char: "酸", pinyin: "suān", de: "sauer", en: "sour", es: "ácido", ar: "حامض", hi: "खट्टा", cat: "Adjektive", icon: "🍋" },
  { char: "苦", pinyin: "kǔ", de: "bitter", en: "bitter", es: "amargo", ar: "مر", hi: "कड़वा", cat: "Adjektive", icon: "☕" },
  { char: "黑", pinyin: "hēi", de: "schwarz", en: "black", es: "negro", ar: "أسود", hi: "काला", cat: "Farben", icon: "⚫" },
  { char: "白", pinyin: "bái", de: "weiß", en: "white", es: "blanco", ar: "أبيض", hi: "सफ़ेद", cat: "Farben", icon: "⚪" },
  { char: "叔叔", pinyin: "shūshu", de: "Onkel", en: "uncle", es: "tío", ar: "عم", hi: "चाचा", cat: "Personen", icon: "👨" },
  { char: "邻居", pinyin: "línjū", de: "Nachbar", en: "neighbor", es: "vecino", ar: "جار", hi: "पड़ोसी", cat: "Personen", icon: "🏠" },
  { char: "客人", pinyin: "kèrén", de: "Gast", en: "guest", es: "invitado", ar: "ضيف", hi: "मेहमान", cat: "Personen", icon: "🧑‍🤝‍🧑" },
  { char: "服务员", pinyin: "fúwùyuán", de: "Kellner", en: "waiter", es: "camarero", ar: "نادل", hi: "वेटर", cat: "Personen", icon: "🧑‍🍳" },
  { char: "医生", pinyin: "yīshēng", de: "Arzt", en: "doctor", es: "médico", ar: "طبيب", hi: "डॉक्टर", cat: "Personen", icon: "👨‍⚕️" },
  { char: "护士", pinyin: "hùshi", de: "Krankenschwester", en: "nurse", es: "enfermera", ar: "ممرضة", hi: "नर्स", cat: "Personen", icon: "👩‍⚕️" },
  { char: "警察", pinyin: "jǐngchá", de: "Polizist", en: "police", es: "policía", ar: "شرطي", hi: "पुलिस", cat: "Personen", icon: "👮" },
  { char: "律师", pinyin: "lǜshī", de: "Anwalt", en: "lawyer", es: "abogado", ar: "محامي", hi: "वकील", cat: "Personen", icon: "⚖️" },
  { char: "作家", pinyin: "zuòjiā", de: "Schriftsteller", en: "writer", es: "escritor", ar: "كاتب", hi: "लेखक", cat: "Personen", icon: "✍️" },
  { char: "演员", pinyin: "yǎnyuán", de: "Schauspieler", en: "actor", es: "actor", ar: "ممثل", hi: "अभिनेता", cat: "Personen", icon: "🎭" },
  { char: "记者", pinyin: "jìzhě", de: "Journalist", en: "journalist", es: "periodista", ar: "صحفي", hi: "पत्रकार", cat: "Personen", icon: "📰" },
  { char: "接", pinyin: "jiē", de: "abholen", en: "pick up", es: "recoger", ar: "يستقبل", hi: "लेना", cat: "Verben", icon: "🤝" },
  { char: "送", pinyin: "sòng", de: "bringen", en: "give/send", es: "enviar", ar: "يرسل", hi: "भेजना", cat: "Verben", icon: "🎁" },
  { char: "帮助", pinyin: "bāngzhù", de: "helfen", en: "help", es: "ayudar", ar: "يساعد", hi: "मदद करना", cat: "Verben", icon: "🤝" },
  { char: "关心", pinyin: "guānxīn", de: "sich kümmern", en: "care about", es: "preocuparse", ar: "يهتم", hi: "परवाह करना", cat: "Verben", icon: "❤️" },
  { char: "感谢", pinyin: "gǎnxiè", de: "danken", en: "thank", es: "agradecer", ar: "يشكر", hi: "धन्यवाद देना", cat: "Verben", icon: "🙏" },
  { char: "欢迎", pinyin: "huānyíng", de: "willkommen", en: "welcome", es: "bienvenido", ar: "يرحب", hi: "स्वागत करना", cat: "Verben", icon: "👋" },
  { char: "告诉", pinyin: "gàosu", de: "sagen", en: "tell", es: "decir", ar: "يخبر", hi: "बताना", cat: "Verben", icon: "🗣️" },
  { char: "希望", pinyin: "xīwàng", de: "hoffen", en: "hope", es: "esperar", ar: "يأمل", hi: "उम्मीद करना", cat: "Verben", icon: "🌟" },
  { char: "了解", pinyin: "liǎojiě", de: "verstehen", en: "understand", es: "entender", ar: "يفهم", hi: "समझना", cat: "Verben", icon: "🧠" },
  { char: "表示", pinyin: "biǎoshì", de: "ausdrücken", en: "express", es: "expresar", ar: "يعبر", hi: "व्यक्त करना", cat: "Verben", icon: "💬" },
  { char: "感觉", pinyin: "gǎnjué", de: "fühlen", en: "feel", es: "sentir", ar: "يشعر", hi: "महसूस करना", cat: "Verben", icon: "🫀" },
  { char: "发", pinyin: "fā", de: "senden", en: "send", es: "mandar", ar: "يرسل", hi: "भेजना", cat: "Verben", icon: "📤" },
  { char: "拿", pinyin: "ná", de: "nehmen", en: "take", es: "tomar", ar: "يأخذ", hi: "लेना", cat: "Verben", icon: "✋" },
  { char: "带", pinyin: "dài", de: "mitnehmen", en: "bring", es: "llevar", ar: "يحضر", hi: "लाना", cat: "Verben", icon: "🎒" },
  { char: "画", pinyin: "huà", de: "zeichnen", en: "draw", es: "dibujar", ar: "يرسم", hi: "चित्र बनाना", cat: "Verben", icon: "🎨" },
  { char: "唱歌", pinyin: "chànggē", de: "singen", en: "sing", es: "cantar", ar: "يغني", hi: "गाना गाना", cat: "Verben", icon: "🎤" },
  { char: "跳舞", pinyin: "tiàowǔ", de: "tanzen", en: "dance", es: "bailar", ar: "يرقص", hi: "नाचना", cat: "Verben", icon: "💃" },
  { char: "游泳", pinyin: "yóuyǒng", de: "schwimmen", en: "swim", es: "nadar", ar: "يسبح", hi: "तैरना", cat: "Sport", icon: "🏊" },
  { char: "踢足球", pinyin: "tī zúqiú", de: "Fußball spielen", en: "play football", es: "jugar fútbol", ar: "يلعب كرة القدم", hi: "फुटबॉल खेलना", cat: "Sport", icon: "⚽" },
  { char: "打篮球", pinyin: "dǎ lánqiú", de: "Basketball spielen", en: "play basketball", es: "jugar baloncesto", ar: "يلعب كرة السلة", hi: "बास्केटबॉल खेलना", cat: "Sport", icon: "🏀" },
  { char: "爱好", pinyin: "àihào", de: "Hobby", en: "hobby", es: "afición", ar: "هواية", hi: "शौक", cat: "Kultur", icon: "⭐" },
  { char: "着急", pinyin: "zháojí", de: "besorgt", en: "worried", es: "ansioso", ar: "قلق", hi: "घबराया हुआ", cat: "Emotion", icon: "😰" },
  { char: "高兴", pinyin: "gāoxìng", de: "froh", en: "happy", es: "feliz", ar: "سعيد", hi: "खुश", cat: "Emotion", icon: "😊" },
  { char: "伤心", pinyin: "shāngxīn", de: "traurig", en: "sad", es: "triste", ar: "حزين", hi: "दुखी", cat: "Emotion", icon: "😢" },
  { char: "放心", pinyin: "fàngxīn", de: "beruhigt", en: "relieved", es: "tranquilo", ar: "مطمئن", hi: "निश्चिंत", cat: "Emotion", icon: "😌" },
  { char: "离开", pinyin: "líkāi", de: "verlassen", en: "leave", es: "salir", ar: "يغادر", hi: "छोड़ना", cat: "Verben", icon: "🚶" },
  { char: "经过", pinyin: "jīngguò", de: "vorbeigehen", en: "pass by", es: "pasar", ar: "يمر", hi: "गुज़रना", cat: "Verben", icon: "🚶" },
  { char: "过去", pinyin: "guòqù", de: "Vergangenheit", en: "past", es: "pasado", ar: "الماضي", hi: "अतीत", cat: "Zeit", icon: "⏪" },
  { char: "将来", pinyin: "jiānglái", de: "Zukunft", en: "future", es: "futuro", ar: "المستقبل", hi: "भविष्य", cat: "Zeit", icon: "⏩" },
  { char: "最近", pinyin: "zuìjìn", de: "kürzlich", en: "recently", es: "recientemente", ar: "مؤخراً", hi: "हाल ही में", cat: "Zeit", icon: "📅" },
  { char: "刚才", pinyin: "gāngcái", de: "gerade eben", en: "just now", es: "hace un momento", ar: "للتو", hi: "अभी-अभी", cat: "Zeit", icon: "⏰" },
  { char: "几乎", pinyin: "jīhū", de: "fast", en: "almost", es: "casi", ar: "تقريباً", hi: "लगभग", cat: "Adverb", icon: "≈" },
  { char: "根据", pinyin: "gēnjù", de: "laut", en: "according to", es: "según", ar: "وفقاً لـ", hi: "के अनुसार", cat: "Grammatik", icon: "📋" },
  { char: "或者", pinyin: "huòzhě", de: "oder", en: "or", es: "o", ar: "أو", hi: "या", cat: "Grammatik", icon: "↔️" },
  { char: "而且", pinyin: "érqiě", de: "außerdem", en: "moreover", es: "además", ar: "بالإضافة", hi: "और भी", cat: "Grammatik", icon: "➕" },
  { char: "虽然", pinyin: "suīrán", de: "obwohl", en: "although", es: "aunque", ar: "على الرغم", hi: "हालाँकि", cat: "Grammatik", icon: "🔄" }
];
