// HSK 4 Vocabulary (600 words)
export const hsk4Vocab = [
  { char: "爱情", pinyin: "àiqíng", de: "Liebe", en: "love", es: "amor", hi: "प्रेम", cat: "Emotion", icon: "❤️" },
  { char: "安排", pinyin: "ānpái", de: "Plan", en: "arrange", es: "organizar", hi: "व्यवस्था", cat: "Aktionen", icon: "📅" },
  { char: "安全", pinyin: "ānquán", de: "Sicherheit", en: "safe", es: "seguro", hi: "सुरक्षित", cat: "Adjektive", icon: "🛡️" },
  { char: "按时", pinyin: "ànshí", de: "Pünktlich", en: "on time", es: "a tiempo", hi: "समय पर", cat: "Zeit", icon: "⌚" },
  { char: "保护", pinyin: "bǎohù", de: "Schutz", en: "protect", es: "proteger", hi: "रक्षा करना", cat: "Verben", icon: "🔒" },
  { char: "报名", pinyin: "bàomíng", de: "Anmeldung", en: "sign up", es: "inscribirse", hi: "पंजीकरण", cat: "Aktionen", icon: "📝" },
  { char: "抱歉", pinyin: "bàoqiàn", de: "Sorry", en: "apologize", es: "lo siento", hi: "क्षमा करें", cat: "Emotion", icon: "🙏" },
  { char: "毕业", pinyin: "bìyè", de: "Abschluss", en: "graduate", es: "graduarse", hi: "स्नातक", cat: "Schule", icon: "🎓" },
  { char: "表格", pinyin: "biǎogé", de: "Liste", en: "form", es: "formulario", hi: "फ़ॉर्म", cat: "Dinge", icon: "📋" },
  { char: "表演", pinyin: "biǎoyǎn", de: "Show", en: "perform", es: "actuar", hi: "प्रदर्शन", cat: "Kultur", icon: "🎭" },
  { char: "饼干", pinyin: "bǐnggān", de: "Keks", en: "biscuit", es: "galleta", hi: "बिस्कुट", cat: "Essen", icon: "🍪" },
  { char: "博士", pinyin: "bóshì", de: "PhD", en: "doctor", es: "doctor", hi: "डॉक्टरेट", cat: "Personen", icon: "👨‍🎓" },
  { char: "不得不", pinyin: "bùdébù", de: "Muss", en: "have to", es: "tener que", hi: "मजबूर होना", cat: "Adverb", icon: "🤷" },
  { char: "材料", pinyin: "cáiliào", de: "Stoff", en: "material", es: "material", hi: "सामग्री", cat: "Dinge", icon: "🏗️" },
  { char: "参观", pinyin: "cānguān", de: "Besuch", en: "visit", es: "visitar", hi: "भ्रमण", cat: "Aktionen", icon: "👀" },
  { char: "成功", pinyin: "chénggōng", de: "Win", en: "success", es: "éxito", hi: "सफलता", cat: "Verben", icon: "🏆" },
  { char: "成为", pinyin: "chéngwéi", de: "Werden", en: "become", es: "llegar a ser", hi: "बनना", cat: "Verben", icon: "✨" },
  { char: "诚实", pinyin: "chéngshí", de: "Ehrlich", en: "honest", es: "honesto", hi: "ईमानदार", cat: "Adjektive", icon: "😇" },
  { char: "出发", pinyin: "chūfā", de: "Go", en: "set out", es: "partir", hi: "निकलना", cat: "Aktionen", icon: "🚀" },
  { char: "出生", pinyin: "chūshēng", de: "Geburt", en: "be born", es: "nacer", hi: "जन्म लेना", cat: "Verben", icon: "👶" },
  { char: "传真", pinyin: "chuánzhēn", de: "Fax", en: "fax", es: "fax", hi: "फ़ैक्स", cat: "Dinge", icon: "📠" },
  { char: "窗户", pinyin: "chuānghu", de: "Fenster", en: "window", es: "ventana", hi: "खिड़की", cat: "Dinge", icon: "🪟" },
  { char: "存", pinyin: "cún", de: "Spar", en: "save", es: "guardar", hi: "बचाना", cat: "Aktionen", icon: "🏦" },
  { char: "错误", pinyin: "cuòwù", de: "Fehler", en: "mistake", es: "error", hi: "गलती", cat: "Dinge", icon: "❌" },
  { char: "答案", pinyin: "dá'àn", de: "Antwort", en: "answer", es: "respuesta", hi: "उत्तर", cat: "Schule", icon: "📝" },
  { char: "打扰", pinyin: "dǎrǎo", de: "Stör", en: "disturb", es: "molestar", hi: "परेशान करना", cat: "Verben", icon: "🚫" },
  { char: "打印", pinyin: "dǎyìn", de: "Print", en: "print", es: "imprimir", hi: "प्रिंट", cat: "Aktionen", icon: "🖨️" },
  { char: "打折", pinyin: "dǎzhé", de: "Sale", en: "discount", es: "descuento", hi: "छूट", cat: "Aktionen", icon: "🏷️" },
  { char: "大概", pinyin: "dàgài", de: "Vielleicht", en: "probably", es: "probablemente", hi: "शायद", cat: "Adverb", icon: "🤷" },
  { char: "大使馆", pinyin: "dàshǐguǎn", de: "Botschaft", en: "embassy", es: "embajada", hi: "दूतावास", cat: "Orte", icon: "🏛️" },
  { char: "导游", pinyin: "dǎoyóu", de: "Guide", en: "guide", es: "guía", hi: "टूर गाइड", cat: "Personen", icon: "🚩" },
  { char: "道歉", pinyin: "dàoqiàn", de: "Sorry", en: "apologize", es: "disculparse", hi: "माफ़ी माँगना", cat: "Aktionen", icon: "🙏" },
  { char: "地球", pinyin: "dìqiú", de: "Erde", en: "earth", es: "tierra", hi: "पृथ्वी", cat: "Natur", icon: "🌏" },
  { char: "地址", pinyin: "dìzhǐ", de: "Adr.", en: "address", es: "dirección", hi: "पता", cat: "Dinge", icon: "🏠" },
  { char: "掉", pinyin: "diào", de: "Fall", en: "fall", es: "caer", hi: "गिरना", cat: "Aktionen", icon: "🍂" },
  { char: "丢", pinyin: "diū", de: "Weg", en: "lose", es: "perder", hi: "खोना", cat: "Verben", icon: "🤷" },
  { char: "动作", pinyin: "dòngzuò", de: "Move", en: "action", es: "acción", hi: "हरकत", cat: "Dinge", icon: "💃" },
  { char: "堵车", pinyin: "dǔchē", de: "Stau", en: "jam", es: "atasco", hi: "ट्रैफ़िक जाम", cat: "Verkehr", icon: "🚗" },
  { char: "发展", pinyin: "fāzhǎn", de: "Grow", en: "develop", es: "desarrollar", hi: "विकास", cat: "Geist", icon: "📈" },
  { char: "法律", pinyin: "fǎlǜ", de: "Law", en: "law", es: "ley", hi: "कानून", cat: "Dinge", icon: "⚖️" },
  { char: "翻译", pinyin: "fānyì", de: "Trans", en: "translate", es: "traducir", hi: "अनुवाद", cat: "Aktionen", icon: "🔤" },
  { char: "方法", pinyin: "fāngfǎ", de: "Weg", en: "method", es: "método", hi: "तरीका", cat: "Geist", icon: "💡" },
  { char: "方向", pinyin: "fāngxiàng", de: "Kurs", en: "direction", es: "dirección", hi: "दिशा", cat: "Richtungen", icon: "🧭" },
  { char: "放弃", pinyin: "fàngqì", de: "Quit", en: "give up", es: "rendirse", hi: "छोड़ना", cat: "Verben", icon: "🏳️" },
  { char: "放松", pinyin: "fàngsōng", de: "Chill", en: "relax", es: "relajarse", hi: "आराम करना", cat: "Emotion", icon: "😌" },
  { char: "丰富", pinyin: "fēngfù", de: "Voll", en: "rich", es: "rico", hi: "समृद्ध", cat: "Adjektive", icon: "🌈" },
  { char: "付款", pinyin: "fùkuǎn", de: "Pay", en: "pay", es: "pagar", hi: "भुगतान", cat: "Aktionen", icon: "💳" },
  { char: "负责", pinyin: "fùzé", de: "Chef", en: "responsible", es: "responsable", hi: "ज़िम्मेदार", cat: "Verben", icon: "🫡" },
  { char: "复杂", pinyin: "fùzá", de: "Wirr", en: "complex", es: "complejo", hi: "जटिल", cat: "Adjektive", icon: "🌀" },
  { char: "改变", pinyin: "gǎibiàn", de: "Change", en: "change", es: "cambiar", hi: "बदलना", cat: "Verben", icon: "🔄" },
  { char: "干杯", pinyin: "gānbēi", de: "Prost", en: "cheers", es: "salud", hi: "चीयर्स", cat: "Aktionen", icon: "🍻" },
  { char: "感动", pinyin: "gǎndòng", de: "Move", en: "moved", es: "conmovido", hi: "प्रभावित", cat: "Emotion", icon: "🥺" },
  { char: "感情", pinyin: "gǎnqíng", de: "Liebe", en: "emotion", es: "emoción", hi: "भावना", cat: "Emotion", icon: "❤️" },
  { char: "感谢", pinyin: "gǎnxiè", de: "Dank", en: "thank", es: "agradecer", hi: "धन्यवाद", cat: "Aktionen", icon: "🙏" },
  { char: "高速公路", pinyin: "gāosù gōnglù", de: "Bahn", en: "highway", es: "autopista", hi: "हाईवे", cat: "Verkehr", icon: "🛣️" },
  { char: "工资", pinyin: "gōngzī", de: "Cash", en: "salary", es: "salario", hi: "वेतन", cat: "Dinge", icon: "💵" },
  { char: "功夫", pinyin: "gōngfu", de: "Kung Fu", en: "kung fu", es: "kung fu", hi: "कुंग फू", cat: "Sport", icon: "🥋" },
  { char: "购物", pinyin: "gòuwù", de: "Shop", en: "shop", es: "compras", hi: "खरीदारी", cat: "Aktionen", icon: "🛍️" },
  { char: "够", pinyin: "gòu", de: "Voll", en: "enough", es: "suficiente", hi: "काफ़ी", cat: "Adjektive", icon: "👌" },
  { char: "鼓励", pinyin: "gǔlì", de: "Mut", en: "encourage", es: "animar", hi: "प्रोत्साहन", cat: "Aktionen", icon: "👏" },
  { char: "顾客", pinyin: "gùkè", de: "User", en: "customer", es: "cliente", hi: "ग्राहक", cat: "Personen", icon: "🛒" },
  { char: "关键", pinyin: "guānjiàn", de: "Key", en: "key", es: "clave", hi: "मुख्य", cat: "Geist", icon: "🔑" },
  { char: "管理", pinyin: "guǎnlǐ", de: "Chef", en: "manage", es: "gestionar", hi: "प्रबंधन", cat: "Aktionen", icon: "👔" },
  { char: "广告", pinyin: "guǎnggào", de: "Ad", en: "ad", es: "anuncio", hi: "विज्ञापन", cat: "Dinge", icon: "📢" },
  { char: "规定", pinyin: "guīdìng", de: "Regel", en: "rule", es: "regla", hi: "नियम", cat: "Geist", icon: "📜" },
  { char: "国际", pinyin: "guójì", de: "Welt", en: "international", es: "internacional", hi: "अंतर्राष्ट्रीय", cat: "Adjektive", icon: "🌐" },
  { char: "果汁", pinyin: "guǒzhī", de: "Saft", en: "juice", es: "zumo", hi: "जूस", cat: "Essen", icon: "🧃" },
  { char: "海洋", pinyin: "hǎiyáng", de: "Meer", en: "ocean", es: "océano", hi: "समुद्र", cat: "Natur", icon: "🌊" },
  { char: "害羞", pinyin: "hàixiū", de: "Scheu", en: "shy", es: "tímido", hi: "शर्मीला", cat: "Emotion", icon: "😳" },
  { char: "航班", pinyin: "hángbān", de: "Flug", en: "flight", es: "vuelo", hi: "उड़ान", cat: "Verkehr", icon: "🛫" },
  { char: "好像", pinyin: "hǎoxiàng", de: "Gleich", en: "seem", es: "parecer", hi: "लगता है", cat: "Verben", icon: "🤔" },
  { char: "号码", pinyin: "hàomǎ", de: "Nr.", en: "number", es: "número", hi: "नंबर", cat: "Dinge", icon: "🔢" },
  { char: "合格", pinyin: "hégé", de: "Gut", en: "qualified", es: "apto", hi: "योग्य", cat: "Adjektive", icon: "✅" },
  { char: "合适", pinyin: "héshì", de: "Passt", en: "fit", es: "adecuado", hi: "उचित", cat: "Adjektive", icon: "👌" },
  { char: "后悔", pinyin: "hòuhuǐ", de: "Reue", en: "regret", es: "arrepentirse", hi: "पछतावा", cat: "Emotion", icon: "😞" },
  { char: "互联网", pinyin: "hùliánwǎng", de: "Web", en: "internet", es: "internet", hi: "इंटरनेट", cat: "Dinge", icon: "🌐" },
  { char: "护士", pinyin: "hùshi", de: "Schwester", en: "nurse", es: "enfermera", hi: "नर्स", cat: "Personen", icon: "👩‍⚕️" },
  { char: "回忆", pinyin: "huíyì", de: "Memo", en: "memory", es: "recuerdo", hi: "यादें", cat: "Geist", icon: "💭" },
  { char: "活泼", pinyin: "huópo", de: "Aktiv", en: "lively", es: "vivo", hi: "चंचल", cat: "Adjektive", icon: "🐇" },
  { char: "获得", pinyin: "huòdé", de: "Sieg", en: "obtain", es: "obtener", hi: "प्राप्त करना", cat: "Verben", icon: "🏆" },
  { char: "基础", pinyin: "jīchǔ", de: "Basis", en: "base", es: "base", hi: "आधार", cat: "Geist", icon: "🏗️" },
  { char: "激动", pinyin: "jīdòng", de: "Aufgeregt", en: "excited", es: "emocionado", hi: "उत्साहित", cat: "Emotion", icon: "🤩" },
  { char: "即使", pinyin: "jíshǐ", de: "Auch wenn", en: "even if", es: "aunque", hi: "भले ही", cat: "Grammatik", icon: "🛤️" },
  { char: "计划", pinyin: "jìhuà", de: "Plan", en: "plan", es: "plan", hi: "योजना", cat: "Geist", icon: "📅" },
  { char: "记者", pinyin: "jìzhě", de: "Reporter", en: "journalist", es: "periodista", hi: "पत्रकार", cat: "Personen", icon: "🎤" },
  { char: "既然", pinyin: "jìrán", de: "Da", en: "since", es: "ya que", hi: "चूँकि", cat: "Grammatik", icon: "💁" },
  { char: "寄", pinyin: "jì", de: "Senden", en: "mail", es: "enviar", hi: "भेजना", cat: "Aktionen", icon: "📮" },
  { char: "加油站", pinyin: "jiāyóuzhàn", de: "Tankstelle", en: "gas station", es: "gasolinera", hi: "पेट्रोल पंप", cat: "Orte", icon: "⛽" },
  { char: "家具", pinyin: "jiājù", de: "Möbel", en: "furniture", es: "muebles", hi: "फ़र्नीचर", cat: "Dinge", icon: "🪑" },
  { char: "价格", pinyin: "jiàgé", de: "Preis", en: "price", es: "precio", hi: "क़ीमत", cat: "Dinge", icon: "🏷️" },
  { char: "坚持", pinyin: "jiānchí", de: "Durchhalten", en: "persist", es: "insistir", hi: "दृढ़ रहना", cat: "Verben", icon: "✊" },
  { char: "减肥", pinyin: "jiǎnféi", de: "Abnehmen", en: "lose weight", es: "adelgazar", hi: "वज़न कम करना", cat: "Aktionen", icon: "🥗" },
  { char: "减少", pinyin: "jiǎnshǎo", de: "Reduzieren", en: "reduce", es: "reducir", hi: "कम करना", cat: "Verben", icon: "📉" },
  { char: "建议", pinyin: "jiànyì", de: "Vorschlag", en: "suggest", es: "sugerir", hi: "सुझाव", cat: "Verben", icon: "💡" },
  { char: "将来", pinyin: "jiānglái", de: "Zukunft", en: "future", es: "futuro", hi: "भविष्य", cat: "Zeit", icon: "🔮" },
  { char: "奖金", pinyin: "jiǎngjīn", de: "Bonus", en: "bonus", es: "bonificación", hi: "बोनस", cat: "Geld", icon: "💵" },
  { char: "交通", pinyin: "jiāotōng", de: "Verkehr", en: "traffic", es: "tráfico", hi: "यातायात", cat: "Verkehr", icon: "🚦" },
  { char: "交流", pinyin: "jiāoliú", de: "Austausch", en: "exchange", es: "intercambio", hi: "आदान-प्रदान", cat: "Verben", icon: "🗣️" },
  { char: "教授", pinyin: "jiàoshòu", de: "Professor", en: "professor", es: "profesor", hi: "प्रोफ़ेसर", cat: "Personen", icon: "👨‍🏫" },
  { char: "教育", pinyin: "jiàoyù", de: "Bildung", en: "education", es: "educación", hi: "शिक्षा", cat: "Schule", icon: "🏫" },
  { char: "接受", pinyin: "jiēshòu", de: "Akzeptieren", en: "accept", es: "aceptar", hi: "स्वीकार करना", cat: "Verben", icon: "✅" },
  { char: "结果", pinyin: "jiéguǒ", de: "Ergebnis", en: "result", es: "resultado", hi: "नतीजा", cat: "Geist", icon: "📊" },
  { char: "节约", pinyin: "jiéyuē", de: "Sparen", en: "save", es: "ahorrar", hi: "बचत", cat: "Verben", icon: "🐷" },
  { char: "解释", pinyin: "jiěshì", de: "Erklären", en: "explain", es: "explicar", hi: "समझाना", cat: "Verben", icon: "💬" },
  { char: "紧张", pinyin: "jǐnzhāng", de: "Nervös", en: "nervous", es: "nervioso", hi: "तनाव", cat: "Emotion", icon: "😬" },
  { char: "尽管", pinyin: "jǐnguǎn", de: "Obwohl", en: "although", es: "aunque", hi: "हालाँकि", cat: "Grammatik", icon: "⚖️" },
  { char: "进行", pinyin: "jìnxíng", de: "Durchführen", en: "carry out", es: "realizar", hi: "आयोजित करना", cat: "Verben", icon: "▶️" },
  { char: "禁止", pinyin: "jìnzhǐ", de: "Verbieten", en: "prohibit", es: "prohibir", hi: "मना", cat: "Verben", icon: "🚫" },
  { char: "精彩", pinyin: "jīngcǎi", de: "Wunderbar", en: "wonderful", es: "maravilloso", hi: "शानदार", cat: "Adjektive", icon: "✨" },
  { char: "经济", pinyin: "jīngjì", de: "Wirtschaft", en: "economy", es: "economía", hi: "अर्थव्यवस्था", cat: "Geist", icon: "📈" },
  { char: "经验", pinyin: "jīngyàn", de: "Erfahrung", en: "experience", es: "experiencia", hi: "अनुभव", cat: "Geist", icon: "🧠" },
  { char: "警察", pinyin: "jǐngchá", de: "Polizei", en: "police", es: "policía", hi: "पुलिस", cat: "Personen", icon: "👮" },
  { char: "竞争", pinyin: "jìngzhēng", de: "Wettkampf", en: "compete", es: "competir", hi: "प्रतिस्पर्धा", cat: "Verben", icon: "🏆" },
  { char: "镜子", pinyin: "jìngzi", de: "Spiegel", en: "mirror", es: "espejo", hi: "आईना", cat: "Dinge", icon: "🪞" },
  { char: "究竟", pinyin: "jiūjìng", de: "Eigentlich", en: "actually", es: "en realidad", hi: "आखिर", cat: "Adverb", icon: "🤔" },
  { char: "举办", pinyin: "jǔbàn", de: "Veranstalten", en: "hold", es: "organizar", hi: "आयोजित करना", cat: "Aktionen", icon: "🎉" },
  { char: "拒绝", pinyin: "jùjué", de: "Ablehnen", en: "refuse", es: "rechazar", hi: "इनकार", cat: "Verben", icon: "🙅" },
  { char: "距离", pinyin: "jùlí", de: "Entfernung", en: "distance", es: "distancia", hi: "दूरी", cat: "Maße", icon: "📏" },
  { char: "聚会", pinyin: "jùhuì", de: "Party", en: "party", es: "fiesta", hi: "पार्टी", cat: "Aktionen", icon: "🎊" },
  { char: "卡", pinyin: "kǎ", de: "Karte", en: "card", es: "tarjeta", hi: "कार्ड", cat: "Dinge", icon: "💳" },
  { char: "开玩笑", pinyin: "kāiwánxiào", de: "Scherzen", en: "joke", es: "bromear", hi: "मज़ाक करना", cat: "Verben", icon: "😄" },
  { char: "看法", pinyin: "kànfǎ", de: "Ansicht", en: "view", es: "opinión", hi: "विचार", cat: "Geist", icon: "👀" },
  { char: "考虑", pinyin: "kǎolǜ", de: "Überlegen", en: "consider", es: "considerar", hi: "सोचना", cat: "Geist", icon: "🤔" },
  { char: "科学", pinyin: "kēxué", de: "Wissenschaft", en: "science", es: "ciencia", hi: "विज्ञान", cat: "Schule", icon: "🔬" },
  { char: "可怜", pinyin: "kělián", de: "Arm", en: "pitiful", es: "pobre", hi: "बेचारा", cat: "Adjektive", icon: "🥺" },
  { char: "可惜", pinyin: "kěxī", de: "Schade", en: "pity", es: "lástima", hi: "अफ़सोस", cat: "Adjektive", icon: "😢" },
  { char: "客厅", pinyin: "kètīng", de: "Wohnzimmer", en: "living room", es: "salón", hi: "लिविंग रूम", cat: "Orte", icon: "🛋️" },
  { char: "肯定", pinyin: "kěndìng", de: "Sicher", en: "certain", es: "seguro", hi: "निश्चित", cat: "Adverb", icon: "💯" },
  { char: "空", pinyin: "kōng", de: "Leer", en: "empty", es: "vacío", hi: "खाली", cat: "Adjektive", icon: "🈳" },
  { char: "恐怕", pinyin: "kǒngpà", de: "Befürchten", en: "afraid", es: "temer", hi: "शायद", cat: "Adverb", icon: "😰" },
  { char: "苦", pinyin: "kǔ", de: "Bitter", en: "bitter", es: "amargo", hi: "कड़वा", cat: "Essen", icon: "😖" },
  { char: "矿泉水", pinyin: "kuàngquánshuǐ", de: "Mineralwasser", en: "mineral water", es: "agua mineral", hi: "मिनरल वाटर", cat: "Essen", icon: "💧" },
  { char: "困", pinyin: "kùn", de: "Schläfrig", en: "sleepy", es: "soñoliento", hi: "नींद आना", cat: "Gefühle", icon: "😴" },
  { char: "困难", pinyin: "kùnnán", de: "Schwierigkeit", en: "difficulty", es: "dificultad", hi: "कठिनाई", cat: "Geist", icon: "🧗" },
  { char: "拉", pinyin: "lā", de: "Ziehen", en: "pull", es: "tirar", hi: "खींचना", cat: "Aktionen", icon: "🤚" },
  { char: "垃圾桶", pinyin: "lājītǒng", de: "Mülleimer", en: "trash can", es: "papelera", hi: "कूड़ेदान", cat: "Dinge", icon: "🗑️" },
  { char: "辣", pinyin: "là", de: "Scharf", en: "spicy", es: "picante", hi: "मसालेदार", cat: "Essen", icon: "🌶️" },
  { char: "来自", pinyin: "láizì", de: "Kommen aus", en: "come from", es: "venir de", hi: "से आना", cat: "Verben", icon: "🌍" },
  { char: "来得及", pinyin: "láidejí", de: "Rechtzeitig", en: "in time", es: "a tiempo", hi: "समय पर", cat: "Zeit", icon: "⏰" },
  { char: "浪费", pinyin: "làngfèi", de: "Verschwenden", en: "waste", es: "desperdiciar", hi: "बर्बाद", cat: "Verben", icon: "🗑️" },
  { char: "浪漫", pinyin: "làngmàn", de: "Romantisch", en: "romantic", es: "romántico", hi: "रोमांटिक", cat: "Adjektive", icon: "🌹" },
  { char: "老虎", pinyin: "lǎohǔ", de: "Tiger", en: "tiger", es: "tigre", hi: "बाघ", cat: "Natur", icon: "🐅" },
  { char: "冷静", pinyin: "lěngjìng", de: "Ruhig", en: "calm", es: "calmado", hi: "शांत", cat: "Adjektive", icon: "🧊" },
  { char: "理发", pinyin: "lǐfà", de: "Friseur", en: "haircut", es: "corte de pelo", hi: "बाल कटवाना", cat: "Aktionen", icon: "💇" },
  { char: "理解", pinyin: "lǐjiě", de: "Verstehen", en: "understand", es: "entender", hi: "समझना", cat: "Geist", icon: "💡" },
  { char: "理想", pinyin: "lǐxiǎng", de: "Ideal", en: "ideal", es: "ideal", hi: "आदर्श", cat: "Geist", icon: "✨" },
  { char: "力气", pinyin: "lìqi", de: "Kraft", en: "strength", es: "fuerza", hi: "ताक़त", cat: "Mensch", icon: "💪" },
  { char: "厉害", pinyin: "lìhai", de: "Beeindruckend", en: "awesome", es: "impresionante", hi: "कमाल", cat: "Adjektive", icon: "🔥" },
  { char: "例如", pinyin: "lìrú", de: "Zum Beispiel", en: "for example", es: "por ejemplo", hi: "उदाहरण के लिए", cat: "Grammatik", icon: "📝" },
  { char: "联系", pinyin: "liánxì", de: "Kontakt", en: "contact", es: "contacto", hi: "संपर्क", cat: "Aktionen", icon: "📞" },
  { char: "凉快", pinyin: "liángkuai", de: "Kühl", en: "cool", es: "fresco", hi: "ठंडा", cat: "Wetter", icon: "🌬️" },
  { char: "聊天", pinyin: "liáotiān", de: "Plaudern", en: "chat", es: "charlar", hi: "बातचीत", cat: "Verben", icon: "💬" },
  { char: "另外", pinyin: "lìngwài", de: "Außerdem", en: "besides", es: "además", hi: "इसके अलावा", cat: "Grammatik", icon: "➕" },
  { char: "留", pinyin: "liú", de: "Bleiben", en: "stay", es: "quedarse", hi: "रहना", cat: "Verben", icon: "🏠" },
  { char: "流利", pinyin: "liúlì", de: "Fließend", en: "fluent", es: "fluido", hi: "धाराप्रवाह", cat: "Adjektive", icon: "🗣️" },
  { char: "流行", pinyin: "liúxíng", de: "Beliebt", en: "popular", es: "popular", hi: "लोकप्रिय", cat: "Adjektive", icon: "📈" },
  { char: "旅行", pinyin: "lǚxíng", de: "Reise", en: "travel", es: "viaje", hi: "यात्रा", cat: "Hobby", icon: "✈️" },
  { char: "律师", pinyin: "lǜshī", de: "Anwalt", en: "lawyer", es: "abogado", hi: "वकील", cat: "Personen", icon: "⚖️" },
  { char: "麻烦", pinyin: "máfan", de: "Ärger", en: "trouble", es: "molestia", hi: "परेशानी", cat: "Adjektive", icon: "😫" },
  { char: "满", pinyin: "mǎn", de: "Voll", en: "full", es: "lleno", hi: "भरा हुआ", cat: "Adjektive", icon: "🈵" },
  { char: "毛巾", pinyin: "máojīn", de: "Handtuch", en: "towel", es: "toalla", hi: "तौलिया", cat: "Dinge", icon: "🧴" },
  { char: "美丽", pinyin: "měilì", de: "Schön", en: "beautiful", es: "hermoso", hi: "सुंदर", cat: "Adjektive", icon: "🌸" },
  { char: "梦", pinyin: "mèng", de: "Traum", en: "dream", es: "sueño", hi: "सपना", cat: "Geist", icon: "💭" },
  { char: "密码", pinyin: "mìmǎ", de: "Passwort", en: "password", es: "contraseña", hi: "पासवर्ड", cat: "Dinge", icon: "🔐" },
  { char: "免费", pinyin: "miǎnfèi", de: "Kostenlos", en: "free", es: "gratis", hi: "मुफ़्त", cat: "Adjektive", icon: "🆓" },
  { char: "秒", pinyin: "miǎo", de: "Sekunde", en: "second", es: "segundo", hi: "सेकंड", cat: "Zeit", icon: "⏱️" },
  { char: "民族", pinyin: "mínzú", de: "Nation", en: "nation", es: "nación", hi: "राष्ट्र", cat: "Geist", icon: "🏳️" },
  { char: "母亲", pinyin: "mǔqīn", de: "Mutter", en: "mother", es: "madre", hi: "माँ", cat: "Personen", icon: "👩" },
  { char: "目的", pinyin: "mùdì", de: "Ziel", en: "purpose", es: "propósito", hi: "उद्देश्य", cat: "Geist", icon: "🎯" },
  { char: "内", pinyin: "nèi", de: "Innen", en: "inside", es: "dentro", hi: "अंदर", cat: "Richtungen", icon: "📥" },
  { char: "内容", pinyin: "nèiróng", de: "Inhalt", en: "content", es: "contenido", hi: "सामग्री", cat: "Dinge", icon: "📦" },
  { char: "耐心", pinyin: "nàixīn", de: "Geduld", en: "patience", es: "paciencia", hi: "धैर्य", cat: "Emotion", icon: "🧘" },
  { char: "难道", pinyin: "nándào", de: "Etwa", en: "could it be", es: "acaso", hi: "क्या", cat: "Grammatik", icon: "❓" },
  { char: "难受", pinyin: "nánshòu", de: "Unwohl", en: "uncomfortable", es: "incómodo", hi: "असहज", cat: "Gefühle", icon: "😣" },
  { char: "能力", pinyin: "nénglì", de: "Fähigkeit", en: "ability", es: "habilidad", hi: "क्षमता", cat: "Geist", icon: "💪" },
  { char: "弄", pinyin: "nòng", de: "Machen", en: "do", es: "hacer", hi: "करना", cat: "Verben", icon: "🔨" },
  { char: "暖和", pinyin: "nuǎnhuo", de: "Warm", en: "warm", es: "cálido", hi: "गर्म", cat: "Wetter", icon: "☀️" },
  { char: "偶尔", pinyin: "ǒuěr", de: "Gelegentlich", en: "occasionally", es: "ocasionalmente", hi: "कभी-कभी", cat: "Adverb", icon: "🎲" },
  { char: "排列", pinyin: "páiliè", de: "Anordnen", en: "arrange", es: "ordenar", hi: "व्यवस्थित करना", cat: "Verben", icon: "📊" },
  { char: "判断", pinyin: "pànduàn", de: "Urteilen", en: "judge", es: "juzgar", hi: "निर्णय", cat: "Geist", icon: "⚖️" },
  { char: "陪", pinyin: "péi", de: "Begleiten", en: "accompany", es: "acompañar", hi: "साथ देना", cat: "Verben", icon: "👫" },
  { char: "批评", pinyin: "pīpíng", de: "Kritisieren", en: "criticize", es: "criticar", hi: "आलोचना", cat: "Verben", icon: "👎" },
  { char: "皮肤", pinyin: "pífū", de: "Haut", en: "skin", es: "piel", hi: "त्वचा", cat: "Mensch", icon: "🖐️" },
  { char: "脾气", pinyin: "píqi", de: "Temperament", en: "temper", es: "temperamento", hi: "स्वभाव", cat: "Emotion", icon: "😤" },
  { char: "平时", pinyin: "píngshí", de: "Normalerweise", en: "usually", es: "normalmente", hi: "आमतौर पर", cat: "Zeit", icon: "📅" },
  { char: "破", pinyin: "pò", de: "Kaputt", en: "broken", es: "roto", hi: "टूटा", cat: "Adjektive", icon: "💔" },
  { char: "普遍", pinyin: "pǔbiàn", de: "Allgemein", en: "common", es: "común", hi: "सामान्य", cat: "Adjektive", icon: "🌐" },
  { char: "普通话", pinyin: "pǔtōnghuà", de: "Mandarin", en: "Mandarin", es: "mandarín", hi: "मंदारिन", cat: "Sprache", icon: "🗣️" },
  { char: "其次", pinyin: "qícì", de: "Zweitens", en: "secondly", es: "en segundo lugar", hi: "दूसरे", cat: "Grammatik", icon: "2️⃣" },
  { char: "其中", pinyin: "qízhōng", de: "Darunter", en: "among", es: "entre", hi: "इनमें से", cat: "Grammatik", icon: "📍" },
  { char: "气候", pinyin: "qìhòu", de: "Klima", en: "climate", es: "clima", hi: "जलवायु", cat: "Wetter", icon: "🌤️" },
  { char: "千万", pinyin: "qiānwàn", de: "Unbedingt", en: "must", es: "absolutamente", hi: "ज़रूर", cat: "Adverb", icon: "⚠️" },
  { char: "签证", pinyin: "qiānzhèng", de: "Visum", en: "visa", es: "visa", hi: "वीज़ा", cat: "Dinge", icon: "🛂" },
  { char: "墙", pinyin: "qiáng", de: "Mauer", en: "wall", es: "pared", hi: "दीवार", cat: "Dinge", icon: "🧱" },
  { char: "敲", pinyin: "qiāo", de: "Klopfen", en: "knock", es: "golpear", hi: "खटखटाना", cat: "Verben", icon: "✊" },
  { char: "桥", pinyin: "qiáo", de: "Brücke", en: "bridge", es: "puente", hi: "पुल", cat: "Orte", icon: "🌉" },
  { char: "巧克力", pinyin: "qiǎokèlì", de: "Schokolade", en: "chocolate", es: "chocolate", hi: "चॉकलेट", cat: "Essen", icon: "🍫" },
  { char: "亲戚", pinyin: "qīnqi", de: "Verwandter", en: "relative", es: "pariente", hi: "रिश्तेदार", cat: "Personen", icon: "👨‍👩‍👧" },
  { char: "轻", pinyin: "qīng", de: "Leicht", en: "light", es: "ligero", hi: "हल्का", cat: "Adjektive", icon: "🪶" },
  { char: "轻松", pinyin: "qīngsōng", de: "Entspannt", en: "relaxed", es: "relajado", hi: "आरामदायक", cat: "Emotion", icon: "😌" },
  { char: "情况", pinyin: "qíngkuàng", de: "Situation", en: "situation", es: "situación", hi: "स्थिति", cat: "Dinge", icon: "📋" },
  { char: "请假", pinyin: "qǐngjià", de: "Urlaub nehmen", en: "ask for leave", es: "pedir permiso", hi: "छुट्टी लेना", cat: "Aktionen", icon: "🏖️" },
  { char: "请客", pinyin: "qǐngkè", de: "Einladen", en: "treat", es: "invitar", hi: "दावत देना", cat: "Aktionen", icon: "🍽️" },
  { char: "穷", pinyin: "qióng", de: "Arm", en: "poor", es: "pobre", hi: "ग़रीब", cat: "Adjektive", icon: "💸" },
  { char: "取", pinyin: "qǔ", de: "Nehmen", en: "take", es: "tomar", hi: "लेना", cat: "Verben", icon: "✋" },
  { char: "全部", pinyin: "quánbù", de: "Gesamt", en: "all", es: "todo", hi: "सभी", cat: "Grammatik", icon: "💯" },
  { char: "缺点", pinyin: "quēdiǎn", de: "Schwäche", en: "weakness", es: "defecto", hi: "कमी", cat: "Geist", icon: "❌" },
  { char: "缺少", pinyin: "quēshǎo", de: "Mangel", en: "lack", es: "faltar", hi: "कमी होना", cat: "Verben", icon: "📉" },
  { char: "却", pinyin: "què", de: "Jedoch", en: "but", es: "sin embargo", hi: "लेकिन", cat: "Grammatik", icon: "↩️" },
  { char: "确实", pinyin: "quèshí", de: "Tatsächlich", en: "indeed", es: "de hecho", hi: "वास्तव में", cat: "Adverb", icon: "✅" },
  { char: "然而", pinyin: "ránér", de: "Jedoch", en: "however", es: "sin embargo", hi: "हालाँकि", cat: "Grammatik", icon: "🔄" },
  { char: "热闹", pinyin: "rènao", de: "Lebhaft", en: "lively", es: "animado", hi: "रौनक", cat: "Adjektive", icon: "🎉" },
  { char: "任何", pinyin: "rènhé", de: "Jeder", en: "any", es: "cualquier", hi: "कोई भी", cat: "Grammatik", icon: "🔄" },
  { char: "任务", pinyin: "rènwu", de: "Aufgabe", en: "task", es: "tarea", hi: "कार्य", cat: "Dinge", icon: "📋" },
  { char: "日记", pinyin: "rìjì", de: "Tagebuch", en: "diary", es: "diario", hi: "डायरी", cat: "Dinge", icon: "📔" },
  { char: "入口", pinyin: "rùkǒu", de: "Eingang", en: "entrance", es: "entrada", hi: "प्रवेश", cat: "Richtungen", icon: "🚪" },
  { char: "散步", pinyin: "sànbù", de: "Spazieren", en: "walk", es: "pasear", hi: "टहलना", cat: "Hobby", icon: "🚶" },
  { char: "森林", pinyin: "sēnlín", de: "Wald", en: "forest", es: "bosque", hi: "जंगल", cat: "Natur", icon: "🌲" },
  { char: "沙发", pinyin: "shāfā", de: "Sofa", en: "sofa", es: "sofá", hi: "सोफ़ा", cat: "Dinge", icon: "🛋️" },
  { char: "伤心", pinyin: "shāngxīn", de: "Traurig", en: "sad", es: "triste", hi: "दुखी", cat: "Emotion", icon: "💔" },
  { char: "商量", pinyin: "shāngliang", de: "Beraten", en: "discuss", es: "discutir", hi: "सलाह करना", cat: "Verben", icon: "💬" },
  { char: "稍微", pinyin: "shāowēi", de: "Etwas", en: "slightly", es: "un poco", hi: "थोड़ा", cat: "Adverb", icon: "🤏" },
  { char: "勺子", pinyin: "sháozi", de: "Löffel", en: "spoon", es: "cuchara", hi: "चम्मच", cat: "Dinge", icon: "🥄" },
  { char: "社会", pinyin: "shèhuì", de: "Gesellschaft", en: "society", es: "sociedad", hi: "समाज", cat: "Geist", icon: "👥" },
  { char: "申请", pinyin: "shēnqǐng", de: "Beantragen", en: "apply", es: "solicitar", hi: "आवेदन", cat: "Aktionen", icon: "📝" },
  { char: "甚至", pinyin: "shènzhì", de: "Sogar", en: "even", es: "incluso", hi: "यहाँ तक कि", cat: "Grammatik", icon: "⬆️" },
  { char: "生活", pinyin: "shēnghuó", de: "Leben", en: "life", es: "vida", hi: "जीवन", cat: "Geist", icon: "🌱" },
  { char: "生意", pinyin: "shēngyì", de: "Geschäft", en: "business", es: "negocio", hi: "व्यापार", cat: "Dinge", icon: "💼" },
  { char: "省", pinyin: "shěng", de: "Sparen", en: "save", es: "ahorrar", hi: "बचाना", cat: "Verben", icon: "💰" },
  { char: "剩", pinyin: "shèng", de: "Übrig", en: "leftover", es: "sobrante", hi: "बचा हुआ", cat: "Verben", icon: "📦" },
  { char: "失败", pinyin: "shībài", de: "Scheitern", en: "fail", es: "fracasar", hi: "असफलता", cat: "Verben", icon: "❌" },
  { char: "失望", pinyin: "shīwàng", de: "Enttäuscht", en: "disappointed", es: "decepcionado", hi: "निराश", cat: "Emotion", icon: "😞" },
  { char: "师傅", pinyin: "shīfu", de: "Meister", en: "master", es: "maestro", hi: "उस्ताद", cat: "Personen", icon: "👨‍🏫" },
  { char: "十分", pinyin: "shífēn", de: "Sehr", en: "very", es: "muy", hi: "बहुत", cat: "Adverb", icon: "💯" },
  { char: "实际", pinyin: "shíjì", de: "Praktisch", en: "practical", es: "práctico", hi: "वास्तविक", cat: "Adjektive", icon: "🔧" },
  { char: "实在", pinyin: "shízài", de: "Wirklich", en: "really", es: "realmente", hi: "सच में", cat: "Adverb", icon: "✅" },
  { char: "使", pinyin: "shǐ", de: "Veranlassen", en: "make", es: "hacer", hi: "करवाना", cat: "Verben", icon: "➡️" },
  { char: "使用", pinyin: "shǐyòng", de: "Benutzen", en: "use", es: "usar", hi: "इस्तेमाल", cat: "Verben", icon: "🔧" },
  { char: "世纪", pinyin: "shìjì", de: "Jahrhundert", en: "century", es: "siglo", hi: "शताब्दी", cat: "Zeit", icon: "📅" },
  { char: "适合", pinyin: "shìhé", de: "Passen", en: "suit", es: "adecuado", hi: "उपयुक्त", cat: "Verben", icon: "👌" },
  { char: "适应", pinyin: "shìyìng", de: "Anpassen", en: "adapt", es: "adaptarse", hi: "अनुकूल होना", cat: "Verben", icon: "🔄" },
  { char: "收", pinyin: "shōu", de: "Sammeln", en: "collect", es: "recoger", hi: "प्राप्त करना", cat: "Verben", icon: "📬" },
  { char: "收入", pinyin: "shōurù", de: "Einkommen", en: "income", es: "ingresos", hi: "आय", cat: "Geld", icon: "💵" },
  { char: "收拾", pinyin: "shōushi", de: "Aufräumen", en: "tidy up", es: "ordenar", hi: "साफ़ करना", cat: "Aktionen", icon: "🧹" },
  { char: "首都", pinyin: "shǒudū", de: "Hauptstadt", en: "capital", es: "capital", hi: "राजधानी", cat: "Orte", icon: "🏛️" },
  { char: "首先", pinyin: "shǒuxiān", de: "Zuerst", en: "first", es: "primero", hi: "पहले", cat: "Grammatik", icon: "1️⃣" },
  { char: "受不了", pinyin: "shòubuliǎo", de: "Unerträglich", en: "unbearable", es: "insoportable", hi: "बर्दाश्त नहीं", cat: "Emotion", icon: "😫" },
  { char: "受到", pinyin: "shòudào", de: "Erhalten", en: "receive", es: "recibir", hi: "प्राप्त करना", cat: "Verben", icon: "📩" },
  { char: "售货员", pinyin: "shòuhuòyuán", de: "Verkäufer", en: "salesperson", es: "vendedor", hi: "विक्रेता", cat: "Personen", icon: "🛒" },
  { char: "输", pinyin: "shū", de: "Verlieren", en: "lose", es: "perder", hi: "हारना", cat: "Verben", icon: "😔" },
  { char: "熟悉", pinyin: "shúxī", de: "Vertraut", en: "familiar", es: "familiar", hi: "परिचित", cat: "Adjektive", icon: "🤝" },
  { char: "数量", pinyin: "shùliàng", de: "Menge", en: "quantity", es: "cantidad", hi: "मात्रा", cat: "Maße", icon: "🔢" },
  { char: "数字", pinyin: "shùzì", de: "Zahl", en: "number", es: "número", hi: "अंक", cat: "Zahlen", icon: "🔢" },
  { char: "帅", pinyin: "shuài", de: "Hübsch", en: "handsome", es: "guapo", hi: "सुंदर", cat: "Adjektive", icon: "😎" },
  { char: "顺便", pinyin: "shùnbiàn", de: "Nebenbei", en: "by the way", es: "de paso", hi: "रास्ते में", cat: "Adverb", icon: "➡️" },
  { char: "顺利", pinyin: "shùnlì", de: "Reibungslos", en: "smooth", es: "sin problemas", hi: "सुचारू", cat: "Adjektive", icon: "✅" },
  { char: "顺序", pinyin: "shùnxù", de: "Reihenfolge", en: "order", es: "orden", hi: "क्रम", cat: "Dinge", icon: "📝" },
  { char: "说明", pinyin: "shuōmíng", de: "Erklären", en: "explain", es: "explicar", hi: "समझाना", cat: "Verben", icon: "💬" },
  { char: "硕士", pinyin: "shuòshì", de: "Master", en: "master's", es: "máster", hi: "मास्टर", cat: "Schule", icon: "🎓" },
  { char: "死", pinyin: "sǐ", de: "Sterben", en: "die", es: "morir", hi: "मरना", cat: "Verben", icon: "💀" },
  { char: "速度", pinyin: "sùdù", de: "Geschwindigkeit", en: "speed", es: "velocidad", hi: "गति", cat: "Maße", icon: "⚡" },
  { char: "塑料袋", pinyin: "sùliàodài", de: "Plastiktüte", en: "plastic bag", es: "bolsa de plástico", hi: "प्लास्टिक बैग", cat: "Dinge", icon: "🛍️" },
  { char: "酸", pinyin: "suān", de: "Sauer", en: "sour", es: "ácido", hi: "खट्टा", cat: "Essen", icon: "🍋" },
  { char: "随便", pinyin: "suíbiàn", de: "Egal", en: "whatever", es: "lo que sea", hi: "कुछ भी", cat: "Adverb", icon: "🤷" },
  { char: "随着", pinyin: "suízhe", de: "Mit", en: "along with", es: "junto con", hi: "के साथ", cat: "Grammatik", icon: "➡️" },
  { char: "孙子", pinyin: "sūnzi", de: "Enkel", en: "grandson", es: "nieto", hi: "पोता", cat: "Personen", icon: "👶" },
  { char: "所有", pinyin: "suǒyǒu", de: "Alle", en: "all", es: "todos", hi: "सभी", cat: "Grammatik", icon: "💯" },
  { char: "台", pinyin: "tái", de: "Plattform", en: "platform", es: "plataforma", hi: "मंच", cat: "Dinge", icon: "🖥️" },
  { char: "抬", pinyin: "tái", de: "Heben", en: "lift", es: "levantar", hi: "उठाना", cat: "Verben", icon: "💪" },
  { char: "态度", pinyin: "tàidu", de: "Haltung", en: "attitude", es: "actitud", hi: "रवैया", cat: "Geist", icon: "🤔" },
  { char: "弹钢琴", pinyin: "tán gāngqín", de: "Klavier spielen", en: "play piano", es: "tocar piano", hi: "पियानो बजाना", cat: "Hobby", icon: "🎹" },
  { char: "谈", pinyin: "tán", de: "Reden", en: "talk", es: "hablar", hi: "बात करना", cat: "Verben", icon: "💬" },
  { char: "汤", pinyin: "tāng", de: "Suppe", en: "soup", es: "sopa", hi: "सूप", cat: "Essen", icon: "🍲" },
  { char: "糖", pinyin: "táng", de: "Zucker", en: "sugar", es: "azúcar", hi: "चीनी", cat: "Essen", icon: "🍬" },
  { char: "躺", pinyin: "tǎng", de: "Liegen", en: "lie down", es: "acostarse", hi: "लेटना", cat: "Verben", icon: "🛋️" },
  { char: "特点", pinyin: "tèdiǎn", de: "Merkmal", en: "feature", es: "característica", hi: "विशेषता", cat: "Dinge", icon: "✨" },
  { char: "提", pinyin: "tí", de: "Heben", en: "lift", es: "levantar", hi: "उठाना", cat: "Verben", icon: "🤲" },
  { char: "提高", pinyin: "tígāo", de: "Verbessern", en: "improve", es: "mejorar", hi: "बढ़ाना", cat: "Verben", icon: "📈" },
  { char: "提供", pinyin: "tígōng", de: "Bereitstellen", en: "provide", es: "proporcionar", hi: "प्रदान करना", cat: "Verben", icon: "📦" },
  { char: "提前", pinyin: "tíqián", de: "Im Voraus", en: "in advance", es: "por adelantado", hi: "पहले से", cat: "Zeit", icon: "⏰" },
  { char: "提醒", pinyin: "tíxǐng", de: "Erinnern", en: "remind", es: "recordar", hi: "याद दिलाना", cat: "Verben", icon: "🔔" },
  { char: "填", pinyin: "tián", de: "Ausfüllen", en: "fill", es: "rellenar", hi: "भरना", cat: "Verben", icon: "📝" },
  { char: "甜", pinyin: "tián", de: "Süß", en: "sweet", es: "dulce", hi: "मीठा", cat: "Essen", icon: "🍯" },
  { char: "条件", pinyin: "tiáojiàn", de: "Bedingung", en: "condition", es: "condición", hi: "शर्त", cat: "Dinge", icon: "📋" },
  { char: "停", pinyin: "tíng", de: "Stoppen", en: "stop", es: "parar", hi: "रुकना", cat: "Verben", icon: "🛑" },
  { char: "挺", pinyin: "tǐng", de: "Ziemlich", en: "quite", es: "bastante", hi: "काफ़ी", cat: "Adverb", icon: "👍" },
  { char: "通过", pinyin: "tōngguò", de: "Durch", en: "through", es: "a través de", hi: "के माध्यम से", cat: "Grammatik", icon: "➡️" },
  { char: "通知", pinyin: "tōngzhī", de: "Benachrichtigen", en: "notify", es: "notificar", hi: "सूचना", cat: "Verben", icon: "📢" },
  { char: "同情", pinyin: "tóngqíng", de: "Mitgefühl", en: "sympathy", es: "simpatía", hi: "सहानुभूति", cat: "Emotion", icon: "💕" },
  { char: "同时", pinyin: "tóngshí", de: "Gleichzeitig", en: "meanwhile", es: "al mismo tiempo", hi: "साथ में", cat: "Zeit", icon: "⏰" },
  { char: "推", pinyin: "tuī", de: "Schieben", en: "push", es: "empujar", hi: "धकेलना", cat: "Verben", icon: "👐" },
  { char: "推迟", pinyin: "tuīchí", de: "Verschieben", en: "postpone", es: "posponer", hi: "स्थगित करना", cat: "Verben", icon: "⏰" },
  { char: "脱", pinyin: "tuō", de: "Ausziehen", en: "take off", es: "quitarse", hi: "उतारना", cat: "Verben", icon: "👔" },
  { char: "袜子", pinyin: "wàzi", de: "Socken", en: "socks", es: "calcetines", hi: "मोज़े", cat: "Dinge", icon: "🧦" },
  { char: "完全", pinyin: "wánquán", de: "Vollständig", en: "completely", es: "completamente", hi: "पूरी तरह", cat: "Adverb", icon: "💯" },
  { char: "网球", pinyin: "wǎngqiú", de: "Tennis", en: "tennis", es: "tenis", hi: "टेनिस", cat: "Sport", icon: "🎾" },
  { char: "网站", pinyin: "wǎngzhàn", de: "Webseite", en: "website", es: "sitio web", hi: "वेबसाइट", cat: "Dinge", icon: "🌐" },
  { char: "往往", pinyin: "wǎngwǎng", de: "Oft", en: "often", es: "a menudo", hi: "अक्सर", cat: "Adverb", icon: "🔄" },
  { char: "危险", pinyin: "wēixiǎn", de: "Gefahr", en: "danger", es: "peligro", hi: "ख़तरा", cat: "Adjektive", icon: "⚠️" },
  { char: "味道", pinyin: "wèidao", de: "Geschmack", en: "taste", es: "sabor", hi: "स्वाद", cat: "Essen", icon: "👅" },
  { char: "温度", pinyin: "wēndù", de: "Temperatur", en: "temperature", es: "temperatura", hi: "तापमान", cat: "Wetter", icon: "🌡️" },
  { char: "文化", pinyin: "wénhuà", de: "Kultur", en: "culture", es: "cultura", hi: "संस्कृति", cat: "Kultur", icon: "🏛️" },
  { char: "污染", pinyin: "wūrǎn", de: "Verschmutzung", en: "pollution", es: "contaminación", hi: "प्रदूषण", cat: "Natur", icon: "🏭" },
  { char: "无", pinyin: "wú", de: "Ohne", en: "without", es: "sin", hi: "बिना", cat: "Grammatik", icon: "⭕" },
  { char: "无聊", pinyin: "wúliáo", de: "Langweilig", en: "boring", es: "aburrido", hi: "बोरिंग", cat: "Adjektive", icon: "😐" },
  { char: "无论", pinyin: "wúlùn", de: "Egal", en: "regardless", es: "sin importar", hi: "चाहे", cat: "Grammatik", icon: "🔄" },
  { char: "误会", pinyin: "wùhuì", de: "Missverständnis", en: "misunderstanding", es: "malentendido", hi: "ग़लतफ़हमी", cat: "Geist", icon: "❓" },
  { char: "西红柿", pinyin: "xīhóngshì", de: "Tomate", en: "tomato", es: "tomate", hi: "टमाटर", cat: "Essen", icon: "🍅" },
  { char: "吸引", pinyin: "xīyǐn", de: "Anziehen", en: "attract", es: "atraer", hi: "आकर्षित", cat: "Verben", icon: "🧲" },
  { char: "习惯", pinyin: "xíguàn", de: "Gewohnheit", en: "habit", es: "hábito", hi: "आदत", cat: "Geist", icon: "🔄" },
  { char: "戏剧", pinyin: "xìjù", de: "Drama", en: "drama", es: "drama", hi: "नाटक", cat: "Kultur", icon: "🎭" },
  { char: "细心", pinyin: "xìxīn", de: "Sorgfältig", en: "careful", es: "cuidadoso", hi: "सावधान", cat: "Adjektive", icon: "🔍" },
  { char: "下载", pinyin: "xiàzài", de: "Herunterladen", en: "download", es: "descargar", hi: "डाउनलोड", cat: "Aktionen", icon: "⬇️" },
  { char: "吓", pinyin: "xià", de: "Erschrecken", en: "scare", es: "asustar", hi: "डराना", cat: "Verben", icon: "😱" },
  { char: "先", pinyin: "xiān", de: "Zuerst", en: "first", es: "primero", hi: "पहले", cat: "Grammatik", icon: "1️⃣" },
  { char: "咸", pinyin: "xián", de: "Salzig", en: "salty", es: "salado", hi: "नमकीन", cat: "Essen", icon: "🧂" },
  { char: "现金", pinyin: "xiànjīn", de: "Bargeld", en: "cash", es: "efectivo", hi: "नक़द", cat: "Geld", icon: "💵" },
  { char: "羡慕", pinyin: "xiànmù", de: "Beneiden", en: "envy", es: "envidiar", hi: "ईर्ष्या", cat: "Emotion", icon: "😍" },
  { char: "相反", pinyin: "xiāngfǎn", de: "Gegenteil", en: "opposite", es: "opuesto", hi: "विपरीत", cat: "Grammatik", icon: "↔️" },
  { char: "相信", pinyin: "xiāngxìn", de: "Glauben", en: "believe", es: "creer", hi: "विश्वास", cat: "Verben", icon: "🙏" },
  { char: "详细", pinyin: "xiángxì", de: "Detailliert", en: "detailed", es: "detallado", hi: "विस्तृत", cat: "Adjektive", icon: "📋" },
  { char: "响", pinyin: "xiǎng", de: "Klingen", en: "ring", es: "sonar", hi: "बजना", cat: "Verben", icon: "🔔" },
  { char: "享受", pinyin: "xiǎngshòu", de: "Genießen", en: "enjoy", es: "disfrutar", hi: "आनंद लेना", cat: "Verben", icon: "😊" },
  { char: "小吃", pinyin: "xiǎochī", de: "Snack", en: "snack", es: "aperitivo", hi: "स्नैक", cat: "Essen", icon: "🍡" },
  { char: "小说", pinyin: "xiǎoshuō", de: "Roman", en: "novel", es: "novela", hi: "उपन्यास", cat: "Dinge", icon: "📖" },
  { char: "效果", pinyin: "xiàoguǒ", de: "Wirkung", en: "effect", es: "efecto", hi: "प्रभाव", cat: "Dinge", icon: "✨" },
  { char: "心情", pinyin: "xīnqíng", de: "Stimmung", en: "mood", es: "estado de ánimo", hi: "मूड", cat: "Emotion", icon: "😊" },
  { char: "信封", pinyin: "xìnfēng", de: "Briefumschlag", en: "envelope", es: "sobre", hi: "लिफ़ाफ़ा", cat: "Dinge", icon: "✉️" },
  { char: "信任", pinyin: "xìnrèn", de: "Vertrauen", en: "trust", es: "confiar", hi: "भरोसा", cat: "Emotion", icon: "🤝" },
  { char: "信息", pinyin: "xìnxī", de: "Information", en: "information", es: "información", hi: "जानकारी", cat: "Dinge", icon: "ℹ️" },
  { char: "信用卡", pinyin: "xìnyòngkǎ", de: "Kreditkarte", en: "credit card", es: "tarjeta de crédito", hi: "क्रेडिट कार्ड", cat: "Geld", icon: "💳" },
  { char: "兴奋", pinyin: "xīngfèn", de: "Aufgeregt", en: "excited", es: "emocionado", hi: "उत्साहित", cat: "Emotion", icon: "🤩" },
  { char: "醒", pinyin: "xǐng", de: "Aufwachen", en: "wake up", es: "despertar", hi: "जागना", cat: "Verben", icon: "⏰" },
  { char: "性格", pinyin: "xìnggé", de: "Charakter", en: "personality", es: "personalidad", hi: "व्यक्तित्व", cat: "Geist", icon: "🎭" },
  { char: "幸福", pinyin: "xìngfú", de: "Glücklich", en: "happy", es: "feliz", hi: "खुशी", cat: "Emotion", icon: "🥰" },
  { char: "修", pinyin: "xiū", de: "Reparieren", en: "repair", es: "reparar", hi: "मरम्मत", cat: "Verben", icon: "🔧" },
  { char: "修理", pinyin: "xiūlǐ", de: "Reparieren", en: "fix", es: "arreglar", hi: "ठीक करना", cat: "Verben", icon: "🛠️" },
  { char: "许多", pinyin: "xǔduō", de: "Viele", en: "many", es: "muchos", hi: "बहुत", cat: "Grammatik", icon: "📊" },
  { char: "选择", pinyin: "xuǎnzé", de: "Wählen", en: "choose", es: "elegir", hi: "चुनना", cat: "Verben", icon: "✅" },
  { char: "学期", pinyin: "xuéqī", de: "Semester", en: "semester", es: "semestre", hi: "सेमेस्टर", cat: "Schule", icon: "📚" },
  { char: "押金", pinyin: "yājīn", de: "Kaution", en: "deposit", es: "depósito", hi: "जमानत", cat: "Geld", icon: "💰" },
  { char: "牙膏", pinyin: "yágāo", de: "Zahnpasta", en: "toothpaste", es: "pasta de dientes", hi: "टूथपेस्ट", cat: "Dinge", icon: "🦷" },
  { char: "亚洲", pinyin: "Yàzhōu", de: "Asien", en: "Asia", es: "Asia", hi: "एशिया", cat: "Orte", icon: "🌏" },
  { char: "严格", pinyin: "yángé", de: "Streng", en: "strict", es: "estricto", hi: "सख़्त", cat: "Adjektive", icon: "😤" },
  { char: "严重", pinyin: "yánzhòng", de: "Ernst", en: "serious", es: "serio", hi: "गंभीर", cat: "Adjektive", icon: "⚠️" },
  { char: "阳光", pinyin: "yángguāng", de: "Sonnenschein", en: "sunshine", es: "luz del sol", hi: "धूप", cat: "Wetter", icon: "☀️" },
  { char: "养成", pinyin: "yǎngchéng", de: "Entwickeln", en: "develop", es: "desarrollar", hi: "विकसित करना", cat: "Verben", icon: "🌱" },
  { char: "邀请", pinyin: "yāoqǐng", de: "Einladen", en: "invite", es: "invitar", hi: "निमंत्रण", cat: "Aktionen", icon: "📨" },
  { char: "钥匙", pinyin: "yàoshi", de: "Schlüssel", en: "key", es: "llave", hi: "चाबी", cat: "Dinge", icon: "🔑" },
  { char: "页", pinyin: "yè", de: "Seite", en: "page", es: "página", hi: "पृष्ठ", cat: "Dinge", icon: "📄" },
  { char: "叶子", pinyin: "yèzi", de: "Blatt", en: "leaf", es: "hoja", hi: "पत्ता", cat: "Natur", icon: "🍃" },
  { char: "一切", pinyin: "yíqiè", de: "Alles", en: "everything", es: "todo", hi: "सब कुछ", cat: "Grammatik", icon: "🌍" },
  { char: "艺术", pinyin: "yìshù", de: "Kunst", en: "art", es: "arte", hi: "कला", cat: "Kultur", icon: "🎨" },
  { char: "阴", pinyin: "yīn", de: "Bewölkt", en: "cloudy", es: "nublado", hi: "बादल", cat: "Wetter", icon: "☁️" },
  { char: "印象", pinyin: "yìnxiàng", de: "Eindruck", en: "impression", es: "impresión", hi: "छाप", cat: "Geist", icon: "💭" },
  { char: "赢", pinyin: "yíng", de: "Gewinnen", en: "win", es: "ganar", hi: "जीतना", cat: "Verben", icon: "🏆" },
  { char: "应该", pinyin: "yīnggāi", de: "Sollen", en: "should", es: "deber", hi: "चाहिए", cat: "Verben", icon: "✅" },
  { char: "优点", pinyin: "yōudiǎn", de: "Vorteil", en: "advantage", es: "ventaja", hi: "गुण", cat: "Geist", icon: "✅" },
  { char: "优秀", pinyin: "yōuxiù", de: "Ausgezeichnet", en: "excellent", es: "excelente", hi: "उत्कृष्ट", cat: "Adjektive", icon: "🌟" },
  { char: "尤其", pinyin: "yóuqí", de: "Besonders", en: "especially", es: "especialmente", hi: "विशेष रूप से", cat: "Adverb", icon: "⭐" },
  { char: "由", pinyin: "yóu", de: "Von", en: "by", es: "por", hi: "द्वारा", cat: "Grammatik", icon: "➡️" },
  { char: "由于", pinyin: "yóuyú", de: "Wegen", en: "due to", es: "debido a", hi: "के कारण", cat: "Grammatik", icon: "📌" },
  { char: "邮局", pinyin: "yóujú", de: "Post", en: "post office", es: "correos", hi: "डाकघर", cat: "Orte", icon: "📮" },
  { char: "友好", pinyin: "yǒuhǎo", de: "Freundlich", en: "friendly", es: "amistoso", hi: "मैत्रीपूर्ण", cat: "Adjektive", icon: "😊" },
  { char: "友谊", pinyin: "yǒuyì", de: "Freundschaft", en: "friendship", es: "amistad", hi: "दोस्ती", cat: "Emotion", icon: "👫" },
  { char: "有趣", pinyin: "yǒuqù", de: "Interessant", en: "interesting", es: "interesante", hi: "दिलचस्प", cat: "Adjektive", icon: "😄" },
  { char: "于是", pinyin: "yúshì", de: "So", en: "so", es: "así que", hi: "इसलिए", cat: "Grammatik", icon: "➡️" },
  { char: "与", pinyin: "yǔ", de: "Und", en: "and", es: "y", hi: "और", cat: "Grammatik", icon: "➕" },
  { char: "羽毛球", pinyin: "yǔmáoqiú", de: "Badminton", en: "badminton", es: "bádminton", hi: "बैडमिंटन", cat: "Sport", icon: "🏸" },
  { char: "语法", pinyin: "yǔfǎ", de: "Grammatik", en: "grammar", es: "gramática", hi: "व्याकरण", cat: "Sprache", icon: "📝" },
  { char: "语言", pinyin: "yǔyán", de: "Sprache", en: "language", es: "idioma", hi: "भाषा", cat: "Sprache", icon: "🗣️" },
  { char: "预习", pinyin: "yùxí", de: "Vorbereiten", en: "preview", es: "preparar", hi: "पूर्व अध्ययन", cat: "Schule", icon: "📚" },
  { char: "原来", pinyin: "yuánlái", de: "Ursprünglich", en: "originally", es: "originalmente", hi: "मूलतः", cat: "Adverb", icon: "⏮️" },
  { char: "原谅", pinyin: "yuánliàng", de: "Verzeihen", en: "forgive", es: "perdonar", hi: "माफ़ करना", cat: "Verben", icon: "🙏" },
  { char: "原因", pinyin: "yuányīn", de: "Grund", en: "reason", es: "razón", hi: "कारण", cat: "Geist", icon: "❓" },
  { char: "约会", pinyin: "yuēhuì", de: "Date", en: "date", es: "cita", hi: "डेट", cat: "Aktionen", icon: "💑" },
  { char: "阅读", pinyin: "yuèdú", de: "Lesen", en: "read", es: "leer", hi: "पढ़ना", cat: "Verben", icon: "📖" },
  { char: "云", pinyin: "yún", de: "Wolke", en: "cloud", es: "nube", hi: "बादल", cat: "Wetter", icon: "☁️" },
  { char: "允许", pinyin: "yǔnxǔ", de: "Erlauben", en: "allow", es: "permitir", hi: "अनुमति", cat: "Verben", icon: "✅" },
  { char: "咱们", pinyin: "zánmen", de: "Wir", en: "we", es: "nosotros", hi: "हम सब", cat: "Pronomen", icon: "👥" },
  { char: "暂时", pinyin: "zànshí", de: "Vorübergehend", en: "temporarily", es: "temporalmente", hi: "अस्थायी", cat: "Zeit", icon: "⏱️" },
  { char: "脏", pinyin: "zāng", de: "Schmutzig", en: "dirty", es: "sucio", hi: "गंदा", cat: "Adjektive", icon: "🗑️" },
  { char: "责任", pinyin: "zérèn", de: "Verantwortung", en: "responsibility", es: "responsabilidad", hi: "ज़िम्मेदारी", cat: "Geist", icon: "💼" },
  { char: "占", pinyin: "zhàn", de: "Besetzen", en: "occupy", es: "ocupar", hi: "क़ब्ज़ा करना", cat: "Verben", icon: "📍" },
  { char: "招聘", pinyin: "zhāopìn", de: "Rekrutieren", en: "recruit", es: "reclutar", hi: "भर्ती", cat: "Aktionen", icon: "📝" },
  { char: "照", pinyin: "zhào", de: "Nach", en: "according to", es: "según", hi: "के अनुसार", cat: "Grammatik", icon: "📋" },
  { char: "照顾", pinyin: "zhàogu", de: "Pflegen", en: "take care of", es: "cuidar", hi: "देखभाल", cat: "Verben", icon: "🤗" },
  { char: "哲学", pinyin: "zhéxué", de: "Philosophie", en: "philosophy", es: "filosofía", hi: "दर्शन", cat: "Schule", icon: "🤔" },
  { char: "者", pinyin: "zhě", de: "Person", en: "person", es: "persona", hi: "वाला", cat: "Grammatik", icon: "👤" },
  { char: "针对", pinyin: "zhēnduì", de: "Gegen", en: "against", es: "contra", hi: "के लिए", cat: "Grammatik", icon: "🎯" },
  { char: "整理", pinyin: "zhěnglǐ", de: "Ordnen", en: "arrange", es: "ordenar", hi: "व्यवस्थित करना", cat: "Verben", icon: "📊" },
  { char: "正好", pinyin: "zhènghǎo", de: "Genau", en: "just right", es: "justo", hi: "बिल्कुल", cat: "Adverb", icon: "👌" },
  { char: "正确", pinyin: "zhèngquè", de: "Richtig", en: "correct", es: "correcto", hi: "सही", cat: "Adjektive", icon: "✅" },
  { char: "正式", pinyin: "zhèngshì", de: "Offiziell", en: "formal", es: "formal", hi: "औपचारिक", cat: "Adjektive", icon: "👔" },
  { char: "证明", pinyin: "zhèngmíng", de: "Beweisen", en: "prove", es: "probar", hi: "साबित करना", cat: "Verben", icon: "📜" },
  { char: "之", pinyin: "zhī", de: "Von", en: "of", es: "de", hi: "का", cat: "Grammatik", icon: "📌" },
  { char: "支持", pinyin: "zhīchí", de: "Unterstützen", en: "support", es: "apoyar", hi: "समर्थन", cat: "Verben", icon: "👍" },
  { char: "只好", pinyin: "zhǐhǎo", de: "Müssen", en: "have to", es: "tener que", hi: "मजबूर होना", cat: "Adverb", icon: "🤷" },
  { char: "只要", pinyin: "zhǐyào", de: "Solange", en: "as long as", es: "mientras que", hi: "बस", cat: "Grammatik", icon: "✅" },
  { char: "指", pinyin: "zhǐ", de: "Zeigen", en: "point", es: "señalar", hi: "इशारा करना", cat: "Verben", icon: "👆" },
  { char: "至少", pinyin: "zhìshǎo", de: "Mindestens", en: "at least", es: "al menos", hi: "कम से कम", cat: "Adverb", icon: "📊" },
  { char: "质量", pinyin: "zhìliàng", de: "Qualität", en: "quality", es: "calidad", hi: "गुणवत्ता", cat: "Dinge", icon: "⭐" },
  { char: "治疗", pinyin: "zhìliáo", de: "Behandeln", en: "treat", es: "tratar", hi: "इलाज", cat: "Gesundheit", icon: "🏥" },
  { char: "中文", pinyin: "zhōngwén", de: "Chinesisch", en: "Chinese", es: "chino", hi: "चीनी भाषा", cat: "Sprache", icon: "🇨🇳" },
  { char: "中心", pinyin: "zhōngxīn", de: "Zentrum", en: "center", es: "centro", hi: "केंद्र", cat: "Orte", icon: "📍" },
  { char: "重点", pinyin: "zhòngdiǎn", de: "Schwerpunkt", en: "focus", es: "punto clave", hi: "मुख्य बिंदु", cat: "Geist", icon: "🎯" },
  { char: "重视", pinyin: "zhòngshì", de: "Schätzen", en: "value", es: "valorar", hi: "महत्व देना", cat: "Verben", icon: "💎" },
  { char: "周围", pinyin: "zhōuwéi", de: "Umgebung", en: "surroundings", es: "alrededores", hi: "आसपास", cat: "Richtungen", icon: "🔄" },
  { char: "主动", pinyin: "zhǔdòng", de: "Proaktiv", en: "proactive", es: "proactivo", hi: "सक्रिय", cat: "Adjektive", icon: "💪" },
  { char: "主意", pinyin: "zhǔyi", de: "Idee", en: "idea", es: "idea", hi: "विचार", cat: "Geist", icon: "💡" },
  { char: "祝贺", pinyin: "zhùhè", de: "Gratulieren", en: "congratulate", es: "felicitar", hi: "बधाई", cat: "Verben", icon: "🎉" },
  { char: "著名", pinyin: "zhùmíng", de: "Berühmt", en: "famous", es: "famoso", hi: "प्रसिद्ध", cat: "Adjektive", icon: "⭐" },
  { char: "专门", pinyin: "zhuānmén", de: "Speziell", en: "specially", es: "especialmente", hi: "विशेष रूप से", cat: "Adverb", icon: "🎯" },
  { char: "专业", pinyin: "zhuānyè", de: "Fachgebiet", en: "major", es: "especialidad", hi: "विषय", cat: "Schule", icon: "📚" },
  { char: "赚", pinyin: "zhuàn", de: "Verdienen", en: "earn", es: "ganar", hi: "कमाना", cat: "Verben", icon: "💰" },
  { char: "撞", pinyin: "zhuàng", de: "Stoßen", en: "bump", es: "chocar", hi: "टकराना", cat: "Verben", icon: "💥" },
  { char: "准确", pinyin: "zhǔnquè", de: "Genau", en: "accurate", es: "preciso", hi: "सटीक", cat: "Adjektive", icon: "🎯" },
  { char: "仔细", pinyin: "zǐxì", de: "Sorgfältig", en: "careful", es: "cuidadoso", hi: "सावधानी से", cat: "Adjektive", icon: "🔍" },
  { char: "自然", pinyin: "zìrán", de: "Natur", en: "nature", es: "naturaleza", hi: "प्रकृति", cat: "Natur", icon: "🌿" },
  { char: "自信", pinyin: "zìxìn", de: "Selbstbewusst", en: "confident", es: "seguro de sí", hi: "आत्मविश्वास", cat: "Adjektive", icon: "💪" },
  { char: "总结", pinyin: "zǒngjié", de: "Zusammenfassen", en: "summarize", es: "resumir", hi: "सारांश", cat: "Verben", icon: "📝" },
  { char: "租", pinyin: "zū", de: "Mieten", en: "rent", es: "alquilar", hi: "किराए पर", cat: "Verben", icon: "🏠" },
  { char: "组成", pinyin: "zǔchéng", de: "Zusammensetzen", en: "compose", es: "componer", hi: "बनाना", cat: "Verben", icon: "🧩" },
  { char: "组织", pinyin: "zǔzhī", de: "Organisation", en: "organize", es: "organizar", hi: "संगठन", cat: "Verben", icon: "🏢" },
  { char: "座", pinyin: "zuò", de: "Sitz", en: "seat", es: "asiento", hi: "सीट", cat: "Dinge", icon: "💺" },
  { char: "座位", pinyin: "zuòwèi", de: "Sitzplatz", en: "seat", es: "asiento", hi: "स्थान", cat: "Dinge", icon: "🪑" },
  { char: "作家", pinyin: "zuòjiā", de: "Autor", en: "writer", es: "escritor", hi: "लेखक", cat: "Personen", icon: "✍️" },
  { char: "作用", pinyin: "zuòyòng", de: "Wirkung", en: "function", es: "función", hi: "भूमिका", cat: "Dinge", icon: "⚙️" },
  { char: "作者", pinyin: "zuòzhě", de: "Autor", en: "author", es: "autor", hi: "लेखक", cat: "Personen", icon: "📝" },
  { char: "按照", pinyin: "ànzhào", de: "Gemäß", en: "according to", es: "según", hi: "के अनुसार", cat: "Grammatik", icon: "📋" },
  { char: "百分之", pinyin: "bǎifēnzhī", de: "Prozent", en: "percent", es: "por ciento", hi: "प्रतिशत", cat: "Zahlen", icon: "%" },
  { char: "棒", pinyin: "bàng", de: "Toll", en: "great", es: "genial", hi: "बढ़िया", cat: "Adjektive", icon: "👍" },
  { char: "抱", pinyin: "bào", de: "Umarmen", en: "hug", es: "abrazar", hi: "गले लगाना", cat: "Verben", icon: "🤗" },
  { char: "被", pinyin: "bèi", de: "Passiv", en: "by", es: "por", hi: "द्वारा", cat: "Grammatik", icon: "📌" },
  { char: "本来", pinyin: "běnlái", de: "Ursprünglich", en: "originally", es: "originalmente", hi: "मूलतः", cat: "Adverb", icon: "⏮️" },
  { char: "笨", pinyin: "bèn", de: "Dumm", en: "stupid", es: "tonto", hi: "मूर्ख", cat: "Adjektive", icon: "🐢" },
  { char: "比如", pinyin: "bǐrú", de: "Zum Beispiel", en: "for example", es: "por ejemplo", hi: "जैसे कि", cat: "Grammatik", icon: "📝" },
  { char: "标准", pinyin: "biāozhǔn", de: "Standard", en: "standard", es: "estándar", hi: "मानक", cat: "Dinge", icon: "📏" },
  { char: "表扬", pinyin: "biǎoyáng", de: "Loben", en: "praise", es: "elogiar", hi: "प्रशंसा", cat: "Verben", icon: "👏" },
  { char: "并且", pinyin: "bìngqiě", de: "Außerdem", en: "and", es: "además", hi: "और भी", cat: "Grammatik", icon: "➕" },
  { char: "不管", pinyin: "bùguǎn", de: "Egal", en: "no matter", es: "sin importar", hi: "चाहे", cat: "Grammatik", icon: "🤷" },
  { char: "不过", pinyin: "búguò", de: "Aber", en: "but", es: "pero", hi: "लेकिन", cat: "Grammatik", icon: "↩️" },
  { char: "不仅", pinyin: "bùjǐn", de: "Nicht nur", en: "not only", es: "no solo", hi: "न केवल", cat: "Grammatik", icon: "➕" },
  { char: "擦", pinyin: "cā", de: "Wischen", en: "wipe", es: "limpiar", hi: "पोंछना", cat: "Verben", icon: "🧽" },
  { char: "猜", pinyin: "cāi", de: "Raten", en: "guess", es: "adivinar", hi: "अनुमान लगाना", cat: "Verben", icon: "🤔" },
  { char: "餐厅", pinyin: "cāntīng", de: "Restaurant", en: "restaurant", es: "restaurante", hi: "रेस्तरां", cat: "Orte", icon: "🍽️" },
  { char: "厕所", pinyin: "cèsuǒ", de: "Toilette", en: "toilet", es: "baño", hi: "शौचालय", cat: "Orte", icon: "🚽" },
  { char: "差不多", pinyin: "chàbuduō", de: "Fast", en: "almost", es: "casi", hi: "लगभग", cat: "Adverb", icon: "📊" },
  { char: "尝", pinyin: "cháng", de: "Probieren", en: "taste", es: "probar", hi: "चखना", cat: "Verben", icon: "👅" },
  { char: "场", pinyin: "chǎng", de: "Platz", en: "field", es: "campo", hi: "मैदान", cat: "Orte", icon: "🏟️" },
  { char: "吵架", pinyin: "chǎojià", de: "Streiten", en: "quarrel", es: "pelear", hi: "झगड़ा", cat: "Verben", icon: "😠" },
  { char: "乘坐", pinyin: "chéngzuò", de: "Fahren", en: "ride", es: "tomar", hi: "सवारी करना", cat: "Verben", icon: "🚌" },
  { char: "抽烟", pinyin: "chōuyān", de: "Rauchen", en: "smoke", es: "fumar", hi: "धूम्रपान", cat: "Aktionen", icon: "🚬" },
  { char: "出差", pinyin: "chūchāi", de: "Geschäftsreise", en: "business trip", es: "viaje de negocios", hi: "व्यापार यात्रा", cat: "Aktionen", icon: "💼" },
  { char: "出现", pinyin: "chūxiàn", de: "Erscheinen", en: "appear", es: "aparecer", hi: "प्रकट होना", cat: "Verben", icon: "✨" },
  { char: "厨房", pinyin: "chúfáng", de: "Küche", en: "kitchen", es: "cocina", hi: "रसोई", cat: "Orte", icon: "🍳" },
  { char: "词典", pinyin: "cídiǎn", de: "Wörterbuch", en: "dictionary", es: "diccionario", hi: "शब्दकोश", cat: "Dinge", icon: "📖" },
  { char: "从来", pinyin: "cónglái", de: "Niemals", en: "never", es: "nunca", hi: "कभी नहीं", cat: "Adverb", icon: "❌" },
  { char: "粗心", pinyin: "cūxīn", de: "Unaufmerksam", en: "careless", es: "descuidado", hi: "लापरवाह", cat: "Adjektive", icon: "😅" },
  { char: "大约", pinyin: "dàyuē", de: "Ungefähr", en: "about", es: "aproximadamente", hi: "लगभग", cat: "Adverb", icon: "📊" },
  { char: "当", pinyin: "dāng", de: "Als", en: "when", es: "cuando", hi: "जब", cat: "Grammatik", icon: "⏰" },
  { char: "导游", pinyin: "dǎoyóu", de: "Reiseleiter", en: "tour guide", es: "guía turístico", hi: "टूर गाइड", cat: "Personen", icon: "🚩" },
  { char: "倒", pinyin: "dào", de: "Umgekehrt", en: "upside down", es: "al revés", hi: "उल्टा", cat: "Verben", icon: "🔄" },
  { char: "底", pinyin: "dǐ", de: "Boden", en: "bottom", es: "fondo", hi: "नीचे", cat: "Richtungen", icon: "⬇️" },
  { char: "地点", pinyin: "dìdiǎn", de: "Ort", en: "location", es: "ubicación", hi: "स्थान", cat: "Orte", icon: "📍" },
  { char: "调查", pinyin: "diàochá", de: "Untersuchen", en: "investigate", es: "investigar", hi: "जाँच", cat: "Verben", icon: "🔍" },
  { char: "掉", pinyin: "diào", de: "Fallen", en: "fall", es: "caer", hi: "गिरना", cat: "Verben", icon: "⬇️" },
  { char: "丢", pinyin: "diū", de: "Verlieren", en: "lose", es: "perder", hi: "खोना", cat: "Verben", icon: "❓" },
  { char: "读者", pinyin: "dúzhě", de: "Leser", en: "reader", es: "lector", hi: "पाठक", cat: "Personen", icon: "📖" },
  { char: "堵车", pinyin: "dǔchē", de: "Stau", en: "traffic jam", es: "atasco", hi: "ट्रैफ़िक जाम", cat: "Verkehr", icon: "🚗" },
  { char: "肚子", pinyin: "dùzi", de: "Bauch", en: "stomach", es: "estómago", hi: "पेट", cat: "Mensch", icon: "🫃" },
  { char: "对话", pinyin: "duìhuà", de: "Dialog", en: "dialogue", es: "diálogo", hi: "संवाद", cat: "Sprache", icon: "💬" },
  { char: "对面", pinyin: "duìmiàn", de: "Gegenüber", en: "opposite", es: "enfrente", hi: "सामने", cat: "Richtungen", icon: "↔️" },
  { char: "对于", pinyin: "duìyú", de: "Bezüglich", en: "regarding", es: "respecto a", hi: "के बारे में", cat: "Grammatik", icon: "📌" },
  { char: "儿童", pinyin: "értóng", de: "Kind", en: "child", es: "niño", hi: "बच्चे", cat: "Personen", icon: "👶" },
  { char: "发", pinyin: "fā", de: "Senden", en: "send", es: "enviar", hi: "भेजना", cat: "Verben", icon: "📤" },
  { char: "发生", pinyin: "fāshēng", de: "Passieren", en: "happen", es: "ocurrir", hi: "होना", cat: "Verben", icon: "⚡" },
  { char: "反对", pinyin: "fǎnduì", de: "Dagegen", en: "oppose", es: "oponerse", hi: "विरोध", cat: "Verben", icon: "❌" },
  { char: "烦恼", pinyin: "fánnǎo", de: "Ärger", en: "trouble", es: "preocupación", hi: "चिंता", cat: "Emotion", icon: "😫" },
  { char: "范围", pinyin: "fànwéi", de: "Bereich", en: "range", es: "rango", hi: "सीमा", cat: "Dinge", icon: "📐" },
  { char: "份", pinyin: "fèn", de: "Portion", en: "portion", es: "porción", hi: "हिस्सा", cat: "Maße", icon: "📦" },
  { char: "丰富", pinyin: "fēngfù", de: "Reich", en: "rich", es: "rico", hi: "समृद्ध", cat: "Adjektive", icon: "🌈" },
  { char: "否则", pinyin: "fǒuzé", de: "Sonst", en: "otherwise", es: "de lo contrario", hi: "वरना", cat: "Grammatik", icon: "⚠️" },
  { char: "符合", pinyin: "fúhé", de: "Entsprechen", en: "conform", es: "cumplir", hi: "मिलना", cat: "Verben", icon: "✅" },
  { char: "父亲", pinyin: "fùqīn", de: "Vater", en: "father", es: "padre", hi: "पिता", cat: "Personen", icon: "👨" },
  { char: "富", pinyin: "fù", de: "Reich", en: "rich", es: "rico", hi: "अमीर", cat: "Adjektive", icon: "💰" },
  { char: "复习", pinyin: "fùxí", de: "Wiederholen", en: "review", es: "repasar", hi: "दोहराना", cat: "Schule", icon: "📚" },
  { char: "复印", pinyin: "fùyìn", de: "Kopieren", en: "copy", es: "copiar", hi: "फ़ोटोकॉपी", cat: "Aktionen", icon: "📄" },
  { char: "复杂", pinyin: "fùzá", de: "Komplex", en: "complex", es: "complejo", hi: "जटिल", cat: "Adjektive", icon: "🌀" },
  { char: "改", pinyin: "gǎi", de: "Ändern", en: "change", es: "cambiar", hi: "बदलना", cat: "Verben", icon: "✏️" },
  { char: "感谢", pinyin: "gǎnxiè", de: "Danken", en: "thank", es: "agradecer", hi: "धन्यवाद", cat: "Verben", icon: "🙏" },
  { char: "刚才", pinyin: "gāngcái", de: "Gerade", en: "just now", es: "ahora mismo", hi: "अभी", cat: "Zeit", icon: "⏰" },
  { char: "个子", pinyin: "gèzi", de: "Größe", en: "height", es: "altura", hi: "क़द", cat: "Mensch", icon: "📏" },
  { char: "各种各样", pinyin: "gèzhǒnggèyàng", de: "Verschiedene", en: "various", es: "varios", hi: "विभिन्न", cat: "Grammatik", icon: "🌈" },
  { char: "工程师", pinyin: "gōngchéngshī", de: "Ingenieur", en: "engineer", es: "ingeniero", hi: "इंजीनियर", cat: "Personen", icon: "👷" },
  { char: "公里", pinyin: "gōnglǐ", de: "Kilometer", en: "kilometer", es: "kilómetro", hi: "किलोमीटर", cat: "Maße", icon: "📏" },
  { char: "估计", pinyin: "gūjì", de: "Schätzen", en: "estimate", es: "estimar", hi: "अनुमान", cat: "Verben", icon: "🤔" },
  { char: "挂", pinyin: "guà", de: "Aufhängen", en: "hang", es: "colgar", hi: "लटकाना", cat: "Verben", icon: "🪝" },
  { char: "关", pinyin: "guān", de: "Schließen", en: "close", es: "cerrar", hi: "बंद करना", cat: "Verben", icon: "🚪" },
  { char: "观点", pinyin: "guāndiǎn", de: "Ansicht", en: "viewpoint", es: "punto de vista", hi: "दृष्टिकोण", cat: "Geist", icon: "👀" },
  { char: "管理", pinyin: "guǎnlǐ", de: "Verwalten", en: "manage", es: "gestionar", hi: "प्रबंधन", cat: "Verben", icon: "👔" },
  { char: "光", pinyin: "guāng", de: "Licht", en: "light", es: "luz", hi: "रोशनी", cat: "Natur", icon: "💡" },
  { char: "广播", pinyin: "guǎngbō", de: "Rundfunk", en: "broadcast", es: "transmisión", hi: "प्रसारण", cat: "Dinge", icon: "📻" },
  { char: "规定", pinyin: "guīdìng", de: "Regel", en: "regulation", es: "regla", hi: "नियम", cat: "Dinge", icon: "📜" },
  { char: "国籍", pinyin: "guójí", de: "Nationalität", en: "nationality", es: "nacionalidad", hi: "राष्ट्रीयता", cat: "Dinge", icon: "🛂" },
  { char: "过程", pinyin: "guòchéng", de: "Prozess", en: "process", es: "proceso", hi: "प्रक्रिया", cat: "Dinge", icon: "⚙️" },
  { char: "海", pinyin: "hǎi", de: "Meer", en: "sea", es: "mar", hi: "समुद्र", cat: "Natur", icon: "🌊" },
  { char: "寒假", pinyin: "hánjià", de: "Winterferien", en: "winter vacation", es: "vacaciones de invierno", hi: "सर्दियों की छुट्टी", cat: "Zeit", icon: "❄️" },
  { char: "汗", pinyin: "hàn", de: "Schweiß", en: "sweat", es: "sudor", hi: "पसीना", cat: "Mensch", icon: "💦" },
  { char: "航班", pinyin: "hángbān", de: "Flug", en: "flight", es: "vuelo", hi: "उड़ान", cat: "Verkehr", icon: "✈️" },
  { char: "好处", pinyin: "hǎochù", de: "Vorteil", en: "advantage", es: "ventaja", hi: "फ़ायदा", cat: "Geist", icon: "👍" },
  { char: "合适", pinyin: "héshì", de: "Passend", en: "suitable", es: "adecuado", hi: "उचित", cat: "Adjektive", icon: "👌" },
  { char: "即使", pinyin: "jíshǐ", de: "Selbst wenn", en: "even if", es: "aunque", hi: "भले ही", cat: "Grammatik", icon: "🛤️" },
  { char: "计划", pinyin: "jìhuà", de: "Plan", en: "plan", es: "plan", hi: "योजना", cat: "Geist", icon: "📅" },
  { char: "技术", pinyin: "jìshù", de: "Technik", en: "technology", es: "tecnología", hi: "तकनीक", cat: "Dinge", icon: "💻" },
  { char: "既然", pinyin: "jìrán", de: "Da", en: "since", es: "ya que", hi: "चूँकि", cat: "Grammatik", icon: "💁" },
  { char: "继续", pinyin: "jìxù", de: "Fortfahren", en: "continue", es: "continuar", hi: "जारी रखना", cat: "Verben", icon: "▶️" },
  { char: "加班", pinyin: "jiābān", de: "Überstunden", en: "overtime", es: "horas extra", hi: "ओवरटाइम", cat: "Aktionen", icon: "🌙" },
  { char: "加油", pinyin: "jiāyóu", de: "Los!", en: "come on", es: "ánimo", hi: "हौसला", cat: "Ausdrücke", icon: "💪" },
  { char: "家庭主妇", pinyin: "jiātíngzhǔfù", de: "Hausfrau", en: "housewife", es: "ama de casa", hi: "गृहिणी", cat: "Personen", icon: "👩‍🍳" },
  { char: "假", pinyin: "jiǎ", de: "Falsch", en: "fake", es: "falso", hi: "नकली", cat: "Adjektive", icon: "❌" },
  { char: "价格", pinyin: "jiàgé", de: "Preis", en: "price", es: "precio", hi: "क़ीमत", cat: "Geld", icon: "🏷️" },
  { char: "坚持", pinyin: "jiānchí", de: "Durchhalten", en: "persist", es: "persistir", hi: "दृढ़ रहना", cat: "Verben", icon: "✊" },
  { char: "减少", pinyin: "jiǎnshǎo", de: "Reduzieren", en: "reduce", es: "reducir", hi: "कम करना", cat: "Verben", icon: "📉" },
  { char: "建议", pinyin: "jiànyì", de: "Vorschlag", en: "suggestion", es: "sugerencia", hi: "सुझाव", cat: "Verben", icon: "💡" },
  { char: "将来", pinyin: "jiānglái", de: "Zukunft", en: "future", es: "futuro", hi: "भविष्य", cat: "Zeit", icon: "🔮" },
  { char: "奖金", pinyin: "jiǎngjīn", de: "Bonus", en: "bonus", es: "bonificación", hi: "बोनस", cat: "Geld", icon: "💵" },
  { char: "降低", pinyin: "jiàngdī", de: "Senken", en: "reduce", es: "reducir", hi: "कम करना", cat: "Verben", icon: "⬇️" },
  { char: "交", pinyin: "jiāo", de: "Übergeben", en: "hand over", es: "entregar", hi: "सौंपना", cat: "Verben", icon: "🤝" },
  { char: "交流", pinyin: "jiāoliú", de: "Austausch", en: "exchange", es: "intercambio", hi: "आदान-प्रदान", cat: "Verben", icon: "🗣️" },
  { char: "郊区", pinyin: "jiāoqū", de: "Vorstadt", en: "suburb", es: "suburbio", hi: "उपनगर", cat: "Orte", icon: "🏘️" },
  { char: "教育", pinyin: "jiàoyù", de: "Bildung", en: "education", es: "educación", hi: "शिक्षा", cat: "Schule", icon: "🏫" },
  { char: "接受", pinyin: "jiēshòu", de: "Akzeptieren", en: "accept", es: "aceptar", hi: "स्वीकार करना", cat: "Verben", icon: "✅" },
  { char: "结果", pinyin: "jiéguǒ", de: "Ergebnis", en: "result", es: "resultado", hi: "नतीजा", cat: "Dinge", icon: "📊" },
  { char: "竟然", pinyin: "jìngrán", de: "Überraschend", en: "unexpectedly", es: "sorprendentemente", hi: "अचानक", cat: "Adverb", icon: "😮" },
  { char: "镜子", pinyin: "jìngzi", de: "Spiegel", en: "mirror", es: "espejo", hi: "आईना", cat: "Dinge", icon: "🪞" },
  { char: "举", pinyin: "jǔ", de: "Heben", en: "raise", es: "levantar", hi: "उठाना", cat: "Verben", icon: "🙋" },
  { char: "举行", pinyin: "jǔxíng", de: "Veranstalten", en: "hold", es: "celebrar", hi: "आयोजित करना", cat: "Aktionen", icon: "🎉" },
  { char: "拒绝", pinyin: "jùjué", de: "Ablehnen", en: "refuse", es: "rechazar", hi: "इनकार", cat: "Verben", icon: "🙅" },
  { char: "距离", pinyin: "jùlí", de: "Entfernung", en: "distance", es: "distancia", hi: "दूरी", cat: "Maße", icon: "📏" },
  { char: "聚会", pinyin: "jùhuì", de: "Party", en: "party", es: "fiesta", hi: "पार्टी", cat: "Aktionen", icon: "🎊" },
  { char: "开心", pinyin: "kāixīn", de: "Fröhlich", en: "happy", es: "feliz", hi: "खुश", cat: "Emotion", icon: "😄" },
  { char: "开玩笑", pinyin: "kāiwánxiào", de: "Scherzen", en: "joke", es: "bromear", hi: "मज़ाक करना", cat: "Verben", icon: "😄" },
  { char: "看法", pinyin: "kànfǎ", de: "Ansicht", en: "opinion", es: "opinión", hi: "विचार", cat: "Geist", icon: "👀" },
  { char: "考虑", pinyin: "kǎolǜ", de: "Überlegen", en: "consider", es: "considerar", hi: "सोचना", cat: "Geist", icon: "🤔" },
  { char: "烤鸭", pinyin: "kǎoyā", de: "Pekingente", en: "roast duck", es: "pato asado", hi: "भुनी बतख", cat: "Essen", icon: "🦆" },
  { char: "科学", pinyin: "kēxué", de: "Wissenschaft", en: "science", es: "ciencia", hi: "विज्ञान", cat: "Schule", icon: "🔬" },
  { char: "可是", pinyin: "kěshì", de: "Aber", en: "but", es: "pero", hi: "लेकिन", cat: "Grammatik", icon: "↩️" },
  { char: "可惜", pinyin: "kěxī", de: "Schade", en: "pity", es: "lástima", hi: "अफ़सोस", cat: "Emotion", icon: "😢" },
  { char: "客厅", pinyin: "kètīng", de: "Wohnzimmer", en: "living room", es: "salón", hi: "लिविंग रूम", cat: "Orte", icon: "🛋️" },
  { char: "肯定", pinyin: "kěndìng", de: "Sicher", en: "certain", es: "seguro", hi: "निश्चित", cat: "Adverb", icon: "💯" },
  { char: "空气", pinyin: "kōngqì", de: "Luft", en: "air", es: "aire", hi: "हवा", cat: "Natur", icon: "💨" },
  { char: "空调", pinyin: "kōngtiáo", de: "Klimaanlage", en: "air conditioner", es: "aire acondicionado", hi: "एयर कंडीशनर", cat: "Dinge", icon: "❄️" },
  { char: "恐怕", pinyin: "kǒngpà", de: "Befürchten", en: "afraid", es: "temer", hi: "शायद", cat: "Adverb", icon: "😰" },
  { char: "矿泉水", pinyin: "kuàngquánshuǐ", de: "Mineralwasser", en: "mineral water", es: "agua mineral", hi: "मिनरल वाटर", cat: "Essen", icon: "💧" },
  { char: "困难", pinyin: "kùnnán", de: "Schwierigkeit", en: "difficulty", es: "dificultad", hi: "कठिनाई", cat: "Geist", icon: "🧗" },
  { char: "垃圾桶", pinyin: "lājītǒng", de: "Mülleimer", en: "trash can", es: "papelera", hi: "कूड़ेदान", cat: "Dinge", icon: "🗑️" },
  { char: "来不及", pinyin: "láibují", de: "Zu spät", en: "too late", es: "demasiado tarde", hi: "देर हो गई", cat: "Zeit", icon: "⏰" },
  { char: "来得及", pinyin: "láidejí", de: "Rechtzeitig", en: "in time", es: "a tiempo", hi: "समय पर", cat: "Zeit", icon: "✅" },
  { char: "懒", pinyin: "lǎn", de: "Faul", en: "lazy", es: "perezoso", hi: "आलसी", cat: "Adjektive", icon: "🦥" },
  { char: "浪费", pinyin: "làngfèi", de: "Verschwenden", en: "waste", es: "desperdiciar", hi: "बर्बाद", cat: "Verben", icon: "🗑️" },
  { char: "浪漫", pinyin: "làngmàn", de: "Romantisch", en: "romantic", es: "romántico", hi: "रोमांटिक", cat: "Adjektive", icon: "🌹" },
  { char: "老虎", pinyin: "lǎohǔ", de: "Tiger", en: "tiger", es: "tigre", hi: "बाघ", cat: "Natur", icon: "🐅" },
  { char: "冷静", pinyin: "lěngjìng", de: "Ruhig", en: "calm", es: "calmado", hi: "शांत", cat: "Adjektive", icon: "🧊" },
  { char: "理发", pinyin: "lǐfà", de: "Friseur", en: "haircut", es: "corte de pelo", hi: "बाल कटवाना", cat: "Aktionen", icon: "💇" },
  { char: "理解", pinyin: "lǐjiě", de: "Verstehen", en: "understand", es: "entender", hi: "समझना", cat: "Geist", icon: "💡" },
  { char: "理想", pinyin: "lǐxiǎng", de: "Ideal", en: "ideal", es: "ideal", hi: "आदर्श", cat: "Geist", icon: "✨" },
  { char: "力气", pinyin: "lìqi", de: "Kraft", en: "strength", es: "fuerza", hi: "ताक़त", cat: "Mensch", icon: "💪" },
  { char: "厉害", pinyin: "lìhai", de: "Beeindruckend", en: "awesome", es: "impresionante", hi: "कमाल", cat: "Adjektive", icon: "🔥" },
  { char: "例如", pinyin: "lìrú", de: "Zum Beispiel", en: "for example", es: "por ejemplo", hi: "उदाहरण के लिए", cat: "Grammatik", icon: "📝" },
  { char: "联系", pinyin: "liánxì", de: "Kontakt", en: "contact", es: "contacto", hi: "संपर्क", cat: "Verben", icon: "📞" },
  { char: "凉快", pinyin: "liángkuai", de: "Kühl", en: "cool", es: "fresco", hi: "ठंडा", cat: "Wetter", icon: "🌬️" },
  { char: "另外", pinyin: "lìngwài", de: "Außerdem", en: "besides", es: "además", hi: "इसके अलावा", cat: "Grammatik", icon: "➕" },
  { char: "流利", pinyin: "liúlì", de: "Fließend", en: "fluent", es: "fluido", hi: "धाराप्रवाह", cat: "Adjektive", icon: "🗣️" },
  { char: "流行", pinyin: "liúxíng", de: "Beliebt", en: "popular", es: "popular", hi: "लोकप्रिय", cat: "Adjektive", icon: "📈" },
  { char: "律师", pinyin: "lǜshī", de: "Anwalt", en: "lawyer", es: "abogado", hi: "वकील", cat: "Personen", icon: "⚖️" },
  { char: "乱", pinyin: "luàn", de: "Unordentlich", en: "messy", es: "desordenado", hi: "अव्यवस्थित", cat: "Adjektive", icon: "🌀" },
  { char: "麻烦", pinyin: "máfan", de: "Ärger", en: "trouble", es: "molestia", hi: "परेशानी", cat: "Adjektive", icon: "😫" },
  { char: "满", pinyin: "mǎn", de: "Voll", en: "full", es: "lleno", hi: "भरा हुआ", cat: "Adjektive", icon: "🈵" },
  { char: "毛", pinyin: "máo", de: "Haar", en: "hair", es: "pelo", hi: "बाल", cat: "Mensch", icon: "🧶" },
  { char: "毛巾", pinyin: "máojīn", de: "Handtuch", en: "towel", es: "toalla", hi: "तौलिया", cat: "Dinge", icon: "🧴" },
  { char: "美丽", pinyin: "měilì", de: "Schön", en: "beautiful", es: "hermoso", hi: "सुंदर", cat: "Adjektive", icon: "🌸" },
  { char: "梦", pinyin: "mèng", de: "Traum", en: "dream", es: "sueño", hi: "सपना", cat: "Geist", icon: "💭" },
  { char: "密码", pinyin: "mìmǎ", de: "Passwort", en: "password", es: "contraseña", hi: "पासवर्ड", cat: "Dinge", icon: "🔐" },
  { char: "免费", pinyin: "miǎnfèi", de: "Kostenlos", en: "free", es: "gratis", hi: "मुफ़्त", cat: "Adjektive", icon: "🆓" },
  { char: "目的", pinyin: "mùdì", de: "Ziel", en: "purpose", es: "propósito", hi: "उद्देश्य", cat: "Geist", icon: "🎯" },
  { char: "内容", pinyin: "nèiróng", de: "Inhalt", en: "content", es: "contenido", hi: "सामग्री", cat: "Dinge", icon: "📦" },
  { char: "耐心", pinyin: "nàixīn", de: "Geduld", en: "patience", es: "paciencia", hi: "धैर्य", cat: "Emotion", icon: "🧘" },
  { char: "难受", pinyin: "nánshòu", de: "Unwohl", en: "uncomfortable", es: "incómodo", hi: "असहज", cat: "Gefühle", icon: "😣" },
  { char: "能力", pinyin: "nénglì", de: "Fähigkeit", en: "ability", es: "habilidad", hi: "क्षमता", cat: "Geist", icon: "💪" },
  { char: "年龄", pinyin: "niánlíng", de: "Alter", en: "age", es: "edad", hi: "उम्र", cat: "Mensch", icon: "🎂" },
  { char: "农村", pinyin: "nóngcūn", de: "Land", en: "countryside", es: "campo", hi: "गाँव", cat: "Orte", icon: "🏕️" },
  { char: "暖和", pinyin: "nuǎnhuo", de: "Warm", en: "warm", es: "cálido", hi: "गर्म", cat: "Wetter", icon: "☀️" },
  { char: "偶尔", pinyin: "ǒuěr", de: "Gelegentlich", en: "occasionally", es: "ocasionalmente", hi: "कभी-कभी", cat: "Adverb", icon: "🎲" }
];

// HSK 5 Vocabulary (First 100 words)
