// HSK 1 Vocabulary (150 words)
export const hsk1Vocab = [
  { char: "我", pinyin: "wǒ", de: "ich", en: "I", es: "yo", cat: "Pronomen", icon: "👤" },
  { char: "你", pinyin: "nǐ", de: "du", en: "you", es: "tú", cat: "Pronomen", icon: "👈" },
  { char: "他", pinyin: "tā", de: "er", en: "he", es: "él", cat: "Pronomen", icon: "👨" },
  { char: "她", pinyin: "tā", de: "sie", en: "she", es: "ella", cat: "Pronomen", icon: "👩" },
  { char: "我们", pinyin: "wǒ men", de: "wir", en: "we", es: "nosotros", cat: "Pronomen", icon: "👥" },
  { char: "这", pinyin: "zhè", de: "dies", en: "this", es: "este", cat: "Pronomen", icon: "📍" },
  { char: "那", pinyin: "nà", de: "jenes", en: "that", es: "eso", cat: "Pronomen", icon: "👉" },
  { char: "谁", pinyin: "shéi", de: "wer", en: "who", es: "quién", cat: "Pronomen", icon: "🕵️" },
  { char: "什么", pinyin: "shén me", de: "was", en: "what", es: "qué", cat: "Pronomen", icon: "🤔" },
  { char: "怎么", pinyin: "zěn me", de: "wie", en: "how", es: "cómo", cat: "Pronomen", icon: "⚙️" },
  { char: "一", pinyin: "yī", de: "eins", en: "one", es: "uno", cat: "Zahlen", icon: "1️⃣" },
  { char: "二", pinyin: "èr", de: "zwei", en: "two", es: "dos", cat: "Zahlen", icon: "2️⃣" },
  { char: "三", pinyin: "sān", de: "drei", en: "three", es: "tres", cat: "Zahlen", icon: "3️⃣" },
  { char: "四", pinyin: "sì", de: "vier", en: "four", es: "cuatro", cat: "Zahlen", icon: "4️⃣" },
  { char: "五", pinyin: "wǔ", de: "fünf", en: "five", es: "cinco", cat: "Zahlen", icon: "5️⃣" },
  { char: "六", pinyin: "liù", de: "sechs", en: "six", es: "seis", cat: "Zahlen", icon: "6️⃣" },
  { char: "七", pinyin: "qī", de: "sieben", en: "seven", es: "siete", cat: "Zahlen", icon: "7️⃣" },
  { char: "八", pinyin: "bā", de: "acht", en: "eight", es: "ocho", cat: "Zahlen", icon: "8️⃣" },
  { char: "九", pinyin: "jiǔ", de: "neun", en: "nine", es: "nueve", cat: "Zahlen", icon: "9️⃣" },
  { char: "十", pinyin: "shí", de: "zehn", en: "ten", es: "diez", cat: "Zahlen", icon: "🔟" },
  { char: "零", pinyin: "líng", de: "null", en: "zero", es: "cero", cat: "Zahlen", icon: "0️⃣" },
  { char: "百", pinyin: "bǎi", de: "hundert", en: "hundred", es: "cien", cat: "Zahlen", icon: "💯" },
  { char: "今天", pinyin: "jīn tiān", de: "heute", en: "today", es: "hoy", cat: "Zeit", icon: "📅" },
  { char: "明天", pinyin: "míng tiān", de: "morgen", en: "tomorrow", es: "mañana", cat: "Zeit", icon: "⏩" },
  { char: "昨天", pinyin: "zuó tiān", de: "gestern", en: "yesterday", es: "ayer", cat: "Zeit", icon: "⏪" },
  { char: "年", pinyin: "nián", de: "Jahr", en: "year", es: "año", cat: "Zeit", icon: "🎇" },
  { char: "月", pinyin: "yuè", de: "Monat", en: "month", es: "mes", cat: "Zeit", icon: "🌙" },
  { char: "日", pinyin: "rì", de: "Tag", en: "day", es: "día", cat: "Zeit", icon: "🌞" },
  { char: "星期", pinyin: "xīng qī", de: "Woche", en: "week", es: "semana", cat: "Zeit", icon: "📆" },
  { char: "现在", pinyin: "xiàn zài", de: "jetzt", en: "now", es: "ahora", cat: "Zeit", icon: "⏱️" },
  { char: "家", pinyin: "jiā", de: "Zuhause", en: "home", es: "casa", cat: "Orte", icon: "🏠" },
  { char: "学校", pinyin: "xué xiào", de: "Schule", en: "school", es: "escuela", cat: "Orte", icon: "🏫" },
  { char: "饭店", pinyin: "fàn diàn", de: "Restaurant", en: "restaurant", es: "restaurante", cat: "Orte", icon: "🍜" },
  { char: "商店", pinyin: "shāng diàn", de: "Laden", en: "shop", es: "tienda", cat: "Orte", icon: "🛒" },
  { char: "医院", pinyin: "yī yuàn", de: "Krankenhaus", en: "hospital", es: "hospital", cat: "Orte", icon: "🏥" },
  { char: "中国", pinyin: "zhōng guó", de: "China", en: "China", es: "China", cat: "Orte", icon: "🇨🇳" },
  { char: "北京", pinyin: "běi jīng", de: "Peking", en: "Beijing", es: "Pekín", cat: "Orte", icon: "🏯" },
  { char: "爸爸", pinyin: "bà ba", de: "Papa", en: "dad", es: "papá", cat: "Personen", icon: "🧔" },
  { char: "妈妈", pinyin: "mā ma", de: "Mama", en: "mom", es: "mamá", cat: "Personen", icon: "👩" },
  { char: "老师", pinyin: "lǎo shī", de: "Lehrer", en: "teacher", es: "profesor", cat: "Personen", icon: "👨‍🏫" },
  { char: "学生", pinyin: "xué sheng", de: "Schüler", en: "student", es: "estudiante", cat: "Personen", icon: "🎒" },
  { char: "朋友", pinyin: "péng you", de: "Freund", en: "friend", es: "amigo", cat: "Personen", icon: "👫" },
  { char: "医生", pinyin: "yī shēng", de: "Arzt", en: "doctor", es: "médico", cat: "Personen", icon: "🩺" },
  { char: "人", pinyin: "rén", de: "Mensch", en: "person", es: "persona", cat: "Personen", icon: "👤" },
  { char: "水", pinyin: "shuǐ", de: "Wasser", en: "water", es: "agua", cat: "Essen", icon: "💧" },
  { char: "茶", pinyin: "chá", de: "Tee", en: "tea", es: "té", cat: "Essen", icon: "🍵" },
  { char: "米饭", pinyin: "mǐ fàn", de: "Reis", en: "rice", es: "arroz", cat: "Essen", icon: "🍚" },
  { char: "苹果", pinyin: "píng guǒ", de: "Apfel", en: "apple", es: "manzana", cat: "Essen", icon: "🍎" },
  { char: "钱", pinyin: "qián", de: "Geld", en: "money", es: "dinero", cat: "Dinge", icon: "💰" },
  { char: "飞机", pinyin: "fēi jī", de: "Flugzeug", en: "airplane", es: "avión", cat: "Dinge", icon: "✈️" },
  { char: "电视", pinyin: "diàn shì", de: "TV", en: "TV", es: "tele", cat: "Dinge", icon: "📺" },
  { char: "电脑", pinyin: "diàn nǎo", de: "Computer", en: "computer", es: "ordenador", cat: "Dinge", icon: "💻" },
  { char: "书", pinyin: "shū", de: "Buch", en: "book", es: "libro", cat: "Dinge", icon: "📕" },
  { char: "猫", pinyin: "māo", de: "Katze", en: "cat", es: "gato", cat: "Natur", icon: "🐱" },
  { char: "狗", pinyin: "gǒu", de: "Hund", en: "dog", es: "perro", cat: "Natur", icon: "🐶" },
  { char: "天气", pinyin: "tiān qì", de: "Wetter", en: "weather", es: "clima", cat: "Natur", icon: "☁️" },
  { char: "名字", pinyin: "míng zi", de: "Name", en: "name", es: "nombre", cat: "Dinge", icon: "📛" },
  { char: "谢谢", pinyin: "xiè xie", de: "danke", en: "thanks", es: "gracias", cat: "Verben", icon: "🙏" },
  { char: "再见", pinyin: "zài jiàn", de: "tschüss", en: "bye", es: "adiós", cat: "Verben", icon: "👋" },
  { char: "请", pinyin: "qǐng", de: "bitte", en: "please", es: "por favor", cat: "Verben", icon: "👐" },
  { char: "是", pinyin: "shì", de: "sein", en: "be", es: "ser", cat: "Verben", icon: "✅" },
  { char: "有", pinyin: "yǒu", de: "haben", en: "have", es: "tener", cat: "Verben", icon: "🤲" },
  { char: "看", pinyin: "kàn", de: "sehen", en: "look", es: "ver", cat: "Verben", icon: "👁️" },
  { char: "听", pinyin: "tīng", de: "hören", en: "listen", es: "escuchar", cat: "Verben", icon: "👂" },
  { char: "说", pinyin: "shuō", de: "sagen", en: "speak", es: "hablar", cat: "Verben", icon: "🗣️" },
  { char: "读", pinyin: "dú", de: "lesen", en: "read", es: "leer", cat: "Verben", icon: "📖" },
  { char: "写", pinyin: "xiě", de: "schreiben", en: "write", es: "escribir", cat: "Verben", icon: "✍️" },
  { char: "叫", pinyin: "jiào", de: "heißen", en: "be called", es: "llamarse", cat: "Verben", icon: "📛" },
  { char: "来", pinyin: "lái", de: "kommen", en: "come", es: "venir", cat: "Verben", icon: "🚶" },
  { char: "去", pinyin: "qù", de: "gehen", en: "go", es: "ir", cat: "Verben", icon: "🏃" },
  { char: "吃", pinyin: "chī", de: "essen", en: "eat", es: "comer", cat: "Verben", icon: "👄" },
  { char: "喝", pinyin: "hē", de: "trinken", en: "drink", es: "beber", cat: "Verben", icon: "🥤" },
  { char: "睡觉", pinyin: "shuì jiào", de: "schlafen", en: "sleep", es: "dormir", cat: "Verben", icon: "😴" },
  { char: "做", pinyin: "zuò", de: "machen", en: "do", es: "hacer", cat: "Verben", icon: "🔨" },
  { char: "买", pinyin: "mǎi", de: "kaufen", en: "buy", es: "comprar", cat: "Verben", icon: "🛍️" },
  { char: "住", pinyin: "zhù", de: "wohnen", en: "live", es: "vivir", cat: "Verben", icon: "🏘️" },
  { char: "学习", pinyin: "xué xí", de: "lernen", en: "study", es: "estudiar", cat: "Verben", icon: "📚" },
  { char: "工作", pinyin: "gōng zuò", de: "arbeiten", en: "work", es: "trabajar", cat: "Verben", icon: "💼" },
  { char: "爱", pinyin: "ài", de: "lieben", en: "love", es: "amar", cat: "Gefühle", icon: "❤️" },
  { char: "喜欢", pinyin: "xǐ huan", de: "mögen", en: "like", es: "gustar", cat: "Gefühle", icon: "🥰" },
  { char: "想", pinyin: "xiǎng", de: "denken", en: "think", es: "pensar", cat: "Gefühle", icon: "🧠" },
  { char: "会", pinyin: "huì", de: "können", en: "can", es: "saber", cat: "Verben", icon: "🎓" },
  { char: "能", pinyin: "néng", de: "können", en: "can", es: "poder", cat: "Verben", icon: "💪" },
  { char: "好", pinyin: "hǎo", de: "gut", en: "good", es: "bueno", cat: "Adjektive", icon: "👍" },
  { char: "大", pinyin: "dà", de: "groß", en: "big", es: "grande", cat: "Adjektive", icon: "🐘" },
  { char: "小", pinyin: "xiǎo", de: "klein", en: "small", es: "pequeño", cat: "Adjektive", icon: "🐭" },
  { char: "多", pinyin: "duō", de: "viel", en: "many", es: "mucho", cat: "Adjektive", icon: "➕" },
  { char: "少", pinyin: "shǎo", de: "wenig", en: "few", es: "poco", cat: "Adjektive", icon: "➖" },
  { char: "冷", pinyin: "lěng", de: "kalt", en: "cold", es: "frío", cat: "Wetter", icon: "❄️" },
  { char: "热", pinyin: "rè", de: "heiß", en: "hot", es: "caliente", cat: "Wetter", icon: "🔥" },
  { char: "高兴", pinyin: "gāo xìng", de: "froh", en: "happy", es: "feliz", cat: "Gefühle", icon: "😊" },
  { char: "漂亮", pinyin: "piào liang", de: "hübsch", en: "pretty", es: "hermoso", cat: "Adjektive", icon: "✨" },
  { char: "不", pinyin: "bù", de: "nicht", en: "not", es: "no", cat: "Grammatik", icon: "❌" },
  { char: "很", pinyin: "hěn", de: "sehr", en: "very", es: "muy", cat: "Grammatik", icon: "🚀" },
  { char: "都", pinyin: "dōu", de: "alle", en: "all", es: "todos", cat: "Grammatik", icon: "🌎" },
  { char: "和", pinyin: "hé", de: "und", en: "and", es: "y", cat: "Grammatik", icon: "➕" },
  { char: "在", pinyin: "zài", de: "in/bei", en: "at/in", es: "en", cat: "Grammatik", icon: "📍" },
  { char: "的", pinyin: "de", de: "Besitz-P.", en: "possessive", es: "posesivo", cat: "Grammatik", icon: "🔗" }
];

// HSK 2 Vocabulary (150 words)
export const hsk2Vocab = [
  { char: "帮助", pinyin: "bāngzhù", de: "helfen", en: "help", es: "ayudar", cat: "Aktionen", icon: "🤝" },
  { char: "报纸", pinyin: "bàozhǐ", de: "Zeitung", en: "newspaper", es: "periódico", cat: "Dinge", icon: "📰" },
  { char: "比", pinyin: "bǐ", de: "vergleichen", en: "than", es: "que", cat: "Grammatik", icon: "⚖️" },
  { char: "别", pinyin: "bié", de: "nicht", en: "don't", es: "no", cat: "Grammatik", icon: "⛔" },
  { char: "长", pinyin: "cháng", de: "lang", en: "long", es: "largo", cat: "Adjektive", icon: "📏" },
  { char: "唱歌", pinyin: "chànggē", de: "singen", en: "sing", es: "cantar", cat: "Hobby", icon: "🎤" },
  { char: "穿", pinyin: "chuān", de: "tragen", en: "wear", es: "vestir", cat: "Verben", icon: "🧥" },
  { char: "错", pinyin: "cuò", de: "falsch", en: "wrong", es: "falso", cat: "Adjektive", icon: "❌" },
  { char: "打篮球", pinyin: "dǎ lánqiú", de: "Basketball", en: "basketball", es: "baloncesto", cat: "Sport", icon: "🏀" },
  { char: "但是", pinyin: "dànshì", de: "aber", en: "but", es: "pero", cat: "Grammatik", icon: "🚦" },
  { char: "到", pinyin: "dào", de: "ankommen", en: "arrive", es: "llegar", cat: "Verben", icon: "🏁" },
  { char: "等", pinyin: "děng", de: "warten", en: "wait", es: "esperar", cat: "Verben", icon: "⏳" },
  { char: "弟弟", pinyin: "dìdi", de: "Bruder", en: "brother", es: "hermano menor", cat: "Personen", icon: "👶" },
  { char: "第一", pinyin: "dì-yī", de: "erster", en: "first", es: "primero", cat: "Zahlen", icon: "🥇" },
  { char: "懂", pinyin: "dǒng", de: "verstehen", en: "understand", es: "entender", cat: "Geist", icon: "💡" },
  { char: "对", pinyin: "duì", de: "richtig", en: "correct", es: "correcto", cat: "Adjektive", icon: "✅" },
  { char: "房间", pinyin: "fángjiān", de: "Zimmer", en: "room", es: "habitación", cat: "Orte", icon: "🛌" },
  { char: "非常", pinyin: "fēicháng", de: "sehr", en: "very", es: "muy", cat: "Adverb", icon: "✨" },
  { char: "高", pinyin: "gāo", de: "hoch", en: "high", es: "alto", cat: "Adjektive", icon: "🏔️" },
  { char: "告诉", pinyin: "gàosu", de: "sagen", en: "tell", es: "decir", cat: "Aktionen", icon: "🗣️" },
  { char: "哥哥", pinyin: "gēge", de: "Bruder", en: "brother", es: "hermano mayor", cat: "Personen", icon: "👦" },
  { char: "给", pinyin: "gěi", de: "geben", en: "give", es: "dar", cat: "Verben", icon: "🎁" },
  { char: "公共汽车", pinyin: "gōnggòngqìchē", de: "Bus", en: "bus", es: "autobús", cat: "Verkehr", icon: "🚌" },
  { char: "公司", pinyin: "gōngsī", de: "Firma", en: "company", es: "compañía", cat: "Orte", icon: "🏢" },
  { char: "贵", pinyin: "guì", de: "teuer", en: "expensive", es: "caro", cat: "Adjektive", icon: "💎" },
  { char: "过", pinyin: "guò", de: "feiern", en: "pass", es: "pasar", cat: "Zeit", icon: "🎉" },
  { char: "还", pinyin: "hái", de: "noch", en: "still", es: "todavía", cat: "Adverb", icon: "🔁" },
  { char: "孩子", pinyin: "háizi", de: "Kind", en: "child", es: "niño", cat: "Personen", icon: "👶" },
  { char: "好吃", pinyin: "hǎochī", de: "lecker", en: "delicious", es: "delicioso", cat: "Adjektive", icon: "😋" },
  { char: "黑", pinyin: "hēi", de: "schwarz", en: "black", es: "negro", cat: "Farben", icon: "⚫" },
  { char: "红", pinyin: "hóng", de: "rot", en: "red", es: "rojo", cat: "Farben", icon: "🔴" },
  { char: "白", pinyin: "bái", de: "weiß", en: "white", es: "blanco", cat: "Farben", icon: "⚪" },
  { char: "欢迎", pinyin: "huānyíng", de: "willkommen", en: "welcome", es: "bienvenido", cat: "Verben", icon: "🎉" },
  { char: "机场", pinyin: "jīchǎng", de: "Flughafen", en: "airport", es: "aeropuerto", cat: "Orte", icon: "✈️" },
  { char: "鸡蛋", pinyin: "jīdàn", de: "Ei", en: "egg", es: "huevo", cat: "Essen", icon: "🥚" },
  { char: "教室", pinyin: "jiàoshì", de: "Klassenzimmer", en: "classroom", es: "aula", cat: "Orte", icon: "🏫" },
  { char: "姐姐", pinyin: "jiějie", de: "Schwester", en: "sister", es: "hermana mayor", cat: "Personen", icon: "👧" },
  { char: "介绍", pinyin: "jièshào", de: "vorstellen", en: "introduce", es: "presentar", cat: "Aktionen", icon: "🗣️" },
  { char: "进", pinyin: "jìn", de: "eintreten", en: "enter", es: "entrar", cat: "Verben", icon: "📥" },
  { char: "近", pinyin: "jìn", de: "nah", en: "near", es: "cerca", cat: "Adjektive", icon: "📍" },
  { char: "就", pinyin: "jiù", de: "eben", en: "just", es: "entonces", cat: "Adverb", icon: "⚡" },
  { char: "觉得", pinyin: "juéde", de: "fühlen", en: "feel", es: "sentir", cat: "Geist", icon: "💭" },
  { char: "咖啡", pinyin: "kāfēi", de: "Kaffee", en: "coffee", es: "café", cat: "Essen", icon: "☕" },
  { char: "开始", pinyin: "kāishǐ", de: "starten", en: "start", es: "empezar", cat: "Aktionen", icon: "🚀" },
  { char: "考试", pinyin: "kǎoshì", de: "Prüfung", en: "exam", es: "examen", cat: "Schule", icon: "📝" },
  { char: "可能", pinyin: "kěnéng", de: "vielleicht", en: "possible", es: "posible", cat: "Adverb", icon: "❓" },
  { char: "可以", pinyin: "kěyǐ", de: "können", en: "can", es: "poder", cat: "Verben", icon: "💪" },
  { char: "课", pinyin: "kè", de: "Unterricht", en: "class", es: "clase", cat: "Schule", icon: "📖" },
  { char: "快", pinyin: "kuài", de: "schnell", en: "fast", es: "rápido", cat: "Adjektive", icon: "⚡" },
  { char: "快乐", pinyin: "kuàilè", de: "glücklich", en: "happy", es: "feliz", cat: "Emotion", icon: "😊" },
  { char: "累", pinyin: "lèi", de: "müde", en: "tired", es: "cansado", cat: "Gefühle", icon: "😫" },
  { char: "离", pinyin: "lí", de: "fern von", en: "away from", es: "lejos de", cat: "Richtungen", icon: "🛤️" },
  { char: "两", pinyin: "liǎng", de: "zwei", en: "two", es: "dos", cat: "Zahlen", icon: "2️⃣" },
  { char: "路", pinyin: "lù", de: "Weg", en: "road", es: "camino", cat: "Orte", icon: "🛣️" },
  { char: "旅游", pinyin: "lǚyóu", de: "reisen", en: "travel", es: "viajar", cat: "Hobby", icon: "🧳" },
  { char: "卖", pinyin: "mài", de: "verkaufen", en: "sell", es: "vender", cat: "Verben", icon: "💵" },
  { char: "慢", pinyin: "màn", de: "langsam", en: "slow", es: "lento", cat: "Adjektive", icon: "🐢" },
  { char: "忙", pinyin: "máng", de: "beschäftigt", en: "busy", es: "ocupado", cat: "Adjektive", icon: "🏃‍♂️" },
  { char: "每", pinyin: "měi", de: "jeder", en: "every", es: "cada", cat: "Adverb", icon: "🔄" },
  { char: "妹妹", pinyin: "mèimei", de: "Schwester", en: "sister", es: "hermana menor", cat: "Personen", icon: "🧒" },
  { char: "门", pinyin: "mén", de: "Tür", en: "door", es: "puerta", cat: "Dinge", icon: "🚪" },
  { char: "面条", pinyin: "miàntiáo", de: "Nudeln", en: "noodles", es: "fideos", cat: "Essen", icon: "🍜" },
  { char: "牛奶", pinyin: "niúnǎi", de: "Milch", en: "milk", es: "leche", cat: "Essen", icon: "🥛" },
  { char: "旁边", pinyin: "pángbiān", de: "neben", en: "beside", es: "al lado", cat: "Richtungen", icon: "📍" },
  { char: "跑步", pinyin: "pǎobù", de: "laufen", en: "running", es: "correr", cat: "Sport", icon: "🏃" },
  { char: "便宜", pinyin: "piányi", de: "billig", en: "cheap", es: "barato", cat: "Adjektive", icon: "🏷️" },
  { char: "票", pinyin: "piào", de: "Ticket", en: "ticket", es: "billete", cat: "Dinge", icon: "🎟️" },
  { char: "起床", pinyin: "qǐchuáng", de: "aufstehen", en: "get up", es: "levantarse", cat: "Aktionen", icon: "🌅" },
  { char: "千", pinyin: "qiān", de: "tausend", en: "thousand", es: "mil", cat: "Zahlen", icon: "🔢" },
  { char: "晴", pinyin: "qíng", de: "sonnig", en: "sunny", es: "soleado", cat: "Wetter", icon: "☀️" },
  { char: "让", pinyin: "ràng", de: "lassen", en: "let", es: "dejar", cat: "Verben", icon: "👤" },
  { char: "上班", pinyin: "shàngbān", de: "arbeiten", en: "work", es: "ir al trabajo", cat: "Aktionen", icon: "💼" },
  { char: "身体", pinyin: "shēntǐ", de: "Körper", en: "body", es: "cuerpo", cat: "Mensch", icon: "💪" },
  { char: "生病", pinyin: "shēngbìng", de: "krank", en: "sick", es: "enfermo", cat: "Gesundheit", icon: "🤒" },
  { char: "生日", pinyin: "shēngrì", de: "Geburtstag", en: "birthday", es: "cumpleaños", cat: "Zeit", icon: "🎂" },
  { char: "时间", pinyin: "shíjiān", de: "Zeit", en: "time", es: "tiempo", cat: "Zeit", icon: "⏰" },
  { char: "手表", pinyin: "shǒubiǎo", de: "Uhr", en: "watch", es: "reloj", cat: "Dinge", icon: "⌚" },
  { char: "手机", pinyin: "shǒujī", de: "Handy", en: "phone", es: "móvil", cat: "Dinge", icon: "📱" },
  { char: "踢足球", pinyin: "tī zúqiú", de: "Fußball", en: "football", es: "fútbol", cat: "Sport", icon: "⚽" },
  { char: "跳舞", pinyin: "tiàowǔ", de: "tanzen", en: "dance", es: "bailar", cat: "Hobby", icon: "💃" },
  { char: "玩", pinyin: "wán", de: "spielen", en: "play", es: "jugar", cat: "Hobby", icon: "🎮" },
  { char: "晚上", pinyin: "wǎnshang", de: "Abend", en: "evening", es: "noche", cat: "Zeit", icon: "🌙" },
  { char: "为什么", pinyin: "wèishénme", de: "warum", en: "why", es: "por qué", cat: "Pronomen", icon: "❔" },
  { char: "问", pinyin: "wèn", de: "fragen", en: "ask", es: "preguntar", cat: "Verben", icon: "❓" },
  { char: "问题", pinyin: "wèntí", de: "Problem", en: "problem", es: "problema", cat: "Geist", icon: "💡" },
  { char: "希望", pinyin: "xīwàng", de: "hoffen", en: "hope", es: "esperar", cat: "Geist", icon: "🌟" },
  { char: "洗", pinyin: "xǐ", de: "waschen", en: "wash", es: "lavar", cat: "Verben", icon: "🧼" },
  { char: "笑", pinyin: "xiào", de: "lachen", en: "laugh", es: "reír", cat: "Emotion", icon: "😄" },
  { char: "休息", pinyin: "xiūxi", de: "ausruhen", en: "rest", es: "descansar", cat: "Verben", icon: "🛌" },
  { char: "雪", pinyin: "xuě", de: "Schnee", en: "snow", es: "nieve", cat: "Wetter", icon: "❄️" },
  { char: "颜色", pinyin: "yánsè", de: "Farbe", en: "color", es: "color", cat: "Dinge", icon: "🎨" },
  { char: "眼睛", pinyin: "yǎnjing", de: "Auge", en: "eye", es: "ojo", cat: "Mensch", icon: "👁️" },
  { char: "药", pinyin: "yào", de: "Medizin", en: "medicine", es: "medicina", cat: "Gesundheit", icon: "💊" },
  { char: "要", pinyin: "yào", de: "wollen", en: "want", es: "querer", cat: "Verben", icon: "🎯" },
  { char: "也", pinyin: "yě", de: "auch", en: "also", es: "también", cat: "Adverb", icon: "➕" },
  { char: "一起", pinyin: "yīqǐ", de: "zusammen", en: "together", es: "junto", cat: "Verben", icon: "👫" },
  { char: "已经", pinyin: "yǐjīng", de: "bereits", en: "already", es: "ya", cat: "Adverb", icon: "⏳" },
  { char: "意思", pinyin: "yìsi", de: "Bedeutung", en: "meaning", es: "significado", cat: "Geist", icon: "📖" },
  { char: "因为", pinyin: "yīnwèi", de: "weil", en: "because", es: "porque", cat: "Grammatik", icon: "ℹ️" },
  { char: "游泳", pinyin: "yóuyǒng", de: "schwimmen", en: "swimming", es: "nadar", cat: "Sport", icon: "🏊" },
  { char: "右边", pinyin: "yòubian", de: "rechts", en: "right side", es: "derecha", cat: "Richtungen", icon: "👉" },
  { char: "鱼", pinyin: "yú", de: "Fisch", en: "fish", es: "pescado", cat: "Essen", icon: "🐟" },
  { char: "远", pinyin: "yuǎn", de: "weit", en: "far", es: "lejos", cat: "Adjektive", icon: "🔭" },
  { char: "运动", pinyin: "yùndòng", de: "Sport", en: "sport", es: "deporte", cat: "Sport", icon: "🏃" },
  { char: "再", pinyin: "zài", de: "wieder", en: "again", es: "otra vez", cat: "Adverb", icon: "🔁" },
  { char: "早上", pinyin: "zǎoshang", de: "Morgen", en: "morning", es: "mañana", cat: "Zeit", icon: "🌅" },
  { char: "丈夫", pinyin: "zhàngfu", de: "Ehemann", en: "husband", es: "esposo", cat: "Personen", icon: "🤵" },
  { char: "找", pinyin: "zhǎo", de: "suchen", en: "find", es: "buscar", cat: "Verben", icon: "🔍" },
  { char: "真", pinyin: "zhēn", de: "wirklich", en: "really", es: "verdadero", cat: "Adverb", icon: "💎" },
  { char: "正在", pinyin: "zhèngzài", de: "gerade", en: "currently", es: "ahora mismo", cat: "Adverb", icon: "🕐" },
  { char: "知道", pinyin: "zhīdao", de: "wissen", en: "know", es: "saber", cat: "Geist", icon: "🧠" },
  { char: "准备", pinyin: "zhǔnbèi", de: "vorbereiten", en: "prepare", es: "preparar", cat: "Aktionen", icon: "📝" },
  { char: "自行车", pinyin: "zìxíngchē", de: "Fahrrad", en: "bicycle", es: "bicicleta", cat: "Verkehr", icon: "🚲" },
  { char: "走", pinyin: "zǒu", de: "gehen", en: "walk", es: "caminar", cat: "Verben", icon: "🚶" },
  { char: "最", pinyin: "zuì", de: "meiste", en: "most", es: "más", cat: "Adverb", icon: "🔝" },
  { char: "左边", pinyin: "zuǒbian", de: "links", en: "left side", es: "izquierda", cat: "Richtungen", icon: "👈" }
];

// HSK 3 Vocabulary (Sample - 80 words)
export const hsk3Vocab = [
  { char: "阿姨", pinyin: "āyí", de: "Tante", en: "aunt", es: "tía", cat: "Personen", icon: "👩" },
  { char: "安静", pinyin: "ānjìng", de: "ruhig", en: "quiet", es: "tranquilo", cat: "Adjektive", icon: "🤫" },
  { char: "把", pinyin: "bǎ", de: "fassen", en: "grasp", es: "agarrar", cat: "Grammatik", icon: "✊" },
  { char: "搬", pinyin: "bān", de: "umziehen", en: "move", es: "mudarse", cat: "Aktionen", icon: "📦" },
  { char: "办法", pinyin: "bànfǎ", de: "Methode", en: "method", es: "método", cat: "Geist", icon: "💡" },
  { char: "办公室", pinyin: "bàngōngshì", de: "Büro", en: "office", es: "oficina", cat: "Orte", icon: "🏢" },
  { char: "包", pinyin: "bāo", de: "Tasche", en: "bag", es: "bolsa", cat: "Dinge", icon: "👜" },
  { char: "比较", pinyin: "bǐjiào", de: "vergleichen", en: "compare", es: "comparar", cat: "Adverb", icon: "⚖️" },
  { char: "比赛", pinyin: "bǐsài", de: "Wettbewerb", en: "match", es: "partido", cat: "Sport", icon: "⚽" },
  { char: "必须", pinyin: "bìxū", de: "müssen", en: "must", es: "deber", cat: "Adverb", icon: "⚠️" },
  { char: "变化", pinyin: "biànhuà", de: "Änderung", en: "change", es: "cambio", cat: "Geist", icon: "🔄" },
  { char: "宾馆", pinyin: "bīnguǎn", de: "Hotel", en: "hotel", es: "hotel", cat: "Orte", icon: "🏨" },
  { char: "冰箱", pinyin: "bīngxiāng", de: "Kühlschrank", en: "fridge", es: "nevera", cat: "Dinge", icon: "🧊" },
  { char: "菜单", pinyin: "càidān", de: "Menü", en: "menu", es: "menú", cat: "Dinge", icon: "📜" },
  { char: "参加", pinyin: "cānjiā", de: "teilnehmen", en: "participate", es: "participar", cat: "Aktionen", icon: "🙋" },
  { char: "超市", pinyin: "chāoshì", de: "Supermarkt", en: "supermarket", es: "supermercado", cat: "Orte", icon: "🛒" },
  { char: "成绩", pinyin: "chéngjì", de: "Note", en: "score", es: "nota", cat: "Schule", icon: "💯" },
  { char: "城市", pinyin: "chéngshì", de: "Stadt", en: "city", es: "ciudad", cat: "Orte", icon: "🏙️" },
  { char: "迟到", pinyin: "chídào", de: "zu spät", en: "late", es: "tarde", cat: "Aktionen", icon: "⏰" },
  { char: "厨房", pinyin: "chúfáng", de: "Küche", en: "kitchen", es: "cocina", cat: "Orte", icon: "🍳" },
  { char: "春", pinyin: "chūn", de: "Frühling", en: "spring", es: "primavera", cat: "Zeit", icon: "🌱" },
  { char: "聪明", pinyin: "cōngmíng", de: "klug", en: "smart", es: "listo", cat: "Adjektive", icon: "🧠" },
  { char: "打扫", pinyin: "dǎsǎo", de: "putzen", en: "clean", es: "limpiar", cat: "Aktionen", icon: "🧹" },
  { char: "打算", pinyin: "dǎsuàn", de: "planen", en: "plan", es: "planear", cat: "Geist", icon: "📅" },
  { char: "担心", pinyin: "dānxīn", de: "sorgen", en: "worry", es: "preocuparse", cat: "Emotion", icon: "😟" },
  { char: "蛋糕", pinyin: "dàngāo", de: "Kuchen", en: "cake", es: "pastel", cat: "Essen", icon: "🍰" },
  { char: "当然", pinyin: "dāngrán", de: "natürlich", en: "of course", es: "claro", cat: "Adverb", icon: "👌" },
  { char: "地方", pinyin: "dìfang", de: "Ort", en: "place", es: "lugar", cat: "Orte", icon: "📍" },
  { char: "地铁", pinyin: "dìtiě", de: "U-Bahn", en: "subway", es: "metro", cat: "Verkehr", icon: "🚇" },
  { char: "电梯", pinyin: "diàntī", de: "Aufzug", en: "elevator", es: "ascensor", cat: "Verkehr", icon: "🛗" },
  { char: "电子邮件", pinyin: "diànzǐ yóujiàn", de: "E-Mail", en: "email", es: "correo", cat: "Dinge", icon: "📧" },
  { char: "冬", pinyin: "dōng", de: "Winter", en: "winter", es: "invierno", cat: "Zeit", icon: "❄️" },
  { char: "动物", pinyin: "dòngwù", de: "Tier", en: "animal", es: "animal", cat: "Natur", icon: "🐾" },
  { char: "锻炼", pinyin: "duànliàn", de: "trainieren", en: "exercise", es: "ejercicio", cat: "Sport", icon: "🏋️" },
  { char: "发现", pinyin: "fāxiàn", de: "entdecken", en: "discover", es: "descubrir", cat: "Verben", icon: "🔍" },
  { char: "方便", pinyin: "fāngbiàn", de: "praktisch", en: "convenient", es: "confortable", cat: "Adjektive", icon: "🛵" },
  { char: "干净", pinyin: "gānjìng", de: "sauber", en: "clean", es: "limpio", cat: "Adjektive", icon: "✨" },
  { char: "感冒", pinyin: "gǎnmào", de: "Erkältung", en: "cold", es: "resfriado", cat: "Gesundheit", icon: "🤧" },
  { char: "公园", pinyin: "gōngyuán", de: "Park", en: "park", es: "parque", cat: "Orte", icon: "🌳" },
  { char: "故事", pinyin: "gùshi", de: "Märchen", en: "story", es: "historia", cat: "Dinge", icon: "📚" },
  { char: "国家", pinyin: "guójiā", de: "Staat", en: "country", es: "país", cat: "Orte", icon: "🗺️" },
  { char: "害怕", pinyin: "hàipà", de: "Angst", en: "afraid", es: "miedo", cat: "Emotion", icon: "😨" },
  { char: "护照", pinyin: "hùzhào", de: "Pass", en: "passport", es: "pasaporte", cat: "Dinge", icon: "🛂" },
  { char: "花", pinyin: "huā", de: "Blume", en: "flower", es: "flor", cat: "Natur", icon: "🌸" },
  { char: "环境", pinyin: "huánjìng", de: "Umwelt", en: "environment", es: "ambiente", cat: "Natur", icon: "🌍" },
  { char: "会议", pinyin: "huìyì", de: "Konferenz", en: "meeting", es: "reunión", cat: "Orte", icon: "🤝" },
  { char: "机会", pinyin: "jīhuì", de: "Chance", en: "chance", es: "oportunidad", cat: "Geist", icon: "🚪" },
  { char: "记得", pinyin: "jìde", de: "erinnern", en: "remember", es: "recordar", cat: "Geist", icon: "🧠" },
  { char: "季节", pinyin: "jìjié", de: "Saison", en: "season", es: "estación", cat: "Zeit", icon: "🍂" },
  { char: "检查", pinyin: "jiǎnchá", de: "prüfen", en: "check", es: "revisar", cat: "Verben", icon: "✅" },
  { char: "简单", pinyin: "jiǎndān", de: "einfach", en: "simple", es: "simple", cat: "Adjektive", icon: "👌" },
  { char: "健康", pinyin: "jiànkāng", de: "Gesundheit", en: "healthy", es: "saludable", cat: "Gesundheit", icon: "🥗" },
  { char: "教", pinyin: "jiāo", de: "lehren", en: "teach", es: "enseñar", cat: "Schule", icon: "👨‍🏫" },
  { char: "节目", pinyin: "jiémù", de: "Sendung", en: "program", es: "programa", cat: "Dinge", icon: "📺" },
  { char: "节日", pinyin: "jiérì", de: "Fest", en: "holiday", es: "festivo", cat: "Zeit", icon: "��" },
  { char: "结婚", pinyin: "jiéhūn", de: "Ehe", en: "marry", es: "casarse", cat: "Aktionen", icon: "💍" },
  { char: "解决", pinyin: "jiějué", de: "lösen", en: "solve", es: "resolver", cat: "Verben", icon: "🔓" },
  { char: "借", pinyin: "jiè", de: "leihen", en: "borrow", es: "prestar", cat: "Verben", icon: "📖" },
  { char: "经常", pinyin: "jīngcháng", de: "oft", en: "often", es: "a menudo", cat: "Adverb", icon: "🔁" },
  { char: "经理", pinyin: "jīnglǐ", de: "Chef", en: "manager", es: "gerente", cat: "Personen", icon: "👔" },
  { char: "决定", pinyin: "juédìng", de: "Beschluss", en: "decide", es: "decidir", cat: "Geist", icon: "🤔" },
  { char: "可爱", pinyin: "kě'ài", de: "süß", en: "cute", es: "lindo", cat: "Adjektive", icon: "😻" },
  { char: "空调", pinyin: "kōngtiáo", de: "Klima", en: "AC", es: "aire", cat: "Dinge", icon: "❄️" },
  { char: "哭", pinyin: "kū", de: "weinen", en: "cry", es: "llorar", cat: "Emotion", icon: "😢" },
  { char: "筷子", pinyin: "kuàizi", de: "Stäbchen", en: "chopsticks", es: "palillos", cat: "Dinge", icon: "🥢" },
  { char: "蓝", pinyin: "lán", de: "blau", en: "blue", es: "azul", cat: "Farben", icon: "🔵" },
  { char: "礼物", pinyin: "lǐwù", de: "Geschenk", en: "gift", es: "regalo", cat: "Dinge", icon: "🎁" },
  { char: "历史", pinyin: "lìshǐ", de: "Historie", en: "history", es: "historia", cat: "Schule", icon: "📜" },
  { char: "练习", pinyin: "liànxí", de: "Übung", en: "practice", es: "practicar", cat: "Schule", icon: "🏋️" },
  { char: "绿", pinyin: "lǜ", de: "grün", en: "green", es: "verde", cat: "Farben", icon: "🟢" },
  { char: "马", pinyin: "mǎ", de: "Pferd", en: "horse", es: "caballo", cat: "Natur", icon: "🐎" },
  { char: "满意", pinyin: "mǎnyì", de: "zufrieden", en: "satisfied", es: "satisfecho", cat: "Emotion", icon: "😊" },
  { char: "面包", pinyin: "miànbāo", de: "Brot", en: "bread", es: "pan", cat: "Essen", icon: "🍞" },
  { char: "明白", pinyin: "míngbai", de: "klar", en: "understand", es: "entender", cat: "Geist", icon: "🧠" },
  { char: "奶奶", pinyin: "nǎinai", de: "Oma", en: "grandma", es: "abuela", cat: "Personen", icon: "👵" },
  { char: "难", pinyin: "nán", de: "schwer", en: "difficult", es: "difícil", cat: "Adjektive", icon: "🧩" },
  { char: "难过", pinyin: "nánguò", de: "traurig", en: "sad", es: "triste", cat: "Emotion", icon: "😔" },
  { char: "年轻", pinyin: "niánqīng", de: "jung", en: "young", es: "joven", cat: "Adjektive", icon: "👶" },
  { char: "鸟", pinyin: "niǎo", de: "Vogel", en: "bird", es: "pájaro", cat: "Natur", icon: "🐦" },
  { char: "努力", pinyin: "nǔlì", de: "fleißig", en: "hardworking", es: "esforzado", cat: "Adjektive", icon: "💪" }
];

// HSK 4 Vocabulary (Sample - 80 words)
export const hsk4Vocab = [
  { char: "爱情", pinyin: "àiqíng", de: "Liebe", en: "love", es: "amor", cat: "Emotion", icon: "❤️" },
  { char: "安排", pinyin: "ānpái", de: "Plan", en: "arrange", es: "organizar", cat: "Aktionen", icon: "📅" },
  { char: "安全", pinyin: "ānquán", de: "Sicherheit", en: "safe", es: "seguro", cat: "Adjektive", icon: "🛡️" },
  { char: "按时", pinyin: "ànshí", de: "Pünktlich", en: "on time", es: "a tiempo", cat: "Zeit", icon: "⌚" },
  { char: "保护", pinyin: "bǎohù", de: "Schutz", en: "protect", es: "proteger", cat: "Verben", icon: "🔒" },
  { char: "报名", pinyin: "bàomíng", de: "Anmeldung", en: "sign up", es: "inscribirse", cat: "Aktionen", icon: "📝" },
  { char: "抱歉", pinyin: "bàoqiàn", de: "Sorry", en: "apologize", es: "lo siento", cat: "Emotion", icon: "🙏" },
  { char: "毕业", pinyin: "bìyè", de: "Abschluss", en: "graduate", es: "graduarse", cat: "Schule", icon: "🎓" },
  { char: "表格", pinyin: "biǎogé", de: "Liste", en: "form", es: "formulario", cat: "Dinge", icon: "📋" },
  { char: "表演", pinyin: "biǎoyǎn", de: "Show", en: "perform", es: "actuar", cat: "Kultur", icon: "🎭" },
  { char: "饼干", pinyin: "bǐnggān", de: "Keks", en: "biscuit", es: "galleta", cat: "Essen", icon: "🍪" },
  { char: "博士", pinyin: "bóshì", de: "PhD", en: "doctor", es: "doctor", cat: "Personen", icon: "👨‍🎓" },
  { char: "不得不", pinyin: "bùdébù", de: "Muss", en: "have to", es: "tener que", cat: "Adverb", icon: "🤷" },
  { char: "材料", pinyin: "cáiliào", de: "Stoff", en: "material", es: "material", cat: "Dinge", icon: "🏗️" },
  { char: "参观", pinyin: "cānguān", de: "Besuch", en: "visit", es: "visitar", cat: "Aktionen", icon: "👀" },
  { char: "成功", pinyin: "chénggōng", de: "Win", en: "success", es: "éxito", cat: "Verben", icon: "🏆" },
  { char: "成为", pinyin: "chéngwéi", de: "Werden", en: "become", es: "llegar a ser", cat: "Verben", icon: "✨" },
  { char: "诚实", pinyin: "chéngshí", de: "Ehrlich", en: "honest", es: "honesto", cat: "Adjektive", icon: "😇" },
  { char: "出发", pinyin: "chūfā", de: "Go", en: "set out", es: "partir", cat: "Aktionen", icon: "🚀" },
  { char: "出生", pinyin: "chūshēng", de: "Geburt", en: "be born", es: "nacer", cat: "Verben", icon: "👶" },
  { char: "传真", pinyin: "chuánzhēn", de: "Fax", en: "fax", es: "fax", cat: "Dinge", icon: "📠" },
  { char: "窗户", pinyin: "chuānghu", de: "Fenster", en: "window", es: "ventana", cat: "Dinge", icon: "🪟" },
  { char: "存", pinyin: "cún", de: "Spar", en: "save", es: "guardar", cat: "Aktionen", icon: "🏦" },
  { char: "错误", pinyin: "cuòwù", de: "Fehler", en: "mistake", es: "error", cat: "Dinge", icon: "❌" },
  { char: "答案", pinyin: "dá'àn", de: "Antwort", en: "answer", es: "respuesta", cat: "Schule", icon: "📝" },
  { char: "打扰", pinyin: "dǎrǎo", de: "Stör", en: "disturb", es: "molestar", cat: "Verben", icon: "🚫" },
  { char: "打印", pinyin: "dǎyìn", de: "Print", en: "print", es: "imprimir", cat: "Aktionen", icon: "🖨️" },
  { char: "打折", pinyin: "dǎzhé", de: "Sale", en: "discount", es: "descuento", cat: "Aktionen", icon: "🏷️" },
  { char: "大概", pinyin: "dàgài", de: "Vielleicht", en: "probably", es: "probablemente", cat: "Adverb", icon: "🤷" },
  { char: "大使馆", pinyin: "dàshǐguǎn", de: "Botschaft", en: "embassy", es: "embajada", cat: "Orte", icon: "🏛️" },
  { char: "导游", pinyin: "dǎoyóu", de: "Guide", en: "guide", es: "guía", cat: "Personen", icon: "🚩" },
  { char: "道歉", pinyin: "dàoqiàn", de: "Sorry", en: "apologize", es: "disculparse", cat: "Aktionen", icon: "🙏" },
  { char: "地球", pinyin: "dìqiú", de: "Erde", en: "earth", es: "tierra", cat: "Natur", icon: "🌏" },
  { char: "地址", pinyin: "dìzhǐ", de: "Adr.", en: "address", es: "dirección", cat: "Dinge", icon: "🏠" },
  { char: "掉", pinyin: "diào", de: "Fall", en: "fall", es: "caer", cat: "Aktionen", icon: "🍂" },
  { char: "丢", pinyin: "diū", de: "Weg", en: "lose", es: "perder", cat: "Verben", icon: "🤷" },
  { char: "动作", pinyin: "dòngzuò", de: "Move", en: "action", es: "acción", cat: "Dinge", icon: "💃" },
  { char: "堵车", pinyin: "dǔchē", de: "Stau", en: "jam", es: "atasco", cat: "Verkehr", icon: "🚗" },
  { char: "发展", pinyin: "fāzhǎn", de: "Grow", en: "develop", es: "desarrollar", cat: "Geist", icon: "📈" },
  { char: "法律", pinyin: "fǎlǜ", de: "Law", en: "law", es: "ley", cat: "Dinge", icon: "⚖️" },
  { char: "翻译", pinyin: "fānyì", de: "Trans", en: "translate", es: "traducir", cat: "Aktionen", icon: "🔤" },
  { char: "方法", pinyin: "fāngfǎ", de: "Weg", en: "method", es: "método", cat: "Geist", icon: "💡" },
  { char: "方向", pinyin: "fāngxiàng", de: "Kurs", en: "direction", es: "dirección", cat: "Richtungen", icon: "🧭" },
  { char: "放弃", pinyin: "fàngqì", de: "Quit", en: "give up", es: "rendirse", cat: "Verben", icon: "🏳️" },
  { char: "放松", pinyin: "fàngsōng", de: "Chill", en: "relax", es: "relajarse", cat: "Emotion", icon: "😌" },
  { char: "丰富", pinyin: "fēngfù", de: "Voll", en: "rich", es: "rico", cat: "Adjektive", icon: "🌈" },
  { char: "付款", pinyin: "fùkuǎn", de: "Pay", en: "pay", es: "pagar", cat: "Aktionen", icon: "💳" },
  { char: "负责", pinyin: "fùzé", de: "Chef", en: "responsible", es: "responsable", cat: "Verben", icon: "🫡" },
  { char: "复杂", pinyin: "fùzá", de: "Wirr", en: "complex", es: "complejo", cat: "Adjektive", icon: "🌀" },
  { char: "改变", pinyin: "gǎibiàn", de: "Change", en: "change", es: "cambiar", cat: "Verben", icon: "🔄" },
  { char: "干杯", pinyin: "gānbēi", de: "Prost", en: "cheers", es: "salud", cat: "Aktionen", icon: "🍻" },
  { char: "感动", pinyin: "gǎndòng", de: "Move", en: "moved", es: "conmovido", cat: "Emotion", icon: "🥺" },
  { char: "感情", pinyin: "gǎnqíng", de: "Liebe", en: "emotion", es: "emoción", cat: "Emotion", icon: "❤️" },
  { char: "感谢", pinyin: "gǎnxiè", de: "Dank", en: "thank", es: "agradecer", cat: "Aktionen", icon: "🙏" },
  { char: "高速公路", pinyin: "gāosù gōnglù", de: "Bahn", en: "highway", es: "autopista", cat: "Verkehr", icon: "🛣️" },
  { char: "工资", pinyin: "gōngzī", de: "Cash", en: "salary", es: "salario", cat: "Dinge", icon: "💵" },
  { char: "功夫", pinyin: "gōngfu", de: "Kung Fu", en: "kung fu", es: "kung fu", cat: "Sport", icon: "🥋" },
  { char: "购物", pinyin: "gòuwù", de: "Shop", en: "shop", es: "compras", cat: "Aktionen", icon: "🛍️" },
  { char: "够", pinyin: "gòu", de: "Voll", en: "enough", es: "suficiente", cat: "Adjektive", icon: "👌" },
  { char: "鼓励", pinyin: "gǔlì", de: "Mut", en: "encourage", es: "animar", cat: "Aktionen", icon: "👏" },
  { char: "顾客", pinyin: "gùkè", de: "User", en: "customer", es: "cliente", cat: "Personen", icon: "🛒" },
  { char: "关键", pinyin: "guānjiàn", de: "Key", en: "key", es: "clave", cat: "Geist", icon: "🔑" },
  { char: "管理", pinyin: "guǎnlǐ", de: "Chef", en: "manage", es: "gestionar", cat: "Aktionen", icon: "👔" },
  { char: "广告", pinyin: "guǎnggào", de: "Ad", en: "ad", es: "anuncio", cat: "Dinge", icon: "📢" },
  { char: "规定", pinyin: "guīdìng", de: "Regel", en: "rule", es: "regla", cat: "Geist", icon: "📜" },
  { char: "国际", pinyin: "guójì", de: "Welt", en: "international", es: "internacional", cat: "Adjektive", icon: "🌐" },
  { char: "果汁", pinyin: "guǒzhī", de: "Saft", en: "juice", es: "zumo", cat: "Essen", icon: "🧃" },
  { char: "海洋", pinyin: "hǎiyáng", de: "Meer", en: "ocean", es: "océano", cat: "Natur", icon: "🌊" },
  { char: "害羞", pinyin: "hàixiū", de: "Scheu", en: "shy", es: "tímido", cat: "Emotion", icon: "😳" },
  { char: "航班", pinyin: "hángbān", de: "Flug", en: "flight", es: "vuelo", cat: "Verkehr", icon: "🛫" },
  { char: "好像", pinyin: "hǎoxiàng", de: "Gleich", en: "seem", es: "parecer", cat: "Verben", icon: "🤔" },
  { char: "号码", pinyin: "hàomǎ", de: "Nr.", en: "number", es: "número", cat: "Dinge", icon: "🔢" },
  { char: "合格", pinyin: "hégé", de: "Gut", en: "qualified", es: "apto", cat: "Adjektive", icon: "✅" },
  { char: "合适", pinyin: "héshì", de: "Passt", en: "fit", es: "adecuado", cat: "Adjektive", icon: "👌" },
  { char: "后悔", pinyin: "hòuhuǐ", de: "Reue", en: "regret", es: "arrepentirse", cat: "Emotion", icon: "😞" },
  { char: "互联网", pinyin: "hùliánwǎng", de: "Web", en: "internet", es: "internet", cat: "Dinge", icon: "🌐" },
  { char: "护士", pinyin: "hùshi", de: "Schwester", en: "nurse", es: "enfermera", cat: "Personen", icon: "👩‍⚕️" },
  { char: "回忆", pinyin: "huíyì", de: "Memo", en: "memory", es: "recuerdo", cat: "Geist", icon: "💭" },
  { char: "活泼", pinyin: "huópo", de: "Aktiv", en: "lively", es: "vivo", cat: "Adjektive", icon: "🐇" },
  { char: "获得", pinyin: "huòdé", de: "Sieg", en: "obtain", es: "obtener", cat: "Verben", icon: "🏆" },
  { char: "基础", pinyin: "jīchǔ", de: "Basis", en: "base", es: "base", cat: "Geist", icon: "🏗️" },
  { char: "激动", pinyin: "jīdòng", de: "Aufgeregt", en: "excited", es: "emocionado", cat: "Emotion", icon: "🤩" },
  { char: "即使", pinyin: "jíshǐ", de: "Auch wenn", en: "even if", es: "aunque", cat: "Grammatik", icon: "🛤️" },
  { char: "计划", pinyin: "jìhuà", de: "Plan", en: "plan", es: "plan", cat: "Geist", icon: "📅" },
  { char: "记者", pinyin: "jìzhě", de: "Reporter", en: "journalist", es: "periodista", cat: "Personen", icon: "🎤" },
  { char: "既然", pinyin: "jìrán", de: "Da", en: "since", es: "ya que", cat: "Grammatik", icon: "💁" },
  { char: "寄", pinyin: "jì", de: "Senden", en: "mail", es: "enviar", cat: "Aktionen", icon: "📮" },
  { char: "加油站", pinyin: "jiāyóuzhàn", de: "Tankstelle", en: "gas station", es: "gasolinera", cat: "Orte", icon: "⛽" },
  { char: "家具", pinyin: "jiājù", de: "Möbel", en: "furniture", es: "muebles", cat: "Dinge", icon: "🪑" },
  { char: "价格", pinyin: "jiàgé", de: "Preis", en: "price", es: "precio", cat: "Dinge", icon: "🏷️" },
  { char: "坚持", pinyin: "jiānchí", de: "Durchhalten", en: "persist", es: "insistir", cat: "Verben", icon: "✊" },
  { char: "减肥", pinyin: "jiǎnféi", de: "Abnehmen", en: "lose weight", es: "adelgazar", cat: "Aktionen", icon: "🥗" },
  { char: "减少", pinyin: "jiǎnshǎo", de: "Reduzieren", en: "reduce", es: "reducir", cat: "Verben", icon: "📉" },
  { char: "建议", pinyin: "jiànyì", de: "Vorschlag", en: "suggest", es: "sugerir", cat: "Verben", icon: "💡" },
  { char: "将来", pinyin: "jiānglái", de: "Zukunft", en: "future", es: "futuro", cat: "Zeit", icon: "🔮" },
  { char: "奖金", pinyin: "jiǎngjīn", de: "Bonus", en: "bonus", es: "bonificación", cat: "Geld", icon: "💵" },
  { char: "交通", pinyin: "jiāotōng", de: "Verkehr", en: "traffic", es: "tráfico", cat: "Verkehr", icon: "🚦" },
  { char: "交流", pinyin: "jiāoliú", de: "Austausch", en: "exchange", es: "intercambio", cat: "Verben", icon: "🗣️" },
  { char: "教授", pinyin: "jiàoshòu", de: "Professor", en: "professor", es: "profesor", cat: "Personen", icon: "👨‍🏫" },
  { char: "教育", pinyin: "jiàoyù", de: "Bildung", en: "education", es: "educación", cat: "Schule", icon: "🏫" },
  { char: "接受", pinyin: "jiēshòu", de: "Akzeptieren", en: "accept", es: "aceptar", cat: "Verben", icon: "✅" },
  { char: "结果", pinyin: "jiéguǒ", de: "Ergebnis", en: "result", es: "resultado", cat: "Geist", icon: "📊" },
  { char: "节约", pinyin: "jiéyuē", de: "Sparen", en: "save", es: "ahorrar", cat: "Verben", icon: "🐷" },
  { char: "解释", pinyin: "jiěshì", de: "Erklären", en: "explain", es: "explicar", cat: "Verben", icon: "💬" },
  { char: "紧张", pinyin: "jǐnzhāng", de: "Nervös", en: "nervous", es: "nervioso", cat: "Emotion", icon: "😬" },
  { char: "尽管", pinyin: "jǐnguǎn", de: "Obwohl", en: "although", es: "aunque", cat: "Grammatik", icon: "⚖️" },
  { char: "进行", pinyin: "jìnxíng", de: "Durchführen", en: "carry out", es: "realizar", cat: "Verben", icon: "▶️" },
  { char: "禁止", pinyin: "jìnzhǐ", de: "Verbieten", en: "prohibit", es: "prohibir", cat: "Verben", icon: "🚫" },
  { char: "精彩", pinyin: "jīngcǎi", de: "Wunderbar", en: "wonderful", es: "maravilloso", cat: "Adjektive", icon: "✨" },
  { char: "经济", pinyin: "jīngjì", de: "Wirtschaft", en: "economy", es: "economía", cat: "Geist", icon: "📈" },
  { char: "经验", pinyin: "jīngyàn", de: "Erfahrung", en: "experience", es: "experiencia", cat: "Geist", icon: "🧠" },
  { char: "警察", pinyin: "jǐngchá", de: "Polizei", en: "police", es: "policía", cat: "Personen", icon: "👮" },
  { char: "竞争", pinyin: "jìngzhēng", de: "Wettkampf", en: "compete", es: "competir", cat: "Verben", icon: "🏆" },
  { char: "镜子", pinyin: "jìngzi", de: "Spiegel", en: "mirror", es: "espejo", cat: "Dinge", icon: "🪞" },
  { char: "究竟", pinyin: "jiūjìng", de: "Eigentlich", en: "actually", es: "en realidad", cat: "Adverb", icon: "🤔" },
  { char: "举办", pinyin: "jǔbàn", de: "Veranstalten", en: "hold", es: "organizar", cat: "Aktionen", icon: "🎉" },
  { char: "拒绝", pinyin: "jùjué", de: "Ablehnen", en: "refuse", es: "rechazar", cat: "Verben", icon: "🙅" },
  { char: "距离", pinyin: "jùlí", de: "Entfernung", en: "distance", es: "distancia", cat: "Maße", icon: "📏" },
  { char: "聚会", pinyin: "jùhuì", de: "Party", en: "party", es: "fiesta", cat: "Aktionen", icon: "🎊" },
  { char: "卡", pinyin: "kǎ", de: "Karte", en: "card", es: "tarjeta", cat: "Dinge", icon: "💳" },
  { char: "开玩笑", pinyin: "kāiwánxiào", de: "Scherzen", en: "joke", es: "bromear", cat: "Verben", icon: "😄" },
  { char: "看法", pinyin: "kànfǎ", de: "Ansicht", en: "view", es: "opinión", cat: "Geist", icon: "👀" },
  { char: "考虑", pinyin: "kǎolǜ", de: "Überlegen", en: "consider", es: "considerar", cat: "Geist", icon: "🤔" },
  { char: "科学", pinyin: "kēxué", de: "Wissenschaft", en: "science", es: "ciencia", cat: "Schule", icon: "🔬" },
  { char: "可怜", pinyin: "kělián", de: "Arm", en: "pitiful", es: "pobre", cat: "Adjektive", icon: "🥺" },
  { char: "可惜", pinyin: "kěxī", de: "Schade", en: "pity", es: "lástima", cat: "Adjektive", icon: "😢" },
  { char: "客厅", pinyin: "kètīng", de: "Wohnzimmer", en: "living room", es: "salón", cat: "Orte", icon: "🛋️" },
  { char: "肯定", pinyin: "kěndìng", de: "Sicher", en: "certain", es: "seguro", cat: "Adverb", icon: "💯" },
  { char: "空", pinyin: "kōng", de: "Leer", en: "empty", es: "vacío", cat: "Adjektive", icon: "🈳" },
  { char: "恐怕", pinyin: "kǒngpà", de: "Befürchten", en: "afraid", es: "temer", cat: "Adverb", icon: "😰" },
  { char: "苦", pinyin: "kǔ", de: "Bitter", en: "bitter", es: "amargo", cat: "Essen", icon: "😖" },
  { char: "矿泉水", pinyin: "kuàngquánshuǐ", de: "Mineralwasser", en: "mineral water", es: "agua mineral", cat: "Essen", icon: "💧" },
  { char: "困", pinyin: "kùn", de: "Schläfrig", en: "sleepy", es: "soñoliento", cat: "Gefühle", icon: "😴" },
  { char: "困难", pinyin: "kùnnán", de: "Schwierigkeit", en: "difficulty", es: "dificultad", cat: "Geist", icon: "🧗" },
  { char: "拉", pinyin: "lā", de: "Ziehen", en: "pull", es: "tirar", cat: "Aktionen", icon: "🤚" },
  { char: "垃圾桶", pinyin: "lājītǒng", de: "Mülleimer", en: "trash can", es: "papelera", cat: "Dinge", icon: "🗑️" },
  { char: "辣", pinyin: "là", de: "Scharf", en: "spicy", es: "picante", cat: "Essen", icon: "🌶️" },
  { char: "来自", pinyin: "láizì", de: "Kommen aus", en: "come from", es: "venir de", cat: "Verben", icon: "🌍" },
  { char: "来得及", pinyin: "láidejí", de: "Rechtzeitig", en: "in time", es: "a tiempo", cat: "Zeit", icon: "⏰" },
  { char: "浪费", pinyin: "làngfèi", de: "Verschwenden", en: "waste", es: "desperdiciar", cat: "Verben", icon: "🗑️" },
  { char: "浪漫", pinyin: "làngmàn", de: "Romantisch", en: "romantic", es: "romántico", cat: "Adjektive", icon: "🌹" },
  { char: "老虎", pinyin: "lǎohǔ", de: "Tiger", en: "tiger", es: "tigre", cat: "Natur", icon: "🐅" },
  { char: "冷静", pinyin: "lěngjìng", de: "Ruhig", en: "calm", es: "calmado", cat: "Adjektive", icon: "🧊" },
  { char: "理发", pinyin: "lǐfà", de: "Friseur", en: "haircut", es: "corte de pelo", cat: "Aktionen", icon: "💇" },
  { char: "理解", pinyin: "lǐjiě", de: "Verstehen", en: "understand", es: "entender", cat: "Geist", icon: "💡" },
  { char: "理想", pinyin: "lǐxiǎng", de: "Ideal", en: "ideal", es: "ideal", cat: "Geist", icon: "✨" },
  { char: "力气", pinyin: "lìqi", de: "Kraft", en: "strength", es: "fuerza", cat: "Mensch", icon: "💪" },
  { char: "厉害", pinyin: "lìhai", de: "Beeindruckend", en: "awesome", es: "impresionante", cat: "Adjektive", icon: "🔥" },
  { char: "例如", pinyin: "lìrú", de: "Zum Beispiel", en: "for example", es: "por ejemplo", cat: "Grammatik", icon: "📝" },
  { char: "联系", pinyin: "liánxì", de: "Kontakt", en: "contact", es: "contacto", cat: "Aktionen", icon: "📞" },
  { char: "凉快", pinyin: "liángkuai", de: "Kühl", en: "cool", es: "fresco", cat: "Wetter", icon: "🌬️" },
  { char: "聊天", pinyin: "liáotiān", de: "Plaudern", en: "chat", es: "charlar", cat: "Verben", icon: "💬" },
  { char: "另外", pinyin: "lìngwài", de: "Außerdem", en: "besides", es: "además", cat: "Grammatik", icon: "➕" },
  { char: "留", pinyin: "liú", de: "Bleiben", en: "stay", es: "quedarse", cat: "Verben", icon: "🏠" },
  { char: "流利", pinyin: "liúlì", de: "Fließend", en: "fluent", es: "fluido", cat: "Adjektive", icon: "🗣️" },
  { char: "流行", pinyin: "liúxíng", de: "Beliebt", en: "popular", es: "popular", cat: "Adjektive", icon: "📈" },
  { char: "旅行", pinyin: "lǚxíng", de: "Reise", en: "travel", es: "viaje", cat: "Hobby", icon: "✈️" },
  { char: "律师", pinyin: "lǜshī", de: "Anwalt", en: "lawyer", es: "abogado", cat: "Personen", icon: "⚖️" },
  { char: "麻烦", pinyin: "máfan", de: "Ärger", en: "trouble", es: "molestia", cat: "Adjektive", icon: "😫" },
  { char: "满", pinyin: "mǎn", de: "Voll", en: "full", es: "lleno", cat: "Adjektive", icon: "🈵" },
  { char: "毛巾", pinyin: "máojīn", de: "Handtuch", en: "towel", es: "toalla", cat: "Dinge", icon: "🧴" },
  { char: "美丽", pinyin: "měilì", de: "Schön", en: "beautiful", es: "hermoso", cat: "Adjektive", icon: "🌸" },
  { char: "梦", pinyin: "mèng", de: "Traum", en: "dream", es: "sueño", cat: "Geist", icon: "💭" },
  { char: "密码", pinyin: "mìmǎ", de: "Passwort", en: "password", es: "contraseña", cat: "Dinge", icon: "🔐" },
  { char: "免费", pinyin: "miǎnfèi", de: "Kostenlos", en: "free", es: "gratis", cat: "Adjektive", icon: "🆓" },
  { char: "秒", pinyin: "miǎo", de: "Sekunde", en: "second", es: "segundo", cat: "Zeit", icon: "⏱️" },
  { char: "民族", pinyin: "mínzú", de: "Nation", en: "nation", es: "nación", cat: "Geist", icon: "🏳️" },
  { char: "母亲", pinyin: "mǔqīn", de: "Mutter", en: "mother", es: "madre", cat: "Personen", icon: "👩" },
  { char: "目的", pinyin: "mùdì", de: "Ziel", en: "purpose", es: "propósito", cat: "Geist", icon: "🎯" },
  { char: "内", pinyin: "nèi", de: "Innen", en: "inside", es: "dentro", cat: "Richtungen", icon: "📥" },
  { char: "内容", pinyin: "nèiróng", de: "Inhalt", en: "content", es: "contenido", cat: "Dinge", icon: "📦" },
  { char: "耐心", pinyin: "nàixīn", de: "Geduld", en: "patience", es: "paciencia", cat: "Emotion", icon: "🧘" },
  { char: "难道", pinyin: "nándào", de: "Etwa", en: "could it be", es: "acaso", cat: "Grammatik", icon: "❓" },
  { char: "难受", pinyin: "nánshòu", de: "Unwohl", en: "uncomfortable", es: "incómodo", cat: "Gefühle", icon: "😣" },
  { char: "能力", pinyin: "nénglì", de: "Fähigkeit", en: "ability", es: "habilidad", cat: "Geist", icon: "💪" },
  { char: "弄", pinyin: "nòng", de: "Machen", en: "do", es: "hacer", cat: "Verben", icon: "🔨" },
  { char: "暖和", pinyin: "nuǎnhuo", de: "Warm", en: "warm", es: "cálido", cat: "Wetter", icon: "☀️" },
  { char: "偶尔", pinyin: "ǒuěr", de: "Gelegentlich", en: "occasionally", es: "ocasionalmente", cat: "Adverb", icon: "🎲" }
];
